// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateAttendanceForTeam = `-- name: AggregateAttendanceForTeam :many
WITH events AS (
    SELECT g.id AS event_id, 'game'::text AS kind, g.kickoff_at AS starts_at
    FROM games g
    WHERE g.team_id = $1 AND g.status <> 'cancelled'
    UNION ALL
    SELECT s.id AS event_id, 'session'::text AS kind, s.scheduled_at AS starts_at
    FROM sessions s
    WHERE s.team_id = $1 AND s.deleted = false
), scoped AS (
    SELECT event_id, kind, starts_at FROM events
    WHERE ($2::bool OR kind <> 'game')
      AND ($3::bool OR kind <> 'session')
      AND ($4::timestamptz IS NULL OR starts_at >= $4)
      AND ($5::timestamptz IS NULL OR starts_at <= $5)
)
SELECT p.id AS person_id, p.display_name, r.jersey_number,
       count(*) AS events,
       count(*) FILTER (WHERE a.status = 'present') AS present,
       count(*) FILTER (WHERE a.status = 'absent')  AS absent,
       count(*) FILTER (WHERE a.status = 'late')    AS late,
       count(*) FILTER (WHERE a.status = 'excused') AS excused,
       count(*) FILTER (WHERE a.status IS NULL)     AS not_recorded,
       -- Said they were coming and did not turn up. The single most actionable number
       -- here after the rate, and one no per-fixture sheet can show: it only exists once
       -- the two halves of a line are read together across a season.
       count(*) FILTER (WHERE a.rsvp = 'going' AND a.status = 'absent') AS no_shows
FROM roster_memberships r
JOIN persons p ON p.id = r.person_id AND p.deleted = false
CROSS JOIN scoped e
LEFT JOIN attendances a
       ON a.person_id = r.person_id
      AND ((e.kind = 'game' AND a.game_id = e.event_id)
        OR (e.kind = 'session' AND a.session_id = e.event_id))
WHERE r.team_id = $1 AND r.left_on IS NULL
GROUP BY p.id, p.display_name, r.jersey_number
ORDER BY r.jersey_number NULLS LAST, p.display_name ASC
`

type AggregateAttendanceForTeamParams struct {
	TeamID          uuid.UUID          `json:"team_id"`
	IncludeGames    bool               `json:"include_games"`
	IncludeSessions bool               `json:"include_sessions"`
	StartingFrom    pgtype.Timestamptz `json:"starting_from"`
	StartingTo      pgtype.Timestamptz `json:"starting_to"`
}

type AggregateAttendanceForTeamRow struct {
	PersonID     uuid.UUID `json:"person_id"`
	DisplayName  string    `json:"display_name"`
	JerseyNumber *int32    `json:"jersey_number"`
	Events       int64     `json:"events"`
	Present      int64     `json:"present"`
	Absent       int64     `json:"absent"`
	Late         int64     `json:"late"`
	Excused      int64     `json:"excused"`
	NotRecorded  int64     `json:"not_recorded"`
	NoShows      int64     `json:"no_shows"`
}

// The register read down the season instead of across one fixture.
//
// A coach's real question is not "who is coming on Saturday" but "who keeps missing
// training", and until now the only way to ask it was to open every sheet in turn and
// count by hand. This is that count, one line per player.
//
// The universe is the active squad times the team's events in the window, not the
// attendance rows: a player who was never marked at all has to appear as somebody who
// missed six sessions, and driving this off `attendances` would show them as having a
// clean record because silence leaves no row. That is what `not_recorded` separates out —
// a squad nobody registered and a squad that turned up are the same numbers otherwise.
//
// A cancelled game drops out. Nobody attends a match that was called off, and counting it
// as an absence would punish a squad for a coach's decision.
//
// Rows with no date are in the window only when no window was asked for: `starts_at >=
// NULL` is NULL and so fails the filter, which is the wanted answer — a fixture with no
// time cannot be placed in March.
func (q *Queries) AggregateAttendanceForTeam(ctx context.Context, arg AggregateAttendanceForTeamParams) ([]AggregateAttendanceForTeamRow, error) {
	rows, err := q.db.Query(ctx, aggregateAttendanceForTeam,
		arg.TeamID,
		arg.IncludeGames,
		arg.IncludeSessions,
		arg.StartingFrom,
		arg.StartingTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateAttendanceForTeamRow
	for rows.Next() {
		var i AggregateAttendanceForTeamRow
		if err := rows.Scan(
			&i.PersonID,
			&i.DisplayName,
			&i.JerseyNumber,
			&i.Events,
			&i.Present,
			&i.Absent,
			&i.Late,
			&i.Excused,
			&i.NotRecorded,
			&i.NoShows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAnsweredAttendanceForSession = `-- name: CountAnsweredAttendanceForSession :one
SELECT count(*) FROM attendances
WHERE session_id = $1 AND (rsvp IS NOT NULL OR status IS NOT NULL)
`

// Whether a session's register has been started, which is what decides whether it may
// still be moved to another team.
//
// Counted on answers rather than rows: EnsureAttendance opens a blank line before either
// setter runs, so a row on its own means nothing happened. A line with an RSVP or a
// recorded status is somebody's statement about a specific squad's training, and carrying
// it over to a different squad would attribute it to people who were never asked.
func (q *Queries) CountAnsweredAttendanceForSession(ctx context.Context, sessionID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAnsweredAttendanceForSession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureAttendance = `-- name: EnsureAttendance :exec

INSERT INTO attendances (game_id, session_id, person_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type EnsureAttendanceParams struct {
	GameID    *uuid.UUID `json:"game_id"`
	SessionID *uuid.UUID `json:"session_id"`
	PersonID  uuid.UUID  `json:"person_id"`
}

// Attendance (RSVP + who actually came) ------------------------------------
// Open the row for (event, person) if it is not already open.
//
// Paired with one of the two setters below rather than folded into them as an upsert:
// the uniqueness that matters lives in two partial indexes (one per event kind, see
// 0014_attendance.sql), and ON CONFLICT can only infer one target, so an upsert would
// have to be written twice and each copy would silently cover only half the table. A
// bare DO NOTHING covers whichever index the row actually hits, and makes this safe to
// call on every write without asking first.
//
// The two statements do not need a transaction between them. An insert whose setter
// never ran leaves a row with no answer and no status, which is exactly the row that
// would have been read as "has not replied" had the insert not happened at all.
func (q *Queries) EnsureAttendance(ctx context.Context, arg EnsureAttendanceParams) error {
	_, err := q.db.Exec(ctx, ensureAttendance, arg.GameID, arg.SessionID, arg.PersonID)
	return err
}

const listAttendanceForEvent = `-- name: ListAttendanceForEvent :many
WITH people AS (
    SELECT r.person_id FROM roster_memberships r
    WHERE r.team_id = $1 AND r.left_on IS NULL
    UNION
    SELECT a.person_id FROM attendances a
    WHERE a.game_id = $2 OR a.session_id = $3
)
SELECT p.id AS person_id, p.display_name,
       r.jersey_number, r.position, (r.id IS NOT NULL)::bool AS on_roster,
       a.rsvp, a.rsvp_note, a.rsvp_at, a.rsvp_by_person_id,
       a.status, a.status_note, a.recorded_at, a.recorded_by_person_id
FROM people pe
JOIN persons p ON p.id = pe.person_id AND p.deleted = false
LEFT JOIN roster_memberships r
       ON r.person_id = pe.person_id AND r.team_id = $1 AND r.left_on IS NULL
LEFT JOIN attendances a
       ON a.person_id = pe.person_id
      AND (a.game_id = $2 OR a.session_id = $3)
WHERE $4::bool OR pe.person_id = ANY($5::uuid[])
ORDER BY r.jersey_number NULLS LAST, p.display_name ASC
`

type ListAttendanceForEventParams struct {
	TeamID    uuid.UUID   `json:"team_id"`
	GameID    *uuid.UUID  `json:"game_id"`
	SessionID *uuid.UUID  `json:"session_id"`
	AllPeople bool        `json:"all_people"`
	PersonIds []uuid.UUID `json:"person_ids"`
}

type ListAttendanceForEventRow struct {
	PersonID           uuid.UUID          `json:"person_id"`
	DisplayName        string             `json:"display_name"`
	JerseyNumber       *int32             `json:"jersey_number"`
	Position           *string            `json:"position"`
	OnRoster           bool               `json:"on_roster"`
	Rsvp               *string            `json:"rsvp"`
	RsvpNote           *string            `json:"rsvp_note"`
	RsvpAt             pgtype.Timestamptz `json:"rsvp_at"`
	RsvpByPersonID     *uuid.UUID         `json:"rsvp_by_person_id"`
	Status             *string            `json:"status"`
	StatusNote         *string            `json:"status_note"`
	RecordedAt         pgtype.Timestamptz `json:"recorded_at"`
	RecordedByPersonID *uuid.UUID         `json:"recorded_by_person_id"`
}

// The sheet: one line per person, whether or not they have answered.
//
// The people are the union of two sets, not just the current roster. A player who left
// the club in March was still at February's match, and driving this off
// roster_memberships alone would erase them from that game's record -- the attendance
// row would still exist, unreachable, and the coach's own count would disagree with it.
// `on_roster` is what tells the two apart on the far side.
//
// The union is a CTE over two indexed lookups rather than a scan of persons filtered by
// "on this team or at this event", which is the same set and reads every person in the
// database to find it.
//
// `all_people` narrows the result to named people without a second query: the RSVP and
// attendance writes each return the one line they changed, and re-reading a squad of
// twenty to answer with one of them is a query nobody asked for. Role scoping is
// deliberately NOT done here -- see handleGetAttendance, which needs the whole sheet to
// count it before narrowing what it shows.
func (q *Queries) ListAttendanceForEvent(ctx context.Context, arg ListAttendanceForEventParams) ([]ListAttendanceForEventRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceForEvent,
		arg.TeamID,
		arg.GameID,
		arg.SessionID,
		arg.AllPeople,
		arg.PersonIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttendanceForEventRow
	for rows.Next() {
		var i ListAttendanceForEventRow
		if err := rows.Scan(
			&i.PersonID,
			&i.DisplayName,
			&i.JerseyNumber,
			&i.Position,
			&i.OnRoster,
			&i.Rsvp,
			&i.RsvpNote,
			&i.RsvpAt,
			&i.RsvpByPersonID,
			&i.Status,
			&i.StatusNote,
			&i.RecordedAt,
			&i.RecordedByPersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAttendanceRSVP = `-- name: SetAttendanceRSVP :one
UPDATE attendances
SET rsvp              = $1::text,
    rsvp_note         = $2,
    rsvp_at           = now(),
    rsvp_by_person_id = $3,
    updated_at        = now()
WHERE person_id = $4
  AND (game_id = $5 OR session_id = $6)
RETURNING id, game_id, session_id, person_id, rsvp, rsvp_note, rsvp_at, rsvp_by_person_id, status, status_note, recorded_at, recorded_by_person_id, created_at, updated_at
`

type SetAttendanceRSVPParams struct {
	Rsvp           string     `json:"rsvp"`
	RsvpNote       *string    `json:"rsvp_note"`
	RsvpByPersonID *uuid.UUID `json:"rsvp_by_person_id"`
	PersonID       uuid.UUID  `json:"person_id"`
	GameID         *uuid.UUID `json:"game_id"`
	SessionID      *uuid.UUID `json:"session_id"`
}

// Record what a player said, and who said it. rsvp_by_person_id is the caller, which is
// not always the subject: a parent answers for a child, and a coach answers for a player
// with no login.
//
// The event is matched with an OR over the two nullable keys rather than a branch per
// kind. Exactly one of the arguments is ever non-NULL, and `column = NULL` is NULL and so
// never matches, which makes the unused half of the condition inert instead of wrong.
//
// Every field is written, with no set-flags: the endpoint is a PUT of one whole answer,
// so a reply sent without a note is a reply that has no note. That is the difference from
// SetAttendanceStatus below, which is a PATCH and has to tell absent from null.
func (q *Queries) SetAttendanceRSVP(ctx context.Context, arg SetAttendanceRSVPParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, setAttendanceRSVP,
		arg.Rsvp,
		arg.RsvpNote,
		arg.RsvpByPersonID,
		arg.PersonID,
		arg.GameID,
		arg.SessionID,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.SessionID,
		&i.PersonID,
		&i.Rsvp,
		&i.RsvpNote,
		&i.RsvpAt,
		&i.RsvpByPersonID,
		&i.Status,
		&i.StatusNote,
		&i.RecordedAt,
		&i.RecordedByPersonID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAttendanceStatus = `-- name: SetAttendanceStatus :one
UPDATE attendances
SET status      = CASE WHEN $1::bool THEN $2 ELSE status END,
    status_note = CASE WHEN $3::bool THEN $4 ELSE status_note END,
    recorded_at = CASE WHEN $1::bool
                       THEN CASE WHEN $2::text IS NULL THEN NULL ELSE now() END
                       ELSE recorded_at END,
    recorded_by_person_id = CASE WHEN $1::bool
                       THEN CASE WHEN $2::text IS NULL
                                 THEN NULL ELSE $5::uuid END
                       ELSE recorded_by_person_id END,
    updated_at  = now()
WHERE person_id = $6
  AND (game_id = $7 OR session_id = $8)
RETURNING id, game_id, session_id, person_id, rsvp, rsvp_note, rsvp_at, rsvp_by_person_id, status, status_note, recorded_at, recorded_by_person_id, created_at, updated_at
`

type SetAttendanceStatusParams struct {
	SetStatus          bool       `json:"set_status"`
	Status             *string    `json:"status"`
	SetStatusNote      bool       `json:"set_status_note"`
	StatusNote         *string    `json:"status_note"`
	RecordedByPersonID *uuid.UUID `json:"recorded_by_person_id"`
	PersonID           uuid.UUID  `json:"person_id"`
	GameID             *uuid.UUID `json:"game_id"`
	SessionID          *uuid.UUID `json:"session_id"`
}

// Record what happened, which is staff's to write.
//
// Clearing the status is a real operation, unlike clearing an RSVP: a coach who ticked
// the wrong player needs the row to go back to "not recorded", and there is no value in
// the vocabulary that means that. When the status goes the provenance goes with it --
// keeping a recorded_at for a status nobody holds would be a timestamp on nothing.
//
// Which makes each field a set-flag plus a nullable value, the shape UpdateGame settles
// on and for the same reason: this is a PATCH, so absent and null are different requests,
// and a single COALESCE has no way to say "clear it". Without the flags, a coach adding a
// note to a line would silently erase the status they had just recorded.
func (q *Queries) SetAttendanceStatus(ctx context.Context, arg SetAttendanceStatusParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, setAttendanceStatus,
		arg.SetStatus,
		arg.Status,
		arg.SetStatusNote,
		arg.StatusNote,
		arg.RecordedByPersonID,
		arg.PersonID,
		arg.GameID,
		arg.SessionID,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.SessionID,
		&i.PersonID,
		&i.Rsvp,
		&i.RsvpNote,
		&i.RsvpAt,
		&i.RsvpByPersonID,
		&i.Status,
		&i.StatusNote,
		&i.RecordedAt,
		&i.RecordedByPersonID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
