// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDrillsInOrgByIDs = `-- name: CountDrillsInOrgByIDs :one
SELECT count(*) FROM drills
WHERE id = ANY($1::uuid[]) AND organization_id = $2 AND deleted = false
`

type CountDrillsInOrgByIDsParams struct {
	Ids            []uuid.UUID `json:"ids"`
	OrganizationID uuid.UUID   `json:"organization_id"`
}

// How many of these ids are live drills in this organization. handleCreateSession asks
// once for every drill its blocks reference and compares the answer with the number of
// distinct ids it asked about; fewer means at least one block points at a drill that is
// deleted, missing, or another org's. Counting rather than returning the rows is enough
// because the request is rejected as a whole, and it keeps the check to one round trip
// however many blocks the session has.
func (q *Queries) CountDrillsInOrgByIDs(ctx context.Context, arg CountDrillsInOrgByIDsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDrillsInOrgByIDs, arg.Ids, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDrill = `-- name: CreateDrill :one

INSERT INTO drills (id, organization_id, author_person_id, sync_account_id, name, description, payload, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, nextval('sync_seq'))
RETURNING id, organization_id, author_person_id, name, description, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreateDrillParams struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	AuthorPersonID *uuid.UUID `json:"author_person_id"`
	SyncAccountID  *uuid.UUID `json:"sync_account_id"`
	Name           string     `json:"name"`
	Description    *string    `json:"description"`
	Payload        []byte     `json:"payload"`
}

// Drills --------------------------------------------------------------------
// A drill created here is a drill the app can see, for the reasons CreateTeam sets out:
// sync_account_id puts the row in the caller's stream, seq gives a cursor something to
// deliver, and payload is what a pull actually returns.
//
// The payload carries only id, title and fieldSetup, because that is all POST /drills
// collects. Until now the app required a category, a duration and coaching points as
// well, so a drill made this way could not be decoded at all and was dropped whole --
// Codable loses the record over one missing key. Those fields are optional on the app
// side now, so the drill arrives with blanks the coach can fill in rather than not
// arriving. Inventing a category here was the alternative, and putting a coaching
// decision nobody made into a coach's library is worse than leaving it empty.
func (q *Queries) CreateDrill(ctx context.Context, arg CreateDrillParams) (Drill, error) {
	row := q.db.QueryRow(ctx, createDrill,
		arg.ID,
		arg.OrganizationID,
		arg.AuthorPersonID,
		arg.SyncAccountID,
		arg.Name,
		arg.Description,
		arg.Payload,
	)
	var i Drill
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one

INSERT INTO games (organization_id, team_id, opponent, kickoff_at, home_away)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, team_id, opponent, kickoff_at, home_away, our_score, opponent_score, status, created_at, updated_at
`

type CreateGameParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	TeamID         uuid.UUID          `json:"team_id"`
	Opponent       *string            `json:"opponent"`
	KickoffAt      pgtype.Timestamptz `json:"kickoff_at"`
	HomeAway       *string            `json:"home_away"`
}

// Games (game day) ----------------------------------------------------------
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.OrganizationID,
		arg.TeamID,
		arg.Opponent,
		arg.KickoffAt,
		arg.HomeAway,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Opponent,
		&i.KickoffAt,
		&i.HomeAway,
		&i.OurScore,
		&i.OpponentScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, organization_id, author_person_id, sync_account_id, team_id, title, scheduled_at, notes, payload, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, nextval('sync_seq'))
RETURNING id, organization_id, author_person_id, team_id, title, scheduled_at, notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreateSessionParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	AuthorPersonID *uuid.UUID         `json:"author_person_id"`
	SyncAccountID  *uuid.UUID         `json:"sync_account_id"`
	TeamID         *uuid.UUID         `json:"team_id"`
	Title          string             `json:"title"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	Notes          *string            `json:"notes"`
	Payload        []byte             `json:"payload"`
}

// Sessions ------------------------------------------------------------------
// Same three columns as CreateDrill, and one field that needs saying out loud: the app
// requires a date and the server always has one, so the payload carries scheduled_at
// when it was given and the creation time when it was not. It is written as a number of
// seconds since 2001-01-01, which is how Swift encodes a Date -- see
// TestContractSwiftDatesSurviveAsNumbers, which pins that against this side drifting.
//
// teamID and each block's drillID may be absent. Both were required by the app until
// now, and both are things this API has always let a caller leave out, so a session
// without a team, or with a warm-up block that runs no drill, simply never arrived.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.OrganizationID,
		arg.AuthorPersonID,
		arg.SyncAccountID,
		arg.TeamID,
		arg.Title,
		arg.ScheduledAt,
		arg.Notes,
		arg.Payload,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.TeamID,
		&i.Title,
		&i.ScheduledAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const createSessionBlock = `-- name: CreateSessionBlock :one
INSERT INTO session_blocks (id, session_id, drill_id, title, duration_min, position, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, session_id, drill_id, title, duration_min, position, notes
`

type CreateSessionBlockParams struct {
	ID          uuid.UUID  `json:"id"`
	SessionID   uuid.UUID  `json:"session_id"`
	DrillID     *uuid.UUID `json:"drill_id"`
	Title       string     `json:"title"`
	DurationMin *int32     `json:"duration_min"`
	Position    int32      `json:"position"`
	Notes       *string    `json:"notes"`
}

// The id is supplied rather than defaulted, because the session's payload has to carry
// each block's id and is written in the same statement as the session itself.
func (q *Queries) CreateSessionBlock(ctx context.Context, arg CreateSessionBlockParams) (SessionBlock, error) {
	row := q.db.QueryRow(ctx, createSessionBlock,
		arg.ID,
		arg.SessionID,
		arg.DrillID,
		arg.Title,
		arg.DurationMin,
		arg.Position,
		arg.Notes,
	)
	var i SessionBlock
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DrillID,
		&i.Title,
		&i.DurationMin,
		&i.Position,
		&i.Notes,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
UPDATE sessions SET deleted = true, seq = nextval('sync_seq'), updated_at = now(),
    title = '', notes = NULL, payload = NULL
WHERE id = $1
`

// Tombstoned, not dropped — see DeleteTeam.
func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getDrill = `-- name: GetDrill :one
SELECT id, organization_id, author_person_id, name, description, created_at, updated_at, sync_account_id, payload, deleted, seq FROM drills WHERE id = $1 AND deleted = false
`

func (q *Queries) GetDrill(ctx context.Context, id uuid.UUID) (Drill, error) {
	row := q.db.QueryRow(ctx, getDrill, id)
	var i Drill
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, organization_id, team_id, opponent, kickoff_at, home_away, our_score, opponent_score, status, created_at, updated_at FROM games WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Opponent,
		&i.KickoffAt,
		&i.HomeAway,
		&i.OurScore,
		&i.OpponentScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, organization_id, author_person_id, team_id, title, scheduled_at, notes, created_at, updated_at, sync_account_id, payload, deleted, seq FROM sessions WHERE id = $1 AND deleted = false
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.TeamID,
		&i.Title,
		&i.ScheduledAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const listDrillsInOrg = `-- name: ListDrillsInOrg :many
SELECT id, organization_id, author_person_id, name, description, created_at, updated_at, sync_account_id, payload, deleted, seq FROM drills WHERE organization_id = $1 AND deleted = false ORDER BY name ASC
`

func (q *Queries) ListDrillsInOrg(ctx context.Context, organizationID uuid.UUID) ([]Drill, error) {
	rows, err := q.db.Query(ctx, listDrillsInOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drill
	for rows.Next() {
		var i Drill
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AuthorPersonID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesForTeam = `-- name: ListGamesForTeam :many
SELECT id, organization_id, team_id, opponent, kickoff_at, home_away, our_score, opponent_score, status, created_at, updated_at FROM games WHERE team_id = $1 ORDER BY kickoff_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListGamesForTeam(ctx context.Context, teamID uuid.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.Opponent,
			&i.KickoffAt,
			&i.HomeAway,
			&i.OurScore,
			&i.OpponentScore,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionBlocks = `-- name: ListSessionBlocks :many
SELECT sb.id, sb.session_id, sb.drill_id, sb.title, sb.duration_min, sb.position, sb.notes, d.name AS drill_name
FROM session_blocks sb
LEFT JOIN drills d ON d.id = sb.drill_id
WHERE sb.session_id = $1
ORDER BY sb.position, sb.title
`

type ListSessionBlocksRow struct {
	ID          uuid.UUID  `json:"id"`
	SessionID   uuid.UUID  `json:"session_id"`
	DrillID     *uuid.UUID `json:"drill_id"`
	Title       string     `json:"title"`
	DurationMin *int32     `json:"duration_min"`
	Position    int32      `json:"position"`
	Notes       *string    `json:"notes"`
	DrillName   *string    `json:"drill_name"`
}

func (q *Queries) ListSessionBlocks(ctx context.Context, sessionID uuid.UUID) ([]ListSessionBlocksRow, error) {
	rows, err := q.db.Query(ctx, listSessionBlocks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionBlocksRow
	for rows.Next() {
		var i ListSessionBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DrillID,
			&i.Title,
			&i.DurationMin,
			&i.Position,
			&i.Notes,
			&i.DrillName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsInOrg = `-- name: ListSessionsInOrg :many
SELECT id, organization_id, author_person_id, team_id, title, scheduled_at, notes, created_at, updated_at, sync_account_id, payload, deleted, seq FROM sessions
WHERE organization_id = $1
  AND deleted = false
  AND ($2::uuid IS NULL OR team_id = $2)
ORDER BY scheduled_at DESC NULLS LAST, created_at DESC
`

type ListSessionsInOrgParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	TeamID         *uuid.UUID `json:"team_id"`
}

func (q *Queries) ListSessionsInOrg(ctx context.Context, arg ListSessionsInOrgParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsInOrg, arg.OrganizationID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AuthorPersonID,
			&i.TeamID,
			&i.Title,
			&i.ScheduledAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET opponent       = CASE WHEN $1::bool THEN $2 ELSE opponent END,
    kickoff_at     = CASE WHEN $3::bool THEN $4 ELSE kickoff_at END,
    home_away      = CASE WHEN $5::bool THEN $6 ELSE home_away END,
    our_score      = CASE WHEN $7::bool THEN $8 ELSE our_score END,
    opponent_score = CASE WHEN $7::bool THEN $9 ELSE opponent_score END,
    status         = COALESCE($10, status),
    updated_at     = now()
WHERE id = $11
RETURNING id, organization_id, team_id, opponent, kickoff_at, home_away, our_score, opponent_score, status, created_at, updated_at
`

type UpdateGameParams struct {
	SetOpponent   bool               `json:"set_opponent"`
	Opponent      *string            `json:"opponent"`
	SetKickoffAt  bool               `json:"set_kickoff_at"`
	KickoffAt     pgtype.Timestamptz `json:"kickoff_at"`
	SetHomeAway   bool               `json:"set_home_away"`
	HomeAway      *string            `json:"home_away"`
	SetScores     bool               `json:"set_scores"`
	OurScore      *int32             `json:"our_score"`
	OpponentScore *int32             `json:"opponent_score"`
	Status        *string            `json:"status"`
	ID            uuid.UUID          `json:"id"`
}

// Every clearable field is a set-flag plus a nullable value, kickoff_at included. It
// used to be COALESCE(narg, kickoff_at), which reads NULL as "leave this alone" and so
// leaves no value that means "clear it": a cancelled fixture's kickoff time could not be
// unset. See docs/AUDIT-2.md L3.
func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.SetOpponent,
		arg.Opponent,
		arg.SetKickoffAt,
		arg.KickoffAt,
		arg.SetHomeAway,
		arg.HomeAway,
		arg.SetScores,
		arg.OurScore,
		arg.OpponentScore,
		arg.Status,
		arg.ID,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Opponent,
		&i.KickoffAt,
		&i.HomeAway,
		&i.OurScore,
		&i.OpponentScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET title        = COALESCE($1, title),
    scheduled_at = CASE WHEN $2::bool THEN $3 ELSE scheduled_at END,
    notes        = CASE WHEN $4::bool THEN $5 ELSE notes END,
    team_id      = CASE WHEN $6::bool THEN $7 ELSE team_id END,
    payload      = CASE WHEN $8::bool
                        THEN COALESCE(payload, '{}'::jsonb) || $9::jsonb
                        ELSE payload END,
    seq          = nextval('sync_seq'),
    updated_at   = now()
WHERE id = $10
RETURNING id, organization_id, author_person_id, team_id, title, scheduled_at, notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type UpdateSessionParams struct {
	Title          *string            `json:"title"`
	SetScheduledAt bool               `json:"set_scheduled_at"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	SetNotes       bool               `json:"set_notes"`
	Notes          *string            `json:"notes"`
	SetTeamID      bool               `json:"set_team_id"`
	TeamID         *uuid.UUID         `json:"team_id"`
	PatchPayload   bool               `json:"patch_payload"`
	PayloadPatch   []byte             `json:"payload_patch"`
	ID             uuid.UUID          `json:"id"`
}

// Sessions could be created and deleted over REST but never edited, so a coach who moved
// Tuesday training to Thursday had to delete the session and build it again -- taking its
// register with it, now that a session has one. It is the same gap UpdateTeam closed for
// teams, arriving late because nothing scheduled by a session used to be attended.
//
// Written twice, into the columns this API reads and into the payload a pull returns, for
// the reason UpdateTeam sets out at length: a pull returns `payload`, so a column-only
// edit is invisible on the phone and the app's next push writes the old values straight
// back over it, with nothing logged and nobody told.
//
// Blocks are deliberately untouched. They are an ordered collection whose ids the payload
// carries, so replacing them is a different operation from editing the session's own
// fields -- folding the two together would mean every rename rewrote the plan, and a
// caller who sent no blocks would erase one.
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.Title,
		arg.SetScheduledAt,
		arg.ScheduledAt,
		arg.SetNotes,
		arg.Notes,
		arg.SetTeamID,
		arg.TeamID,
		arg.PatchPayload,
		arg.PayloadPatch,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.TeamID,
		&i.Title,
		&i.ScheduledAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}
