// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDrill = `-- name: CreateDrill :one

INSERT INTO drills (organization_id, author_person_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, author_person_id, name, description, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreateDrillParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	AuthorPersonID *uuid.UUID `json:"author_person_id"`
	Name           string     `json:"name"`
	Description    *string    `json:"description"`
}

// Drills --------------------------------------------------------------------
func (q *Queries) CreateDrill(ctx context.Context, arg CreateDrillParams) (Drill, error) {
	row := q.db.QueryRow(ctx, createDrill,
		arg.OrganizationID,
		arg.AuthorPersonID,
		arg.Name,
		arg.Description,
	)
	var i Drill
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one

INSERT INTO games (organization_id, team_id, opponent, kickoff_at, home_away)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, team_id, opponent, kickoff_at, home_away, our_score, opponent_score, status, created_at, updated_at
`

type CreateGameParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	TeamID         uuid.UUID          `json:"team_id"`
	Opponent       *string            `json:"opponent"`
	KickoffAt      pgtype.Timestamptz `json:"kickoff_at"`
	HomeAway       *string            `json:"home_away"`
}

// Games (game day) ----------------------------------------------------------
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.OrganizationID,
		arg.TeamID,
		arg.Opponent,
		arg.KickoffAt,
		arg.HomeAway,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Opponent,
		&i.KickoffAt,
		&i.HomeAway,
		&i.OurScore,
		&i.OpponentScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (organization_id, author_person_id, team_id, title, scheduled_at, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, author_person_id, team_id, title, scheduled_at, notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreateSessionParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	AuthorPersonID *uuid.UUID         `json:"author_person_id"`
	TeamID         *uuid.UUID         `json:"team_id"`
	Title          string             `json:"title"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	Notes          *string            `json:"notes"`
}

// Sessions ------------------------------------------------------------------
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.OrganizationID,
		arg.AuthorPersonID,
		arg.TeamID,
		arg.Title,
		arg.ScheduledAt,
		arg.Notes,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.TeamID,
		&i.Title,
		&i.ScheduledAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const createSessionBlock = `-- name: CreateSessionBlock :one
INSERT INTO session_blocks (session_id, drill_id, title, duration_min, position, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, drill_id, title, duration_min, position, notes
`

type CreateSessionBlockParams struct {
	SessionID   uuid.UUID  `json:"session_id"`
	DrillID     *uuid.UUID `json:"drill_id"`
	Title       string     `json:"title"`
	DurationMin *int32     `json:"duration_min"`
	Position    int32      `json:"position"`
	Notes       *string    `json:"notes"`
}

func (q *Queries) CreateSessionBlock(ctx context.Context, arg CreateSessionBlockParams) (SessionBlock, error) {
	row := q.db.QueryRow(ctx, createSessionBlock,
		arg.SessionID,
		arg.DrillID,
		arg.Title,
		arg.DurationMin,
		arg.Position,
		arg.Notes,
	)
	var i SessionBlock
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DrillID,
		&i.Title,
		&i.DurationMin,
		&i.Position,
		&i.Notes,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getDrill = `-- name: GetDrill :one
SELECT id, organization_id, author_person_id, name, description, created_at, updated_at, sync_account_id, payload, deleted, seq FROM drills WHERE id = $1
`

func (q *Queries) GetDrill(ctx context.Context, id uuid.UUID) (Drill, error) {
	row := q.db.QueryRow(ctx, getDrill, id)
	var i Drill
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, organization_id, team_id, opponent, kickoff_at, home_away, our_score, opponent_score, status, created_at, updated_at FROM games WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Opponent,
		&i.KickoffAt,
		&i.HomeAway,
		&i.OurScore,
		&i.OpponentScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, organization_id, author_person_id, team_id, title, scheduled_at, notes, created_at, updated_at, sync_account_id, payload, deleted, seq FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.TeamID,
		&i.Title,
		&i.ScheduledAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const listDrillsInOrg = `-- name: ListDrillsInOrg :many
SELECT id, organization_id, author_person_id, name, description, created_at, updated_at, sync_account_id, payload, deleted, seq FROM drills WHERE organization_id = $1 ORDER BY name ASC
`

func (q *Queries) ListDrillsInOrg(ctx context.Context, organizationID uuid.UUID) ([]Drill, error) {
	rows, err := q.db.Query(ctx, listDrillsInOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drill
	for rows.Next() {
		var i Drill
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AuthorPersonID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesForTeam = `-- name: ListGamesForTeam :many
SELECT id, organization_id, team_id, opponent, kickoff_at, home_away, our_score, opponent_score, status, created_at, updated_at FROM games WHERE team_id = $1 ORDER BY kickoff_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListGamesForTeam(ctx context.Context, teamID uuid.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.Opponent,
			&i.KickoffAt,
			&i.HomeAway,
			&i.OurScore,
			&i.OpponentScore,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionBlocks = `-- name: ListSessionBlocks :many
SELECT sb.id, sb.session_id, sb.drill_id, sb.title, sb.duration_min, sb.position, sb.notes, d.name AS drill_name
FROM session_blocks sb
LEFT JOIN drills d ON d.id = sb.drill_id
WHERE sb.session_id = $1
ORDER BY sb.position, sb.title
`

type ListSessionBlocksRow struct {
	ID          uuid.UUID  `json:"id"`
	SessionID   uuid.UUID  `json:"session_id"`
	DrillID     *uuid.UUID `json:"drill_id"`
	Title       string     `json:"title"`
	DurationMin *int32     `json:"duration_min"`
	Position    int32      `json:"position"`
	Notes       *string    `json:"notes"`
	DrillName   *string    `json:"drill_name"`
}

func (q *Queries) ListSessionBlocks(ctx context.Context, sessionID uuid.UUID) ([]ListSessionBlocksRow, error) {
	rows, err := q.db.Query(ctx, listSessionBlocks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionBlocksRow
	for rows.Next() {
		var i ListSessionBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DrillID,
			&i.Title,
			&i.DurationMin,
			&i.Position,
			&i.Notes,
			&i.DrillName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsInOrg = `-- name: ListSessionsInOrg :many
SELECT id, organization_id, author_person_id, team_id, title, scheduled_at, notes, created_at, updated_at, sync_account_id, payload, deleted, seq FROM sessions
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR team_id = $2)
ORDER BY scheduled_at DESC NULLS LAST, created_at DESC
`

type ListSessionsInOrgParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	TeamID         *uuid.UUID `json:"team_id"`
}

func (q *Queries) ListSessionsInOrg(ctx context.Context, arg ListSessionsInOrgParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsInOrg, arg.OrganizationID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AuthorPersonID,
			&i.TeamID,
			&i.Title,
			&i.ScheduledAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET opponent       = CASE WHEN $1::bool THEN $2 ELSE opponent END,
    kickoff_at     = COALESCE($3, kickoff_at),
    home_away      = CASE WHEN $4::bool THEN $5 ELSE home_away END,
    our_score      = CASE WHEN $6::bool THEN $7 ELSE our_score END,
    opponent_score = CASE WHEN $6::bool THEN $8 ELSE opponent_score END,
    status         = COALESCE($9, status),
    updated_at     = now()
WHERE id = $10
RETURNING id, organization_id, team_id, opponent, kickoff_at, home_away, our_score, opponent_score, status, created_at, updated_at
`

type UpdateGameParams struct {
	SetOpponent   bool               `json:"set_opponent"`
	Opponent      *string            `json:"opponent"`
	KickoffAt     pgtype.Timestamptz `json:"kickoff_at"`
	SetHomeAway   bool               `json:"set_home_away"`
	HomeAway      *string            `json:"home_away"`
	SetScores     bool               `json:"set_scores"`
	OurScore      *int32             `json:"our_score"`
	OpponentScore *int32             `json:"opponent_score"`
	Status        *string            `json:"status"`
	ID            uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.SetOpponent,
		arg.Opponent,
		arg.KickoffAt,
		arg.SetHomeAway,
		arg.HomeAway,
		arg.SetScores,
		arg.OurScore,
		arg.OpponentScore,
		arg.Status,
		arg.ID,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Opponent,
		&i.KickoffAt,
		&i.HomeAway,
		&i.OurScore,
		&i.OpponentScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
