// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :execrows
DELETE FROM device_tokens WHERE token = $1 AND person_id = $2
`

type DeleteDeviceTokenParams struct {
	Token    string    `json:"token"`
	PersonID uuid.UUID `json:"person_id"`
}

// Scoped to the owner, so holding a token is not enough to unregister someone else's
// device. Sign-out is the ordinary caller.
func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceToken, arg.Token, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeviceTokenAnyOwner = `-- name: DeleteDeviceTokenAnyOwner :exec
DELETE FROM device_tokens WHERE token = $1
`

// Pruning after Apple rejects a token, which is not scoped to a person on purpose: the
// rejection says this token is dead everywhere, and the row may well belong to whoever
// registered it before the device changed hands.
func (q *Queries) DeleteDeviceTokenAnyOwner(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokenAnyOwner, token)
	return err
}

const listDeviceTokensForPerson = `-- name: ListDeviceTokensForPerson :many
SELECT token FROM device_tokens WHERE person_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) ListDeviceTokensForPerson(ctx context.Context, personID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (token, person_id, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
SET person_id = EXCLUDED.person_id, platform = EXCLUDED.platform, last_seen_at = now()
RETURNING token, person_id, platform, created_at, last_seen_at
`

type UpsertDeviceTokenParams struct {
	Token    string    `json:"token"`
	PersonID uuid.UUID `json:"person_id"`
	Platform string    `json:"platform"`
}

// Registering is idempotent and re-points the token at whoever is signed in now. See
// 0012_device_tokens.sql for why the token owns the row rather than the person.
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.Token, arg.PersonID, arg.Platform)
	var i DeviceToken
	err := row.Scan(
		&i.Token,
		&i.PersonID,
		&i.Platform,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
