// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateScoresForPerson = `-- name: AggregateScoresForPerson :many
SELECT ff.key, ff.label,
    count(fa.numeric_value)::bigint      AS samples,
    avg(fa.numeric_value)::double precision AS average,
    min(fa.numeric_value)::double precision AS minimum,
    max(fa.numeric_value)::double precision AS maximum
FROM form_instances fi
JOIN form_templates ft ON ft.id = fi.template_id
JOIN form_answers fa ON fa.instance_id = fi.id
JOIN form_fields ff ON ff.id = fa.field_id
WHERE fi.subject_person_id = $1
  AND ($2::text IS NULL OR ft.context = $2)
  AND fa.numeric_value IS NOT NULL
GROUP BY ff.key, ff.label
ORDER BY ff.key
`

type AggregateScoresForPersonParams struct {
	SubjectPersonID *uuid.UUID `json:"subject_person_id"`
	Context         *string    `json:"context"`
}

type AggregateScoresForPersonRow struct {
	Key     string  `json:"key"`
	Label   string  `json:"label"`
	Samples int64   `json:"samples"`
	Average float64 `json:"average"`
	Minimum float64 `json:"minimum"`
	Maximum float64 `json:"maximum"`
}

// The moat query: cross-instance aggregation of scored fields for one athlete,
// optionally scoped to a context. Powers readiness means, effort trends, etc.
func (q *Queries) AggregateScoresForPerson(ctx context.Context, arg AggregateScoresForPersonParams) ([]AggregateScoresForPersonRow, error) {
	rows, err := q.db.Query(ctx, aggregateScoresForPerson, arg.SubjectPersonID, arg.Context)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateScoresForPersonRow
	for rows.Next() {
		var i AggregateScoresForPersonRow
		if err := rows.Scan(
			&i.Key,
			&i.Label,
			&i.Samples,
			&i.Average,
			&i.Minimum,
			&i.Maximum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFormAnswer = `-- name: CreateFormAnswer :one
INSERT INTO form_answers (instance_id, field_id, numeric_value, bool_value, text_value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (instance_id, field_id)
DO UPDATE SET numeric_value = EXCLUDED.numeric_value, bool_value = EXCLUDED.bool_value, text_value = EXCLUDED.text_value
RETURNING id, instance_id, field_id, numeric_value, bool_value, text_value
`

type CreateFormAnswerParams struct {
	InstanceID   uuid.UUID `json:"instance_id"`
	FieldID      uuid.UUID `json:"field_id"`
	NumericValue *float64  `json:"numeric_value"`
	BoolValue    *bool     `json:"bool_value"`
	TextValue    *string   `json:"text_value"`
}

func (q *Queries) CreateFormAnswer(ctx context.Context, arg CreateFormAnswerParams) (FormAnswer, error) {
	row := q.db.QueryRow(ctx, createFormAnswer,
		arg.InstanceID,
		arg.FieldID,
		arg.NumericValue,
		arg.BoolValue,
		arg.TextValue,
	)
	var i FormAnswer
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.FieldID,
		&i.NumericValue,
		&i.BoolValue,
		&i.TextValue,
	)
	return i, err
}

const createFormField = `-- name: CreateFormField :one
INSERT INTO form_fields (template_id, key, label, kind, position, config)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, template_id, key, label, kind, position, config
`

type CreateFormFieldParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	Key        string    `json:"key"`
	Label      string    `json:"label"`
	Kind       string    `json:"kind"`
	Position   int32     `json:"position"`
	Config     []byte    `json:"config"`
}

func (q *Queries) CreateFormField(ctx context.Context, arg CreateFormFieldParams) (FormField, error) {
	row := q.db.QueryRow(ctx, createFormField,
		arg.TemplateID,
		arg.Key,
		arg.Label,
		arg.Kind,
		arg.Position,
		arg.Config,
	)
	var i FormField
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.Position,
		&i.Config,
	)
	return i, err
}

const createFormInstance = `-- name: CreateFormInstance :one

INSERT INTO form_instances
    (template_id, subject_person_id, subject_team_id, context_ref_type, context_ref_id, submitted_by_person_id, extra)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, template_id, subject_person_id, subject_team_id, context_ref_type, context_ref_id, submitted_by_person_id, submitted_at, extra, created_at
`

type CreateFormInstanceParams struct {
	TemplateID          uuid.UUID  `json:"template_id"`
	SubjectPersonID     *uuid.UUID `json:"subject_person_id"`
	SubjectTeamID       *uuid.UUID `json:"subject_team_id"`
	ContextRefType      *string    `json:"context_ref_type"`
	ContextRefID        *uuid.UUID `json:"context_ref_id"`
	SubmittedByPersonID *uuid.UUID `json:"submitted_by_person_id"`
	Extra               []byte     `json:"extra"`
}

// Instances & answers -------------------------------------------------------
func (q *Queries) CreateFormInstance(ctx context.Context, arg CreateFormInstanceParams) (FormInstance, error) {
	row := q.db.QueryRow(ctx, createFormInstance,
		arg.TemplateID,
		arg.SubjectPersonID,
		arg.SubjectTeamID,
		arg.ContextRefType,
		arg.ContextRefID,
		arg.SubmittedByPersonID,
		arg.Extra,
	)
	var i FormInstance
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.SubjectPersonID,
		&i.SubjectTeamID,
		&i.ContextRefType,
		&i.ContextRefID,
		&i.SubmittedByPersonID,
		&i.SubmittedAt,
		&i.Extra,
		&i.CreatedAt,
	)
	return i, err
}

const createFormTemplate = `-- name: CreateFormTemplate :one

INSERT INTO form_templates (organization_id, author_person_id, context, name, subject_type, version, is_seed)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, 1), COALESCE($7, false))
RETURNING id, organization_id, author_person_id, context, name, subject_type, version, is_seed, created_at, updated_at
`

type CreateFormTemplateParams struct {
	OrganizationID *uuid.UUID  `json:"organization_id"`
	AuthorPersonID *uuid.UUID  `json:"author_person_id"`
	Context        string      `json:"context"`
	Name           string      `json:"name"`
	SubjectType    string      `json:"subject_type"`
	Version        interface{} `json:"version"`
	IsSeed         interface{} `json:"is_seed"`
}

// Templates ----------------------------------------------------------------
func (q *Queries) CreateFormTemplate(ctx context.Context, arg CreateFormTemplateParams) (FormTemplate, error) {
	row := q.db.QueryRow(ctx, createFormTemplate,
		arg.OrganizationID,
		arg.AuthorPersonID,
		arg.Context,
		arg.Name,
		arg.SubjectType,
		arg.Version,
		arg.IsSeed,
	)
	var i FormTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.Context,
		&i.Name,
		&i.SubjectType,
		&i.Version,
		&i.IsSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormFieldByKey = `-- name: GetFormFieldByKey :one
SELECT id, template_id, key, label, kind, position, config FROM form_fields WHERE template_id = $1 AND key = $2
`

type GetFormFieldByKeyParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	Key        string    `json:"key"`
}

func (q *Queries) GetFormFieldByKey(ctx context.Context, arg GetFormFieldByKeyParams) (FormField, error) {
	row := q.db.QueryRow(ctx, getFormFieldByKey, arg.TemplateID, arg.Key)
	var i FormField
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.Position,
		&i.Config,
	)
	return i, err
}

const getFormInstance = `-- name: GetFormInstance :one
SELECT id, template_id, subject_person_id, subject_team_id, context_ref_type, context_ref_id, submitted_by_person_id, submitted_at, extra, created_at FROM form_instances WHERE id = $1
`

func (q *Queries) GetFormInstance(ctx context.Context, id uuid.UUID) (FormInstance, error) {
	row := q.db.QueryRow(ctx, getFormInstance, id)
	var i FormInstance
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.SubjectPersonID,
		&i.SubjectTeamID,
		&i.ContextRefType,
		&i.ContextRefID,
		&i.SubmittedByPersonID,
		&i.SubmittedAt,
		&i.Extra,
		&i.CreatedAt,
	)
	return i, err
}

const getFormTemplate = `-- name: GetFormTemplate :one
SELECT id, organization_id, author_person_id, context, name, subject_type, version, is_seed, created_at, updated_at FROM form_templates WHERE id = $1
`

func (q *Queries) GetFormTemplate(ctx context.Context, id uuid.UUID) (FormTemplate, error) {
	row := q.db.QueryRow(ctx, getFormTemplate, id)
	var i FormTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorPersonID,
		&i.Context,
		&i.Name,
		&i.SubjectType,
		&i.Version,
		&i.IsSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnswersForInstance = `-- name: ListAnswersForInstance :many
SELECT fa.id, fa.instance_id, fa.field_id, fa.numeric_value, fa.bool_value, fa.text_value, ff.key, ff.label, ff.kind
FROM form_answers fa
JOIN form_fields ff ON ff.id = fa.field_id
WHERE fa.instance_id = $1
ORDER BY ff.position, ff.key
`

type ListAnswersForInstanceRow struct {
	ID           uuid.UUID `json:"id"`
	InstanceID   uuid.UUID `json:"instance_id"`
	FieldID      uuid.UUID `json:"field_id"`
	NumericValue *float64  `json:"numeric_value"`
	BoolValue    *bool     `json:"bool_value"`
	TextValue    *string   `json:"text_value"`
	Key          string    `json:"key"`
	Label        string    `json:"label"`
	Kind         string    `json:"kind"`
}

func (q *Queries) ListAnswersForInstance(ctx context.Context, instanceID uuid.UUID) ([]ListAnswersForInstanceRow, error) {
	rows, err := q.db.Query(ctx, listAnswersForInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswersForInstanceRow
	for rows.Next() {
		var i ListAnswersForInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.FieldID,
			&i.NumericValue,
			&i.BoolValue,
			&i.TextValue,
			&i.Key,
			&i.Label,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormFields = `-- name: ListFormFields :many
SELECT id, template_id, key, label, kind, position, config FROM form_fields WHERE template_id = $1 ORDER BY position, key
`

func (q *Queries) ListFormFields(ctx context.Context, templateID uuid.UUID) ([]FormField, error) {
	rows, err := q.db.Query(ctx, listFormFields, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormField
	for rows.Next() {
		var i FormField
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Key,
			&i.Label,
			&i.Kind,
			&i.Position,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormTemplates = `-- name: ListFormTemplates :many
SELECT id, organization_id, author_person_id, context, name, subject_type, version, is_seed, created_at, updated_at FROM form_templates
WHERE (organization_id = $1 OR author_person_id = $2)
  AND ($3::text IS NULL OR context = $3)
ORDER BY context, name
`

type ListFormTemplatesParams struct {
	OrganizationID *uuid.UUID `json:"organization_id"`
	AuthorPersonID *uuid.UUID `json:"author_person_id"`
	Context        *string    `json:"context"`
}

func (q *Queries) ListFormTemplates(ctx context.Context, arg ListFormTemplatesParams) ([]FormTemplate, error) {
	rows, err := q.db.Query(ctx, listFormTemplates, arg.OrganizationID, arg.AuthorPersonID, arg.Context)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormTemplate
	for rows.Next() {
		var i FormTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AuthorPersonID,
			&i.Context,
			&i.Name,
			&i.SubjectType,
			&i.Version,
			&i.IsSeed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesForPerson = `-- name: ListInstancesForPerson :many
SELECT fi.id, fi.template_id, ft.context, ft.name AS template_name,
    fi.context_ref_type, fi.context_ref_id, fi.submitted_by_person_id, fi.submitted_at
FROM form_instances fi
JOIN form_templates ft ON ft.id = fi.template_id
WHERE fi.subject_person_id = $1
  AND ($2::text IS NULL OR ft.context = $2)
ORDER BY fi.submitted_at DESC
LIMIT $4 OFFSET $3
`

type ListInstancesForPersonParams struct {
	SubjectPersonID *uuid.UUID `json:"subject_person_id"`
	Context         *string    `json:"context"`
	Off             int32      `json:"off"`
	Lim             int32      `json:"lim"`
}

type ListInstancesForPersonRow struct {
	ID                  uuid.UUID          `json:"id"`
	TemplateID          uuid.UUID          `json:"template_id"`
	Context             string             `json:"context"`
	TemplateName        string             `json:"template_name"`
	ContextRefType      *string            `json:"context_ref_type"`
	ContextRefID        *uuid.UUID         `json:"context_ref_id"`
	SubmittedByPersonID *uuid.UUID         `json:"submitted_by_person_id"`
	SubmittedAt         pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) ListInstancesForPerson(ctx context.Context, arg ListInstancesForPersonParams) ([]ListInstancesForPersonRow, error) {
	rows, err := q.db.Query(ctx, listInstancesForPerson,
		arg.SubjectPersonID,
		arg.Context,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstancesForPersonRow
	for rows.Next() {
		var i ListInstancesForPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Context,
			&i.TemplateName,
			&i.ContextRefType,
			&i.ContextRefID,
			&i.SubmittedByPersonID,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
