// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGuardianship = `-- name: CreateGuardianship :one
INSERT INTO guardianships (guardian_person_id, child_person_id)
VALUES ($1, $2)
ON CONFLICT (guardian_person_id, child_person_id) DO NOTHING
RETURNING id, guardian_person_id, child_person_id, created_at
`

type CreateGuardianshipParams struct {
	GuardianPersonID uuid.UUID `json:"guardian_person_id"`
	ChildPersonID    uuid.UUID `json:"child_person_id"`
}

func (q *Queries) CreateGuardianship(ctx context.Context, arg CreateGuardianshipParams) (Guardianship, error) {
	row := q.db.QueryRow(ctx, createGuardianship, arg.GuardianPersonID, arg.ChildPersonID)
	var i Guardianship
	err := row.Scan(
		&i.ID,
		&i.GuardianPersonID,
		&i.ChildPersonID,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (person_id, organization_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (person_id, organization_id, role) DO NOTHING
RETURNING id, person_id, organization_id, role, created_at
`

type CreateMembershipParams struct {
	PersonID       uuid.UUID `json:"person_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.PersonID, arg.OrganizationID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.OrganizationID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, kind) VALUES ($1, $2) RETURNING id, name, kind, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Kind)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (display_name, given_name, family_name, birthdate, email, phone,
    emergency_contact_name, emergency_contact_phone, medical_notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, display_name, given_name, family_name, birthdate, email, phone, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreatePersonParams struct {
	DisplayName           string      `json:"display_name"`
	GivenName             *string     `json:"given_name"`
	FamilyName            *string     `json:"family_name"`
	Birthdate             pgtype.Date `json:"birthdate"`
	Email                 *string     `json:"email"`
	Phone                 *string     `json:"phone"`
	EmergencyContactName  *string     `json:"emergency_contact_name"`
	EmergencyContactPhone *string     `json:"emergency_contact_phone"`
	MedicalNotes          *string     `json:"medical_notes"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.DisplayName,
		arg.GivenName,
		arg.FamilyName,
		arg.Birthdate,
		arg.Email,
		arg.Phone,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalNotes,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Birthdate,
		&i.Email,
		&i.Phone,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const createPersonWithID = `-- name: CreatePersonWithID :one
INSERT INTO persons (id, display_name, email)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET display_name = EXCLUDED.display_name, updated_at = now()
RETURNING id, display_name, given_name, family_name, birthdate, email, phone, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreatePersonWithIDParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Email       *string   `json:"email"`
}

// Create (or adopt) a Person with an explicit id — used for the coach's
// deterministic account Person so it matches the app's synced Person.
func (q *Queries) CreatePersonWithID(ctx context.Context, arg CreatePersonWithIDParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPersonWithID, arg.ID, arg.DisplayName, arg.Email)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Birthdate,
		&i.Email,
		&i.Phone,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_account_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token, user_account_id, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	Token         string             `json:"token"`
	UserAccountID uuid.UUID          `json:"user_account_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.Token, arg.UserAccountID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserAccountID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (person_id, email, password_hash, apple_sub)
VALUES ($1, $2, $3, $4)
RETURNING id, person_id, email, password_hash, apple_sub, created_at, updated_at
`

type CreateUserAccountParams struct {
	PersonID     uuid.UUID `json:"person_id"`
	Email        string    `json:"email"`
	PasswordHash *string   `json:"password_hash"`
	AppleSub     *string   `json:"apple_sub"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.PersonID,
		arg.Email,
		arg.PasswordHash,
		arg.AppleSub,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganizationsByIDs = `-- name: DeleteOrganizationsByIDs :exec
DELETE FROM organizations WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteOrganizationsByIDs(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationsByIDs, ids)
	return err
}

const deletePersonByID = `-- name: DeletePersonByID :exec
DELETE FROM persons WHERE id = $1
`

func (q *Queries) DeletePersonByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePersonByID, id)
	return err
}

const deletePersonsByIDs = `-- name: DeletePersonsByIDs :exec
DELETE FROM persons WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeletePersonsByIDs(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePersonsByIDs, ids)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, kind, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, display_name, given_name, family_name, birthdate, email, phone, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at, sync_account_id, payload, deleted, seq FROM persons WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Birthdate,
		&i.Email,
		&i.Phone,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token, user_account_id, expires_at, revoked_at, created_at FROM refresh_tokens WHERE token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserAccountID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAccountByAppleSub = `-- name: GetUserAccountByAppleSub :one
SELECT id, person_id, email, password_hash, apple_sub, created_at, updated_at FROM user_accounts WHERE apple_sub = $1
`

func (q *Queries) GetUserAccountByAppleSub(ctx context.Context, appleSub *string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByAppleSub, appleSub)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByEmail = `-- name: GetUserAccountByEmail :one
SELECT id, person_id, email, password_hash, apple_sub, created_at, updated_at FROM user_accounts WHERE email = $1
`

func (q *Queries) GetUserAccountByEmail(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByEmail, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByID = `-- name: GetUserAccountByID :one
SELECT id, person_id, email, password_hash, apple_sub, created_at, updated_at FROM user_accounts WHERE id = $1
`

func (q *Queries) GetUserAccountByID(ctx context.Context, id uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasMembership = `-- name: HasMembership :one
SELECT EXISTS (
    SELECT 1 FROM memberships WHERE person_id = $1 AND organization_id = $2
)
`

type HasMembershipParams struct {
	PersonID       uuid.UUID `json:"person_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) HasMembership(ctx context.Context, arg HasMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMembership, arg.PersonID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkAppleSub = `-- name: LinkAppleSub :exec
UPDATE user_accounts SET apple_sub = $2, updated_at = now() WHERE id = $1
`

type LinkAppleSubParams struct {
	ID       uuid.UUID `json:"id"`
	AppleSub *string   `json:"apple_sub"`
}

func (q *Queries) LinkAppleSub(ctx context.Context, arg LinkAppleSubParams) error {
	_, err := q.db.Exec(ctx, linkAppleSub, arg.ID, arg.AppleSub)
	return err
}

const listChildren = `-- name: ListChildren :many
SELECT p.id, p.display_name, p.given_name, p.family_name, p.birthdate, p.email, p.phone, p.emergency_contact_name, p.emergency_contact_phone, p.medical_notes, p.created_at, p.updated_at, p.sync_account_id, p.payload, p.deleted, p.seq FROM guardianships g
JOIN persons p ON p.id = g.child_person_id
WHERE g.guardian_person_id = $1
ORDER BY p.display_name ASC
`

func (q *Queries) ListChildren(ctx context.Context, guardianPersonID uuid.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listChildren, guardianPersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GivenName,
			&i.FamilyName,
			&i.Birthdate,
			&i.Email,
			&i.Phone,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForPerson = `-- name: ListMembershipsForPerson :many
SELECT m.id, m.role, m.organization_id, o.name AS organization_name, o.kind AS organization_kind
FROM memberships m
JOIN organizations o ON o.id = m.organization_id
WHERE m.person_id = $1
ORDER BY o.created_at ASC
`

type ListMembershipsForPersonRow struct {
	ID               uuid.UUID `json:"id"`
	Role             string    `json:"role"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrganizationName string    `json:"organization_name"`
	OrganizationKind string    `json:"organization_kind"`
}

func (q *Queries) ListMembershipsForPerson(ctx context.Context, personID uuid.UUID) ([]ListMembershipsForPersonRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForPersonRow
	for rows.Next() {
		var i ListMembershipsForPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalOrgIDsForPerson = `-- name: ListPersonalOrgIDsForPerson :many
SELECT DISTINCT o.id
FROM memberships m
JOIN organizations o ON o.id = m.organization_id
WHERE m.person_id = $1 AND o.kind = 'personal'
`

// The personal org(s) this person owns. A personal org is created with its owner
// as sole member (see handleRegister), so "member of a personal org" == "owns
// it". Club orgs the caller merely belongs to are intentionally excluded: account
// deletion removes the caller from the club (via their membership), not the club.
func (q *Queries) ListPersonalOrgIDsForPerson(ctx context.Context, personID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPersonalOrgIDsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesInOrg = `-- name: ListRolesInOrg :many
SELECT role FROM memberships WHERE person_id = $1 AND organization_id = $2
`

type ListRolesInOrgParams struct {
	PersonID       uuid.UUID `json:"person_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListRolesInOrg(ctx context.Context, arg ListRolesInOrgParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolesInOrg, arg.PersonID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenByToken = `-- name: RevokeRefreshTokenByToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE token = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByToken, token)
	return err
}

const selectOrphanedAthletePersonIDs = `-- name: SelectOrphanedAthletePersonIDs :many
WITH linked_in AS (
    SELECT m.person_id FROM memberships m
    WHERE m.organization_id = ANY($2::uuid[])
    UNION
    SELECT rm.person_id FROM roster_memberships rm
    JOIN teams t ON t.id = rm.team_id
    WHERE t.organization_id = ANY($2::uuid[])
),
linked_out AS (
    SELECT m.person_id FROM memberships m
    WHERE m.organization_id <> ALL($2::uuid[])
    UNION
    SELECT rm.person_id FROM roster_memberships rm
    JOIN teams t ON t.id = rm.team_id
    WHERE t.organization_id <> ALL($2::uuid[])
)
SELECT p.id
FROM persons p
WHERE p.id IN (SELECT person_id FROM linked_in)
  AND p.id NOT IN (SELECT person_id FROM linked_out)
  AND p.id <> $1
  AND (p.sync_account_id IS NULL OR p.sync_account_id = $1)
`

type SelectOrphanedAthletePersonIDsParams struct {
	CallerPersonID uuid.UUID   `json:"caller_person_id"`
	OrgIds         []uuid.UUID `json:"org_ids"`
}

// Athletes (Persons) whose ONLY organizational linkage is via the org(s) being
// deleted. Deleting those orgs strips their membership/roster rows but leaves the
// Person itself — name, birthdate, medical notes: minors' PII we are legally
// required to erase (COPPA/GDPR). ON DELETE CASCADE never reaches these, so we
// delete them explicitly. A person still linked to any org OUTSIDE the delete-set
// survives (the shared-athlete / multi-org case). Excludes the caller's own
// Person (deleted separately) and anyone synced by a different account.
func (q *Queries) SelectOrphanedAthletePersonIDs(ctx context.Context, arg SelectOrphanedAthletePersonIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, selectOrphanedAthletePersonIDs, arg.CallerPersonID, arg.OrgIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET display_name            = COALESCE($1, display_name),
    given_name              = CASE WHEN $2::bool THEN $3 ELSE given_name END,
    family_name             = CASE WHEN $4::bool THEN $5 ELSE family_name END,
    birthdate               = CASE WHEN $6::bool THEN $7 ELSE birthdate END,
    email                   = CASE WHEN $8::bool THEN $9 ELSE email END,
    phone                   = CASE WHEN $10::bool THEN $11 ELSE phone END,
    emergency_contact_name  = CASE WHEN $12::bool THEN $13 ELSE emergency_contact_name END,
    emergency_contact_phone = CASE WHEN $14::bool THEN $15 ELSE emergency_contact_phone END,
    medical_notes           = CASE WHEN $16::bool THEN $17 ELSE medical_notes END,
    updated_at              = now()
WHERE id = $18
RETURNING id, display_name, given_name, family_name, birthdate, email, phone, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type UpdatePersonParams struct {
	DisplayName   *string     `json:"display_name"`
	SetGivenName  bool        `json:"set_given_name"`
	GivenName     *string     `json:"given_name"`
	SetFamilyName bool        `json:"set_family_name"`
	FamilyName    *string     `json:"family_name"`
	SetBirthdate  bool        `json:"set_birthdate"`
	Birthdate     pgtype.Date `json:"birthdate"`
	SetEmail      bool        `json:"set_email"`
	Email         *string     `json:"email"`
	SetPhone      bool        `json:"set_phone"`
	Phone         *string     `json:"phone"`
	SetEcName     bool        `json:"set_ec_name"`
	EcName        *string     `json:"ec_name"`
	SetEcPhone    bool        `json:"set_ec_phone"`
	EcPhone       *string     `json:"ec_phone"`
	SetMedical    bool        `json:"set_medical"`
	Medical       *string     `json:"medical"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.DisplayName,
		arg.SetGivenName,
		arg.GivenName,
		arg.SetFamilyName,
		arg.FamilyName,
		arg.SetBirthdate,
		arg.Birthdate,
		arg.SetEmail,
		arg.Email,
		arg.SetPhone,
		arg.Phone,
		arg.SetEcName,
		arg.EcName,
		arg.SetEcPhone,
		arg.EcPhone,
		arg.SetMedical,
		arg.Medical,
		arg.ID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Birthdate,
		&i.Email,
		&i.Phone,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}
