// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOtherAdminsInOrg = `-- name: CountOtherAdminsInOrg :one
SELECT count(*) FROM memberships
WHERE organization_id = $1 AND role = 'admin' AND person_id <> $2
`

type CountOtherAdminsInOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	PersonID       uuid.UUID `json:"person_id"`
}

// How many admins an organization would still have without this person. The guard against
// the one mistake that cannot be undone through the API: an org whose last admin demotes
// or removes themselves has nobody left who can manage members, and no endpoint that can
// put one back.
func (q *Queries) CountOtherAdminsInOrg(ctx context.Context, arg CountOtherAdminsInOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherAdminsInOrg, arg.OrganizationID, arg.PersonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuardianship = `-- name: CreateGuardianship :one
INSERT INTO guardianships (guardian_person_id, child_person_id)
VALUES ($1, $2)
ON CONFLICT (guardian_person_id, child_person_id) DO NOTHING
RETURNING id, guardian_person_id, child_person_id, created_at
`

type CreateGuardianshipParams struct {
	GuardianPersonID uuid.UUID `json:"guardian_person_id"`
	ChildPersonID    uuid.UUID `json:"child_person_id"`
}

func (q *Queries) CreateGuardianship(ctx context.Context, arg CreateGuardianshipParams) (Guardianship, error) {
	row := q.db.QueryRow(ctx, createGuardianship, arg.GuardianPersonID, arg.ChildPersonID)
	var i Guardianship
	err := row.Scan(
		&i.ID,
		&i.GuardianPersonID,
		&i.ChildPersonID,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (organization_id, email, roles, invited_by_person_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, email, roles, invited_by_person_id, status, expires_at, created_at, responded_at
`

type CreateInvitationParams struct {
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	Roles             []string           `json:"roles"`
	InvitedByPersonID *uuid.UUID         `json:"invited_by_person_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Roles,
		arg.InvitedByPersonID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Roles,
		&i.InvitedByPersonID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (person_id, organization_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (person_id, organization_id, role) DO NOTHING
RETURNING id, person_id, organization_id, role, created_at
`

type CreateMembershipParams struct {
	PersonID       uuid.UUID `json:"person_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.PersonID, arg.OrganizationID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.OrganizationID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, kind, owner_person_id) VALUES ($1, $2, $3) RETURNING id, name, kind, created_at, updated_at, owner_person_id
`

type CreateOrganizationParams struct {
	Name          string     `json:"name"`
	Kind          string     `json:"kind"`
	OwnerPersonID *uuid.UUID `json:"owner_person_id"`
}

// owner_person_id is not optional in practice: it is what account deletion selects on,
// and an org created without one can never be deleted by the person who made it.
func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Kind, arg.OwnerPersonID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerPersonID,
	)
	return i, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (display_name, given_name, family_name, birthdate, email, phone,
    emergency_contact_name, emergency_contact_phone, medical_notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, display_name, given_name, family_name, birthdate, email, phone, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreatePersonParams struct {
	DisplayName           string      `json:"display_name"`
	GivenName             *string     `json:"given_name"`
	FamilyName            *string     `json:"family_name"`
	Birthdate             pgtype.Date `json:"birthdate"`
	Email                 *string     `json:"email"`
	Phone                 *string     `json:"phone"`
	EmergencyContactName  *string     `json:"emergency_contact_name"`
	EmergencyContactPhone *string     `json:"emergency_contact_phone"`
	MedicalNotes          *string     `json:"medical_notes"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.DisplayName,
		arg.GivenName,
		arg.FamilyName,
		arg.Birthdate,
		arg.Email,
		arg.Phone,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalNotes,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Birthdate,
		&i.Email,
		&i.Phone,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const createPersonWithID = `-- name: CreatePersonWithID :one
INSERT INTO persons (id, display_name, email)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
RETURNING id, display_name, given_name, family_name, birthdate, email, phone, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreatePersonWithIDParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Email       *string   `json:"email"`
}

// Create a Person at an explicit id — the coach's deterministic account Person, so it
// matches the id the app derives locally.
//
// DO NOTHING, not DO UPDATE. This used to adopt whatever row was already at that id,
// and the id is UUIDv5(a namespace constant published in this repo, apple_sub), so it is
// computable by anyone who knows the subject. POST /sync lets any authenticated account
// insert a persons row at an id of its choosing — SyncUpsertPerson's ownership guard
// governs conflicts, and there is no conflict when the row does not exist yet — so an
// attacker could pre-create the row and have the victim's first Apple sign-in adopt it,
// sync_account_id and all. From then on the victim's own account Person was the
// attacker's to rewrite, tombstone and pull.
//
// Returning zero rows means the id is taken by a row we did not create. There is no
// legitimate way for that to happen: authenticating as this coach requires /auth/apple,
// so their own sync push cannot precede their own provisioning, and provisioning is one
// transaction that commits whole or not at all. The caller treats it as a refusal.
func (q *Queries) CreatePersonWithID(ctx context.Context, arg CreatePersonWithIDParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPersonWithID, arg.ID, arg.DisplayName, arg.Email)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Birthdate,
		&i.Email,
		&i.Phone,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token_hash, user_account_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token_hash, user_account_id, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	TokenHash     string             `json:"token_hash"`
	UserAccountID uuid.UUID          `json:"user_account_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.TokenHash, arg.UserAccountID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserAccountID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (person_id, email, apple_sub)
VALUES ($1, $2, $3)
RETURNING id, person_id, email, apple_sub, created_at, updated_at
`

type CreateUserAccountParams struct {
	PersonID uuid.UUID `json:"person_id"`
	Email    string    `json:"email"`
	AppleSub *string   `json:"apple_sub"`
}

// Sign in with Apple is the only path that creates an account, so an account is born
// with its Apple subject and there is no credential of ours to store alongside it.
func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount, arg.PersonID, arg.Email, arg.AppleSub)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGuardianship = `-- name: DeleteGuardianship :exec
DELETE FROM guardianships
WHERE guardian_person_id = $1 AND child_person_id = $2
`

type DeleteGuardianshipParams struct {
	GuardianPersonID uuid.UUID `json:"guardian_person_id"`
	ChildPersonID    uuid.UUID `json:"child_person_id"`
}

func (q *Queries) DeleteGuardianship(ctx context.Context, arg DeleteGuardianshipParams) error {
	_, err := q.db.Exec(ctx, deleteGuardianship, arg.GuardianPersonID, arg.ChildPersonID)
	return err
}

const deleteMembershipsForPersonInOrg = `-- name: DeleteMembershipsForPersonInOrg :exec
DELETE FROM memberships WHERE person_id = $1 AND organization_id = $2
`

type DeleteMembershipsForPersonInOrgParams struct {
	PersonID       uuid.UUID `json:"person_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Removes a person from an organization outright, every role at once. Roles are rows, so
// "remove this member" is a delete of the set rather than of one of them.
func (q *Queries) DeleteMembershipsForPersonInOrg(ctx context.Context, arg DeleteMembershipsForPersonInOrgParams) error {
	_, err := q.db.Exec(ctx, deleteMembershipsForPersonInOrg, arg.PersonID, arg.OrganizationID)
	return err
}

const deleteOrganizationsByIDs = `-- name: DeleteOrganizationsByIDs :exec
DELETE FROM organizations WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteOrganizationsByIDs(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationsByIDs, ids)
	return err
}

const deletePersonByID = `-- name: DeletePersonByID :exec
DELETE FROM persons WHERE id = $1
`

func (q *Queries) DeletePersonByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePersonByID, id)
	return err
}

const deletePersonsByIDs = `-- name: DeletePersonsByIDs :exec
DELETE FROM persons WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeletePersonsByIDs(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePersonsByIDs, ids)
	return err
}

const deleteRefreshTokenByToken = `-- name: DeleteRefreshTokenByToken :exec
DELETE FROM refresh_tokens WHERE token_hash = $1
`

// Logout removes the row outright rather than revoking it. A revoked row is the signal
// that a token was rotated away, and presenting one again is treated as a replay; a
// logged-out token must not look like that, or signing out on one device would cascade
// every other device off too.
func (q *Queries) DeleteRefreshTokenByToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByToken, tokenHash)
	return err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, organization_id, email, roles, invited_by_person_id, status, expires_at, created_at, responded_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Roles,
		&i.InvitedByPersonID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, kind, created_at, updated_at, owner_person_id FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerPersonID,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, display_name, given_name, family_name, birthdate, email, phone, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at, sync_account_id, payload, deleted, seq FROM persons WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Birthdate,
		&i.Email,
		&i.Phone,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const getPersonIDByAccountEmail = `-- name: GetPersonIDByAccountEmail :one
SELECT ua.person_id FROM user_accounts ua WHERE ua.email = $1
`

// Resolves the address a member is invited by to the Person it belongs to.
//
// Addressing by email rather than by person id is the authorization: a person id is an
// opaque handle that says nothing about whether the caller has any business adding its
// owner, whereas knowing someone's sign-in address is the ordinary evidence that you
// know them. It also keeps this endpoint from becoming a way to sweep person ids and
// pull each one into an org to read it.
//
// user_accounts.email, not persons.email: the former is the verified Apple claim and is
// UNIQUE, the latter is editable contact information and neither.
func (q *Queries) GetPersonIDByAccountEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPersonIDByAccountEmail, email)
	var person_id uuid.UUID
	err := row.Scan(&person_id)
	return person_id, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token_hash, user_account_id, expires_at, revoked_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserAccountID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAccountByAppleSub = `-- name: GetUserAccountByAppleSub :one
SELECT id, person_id, email, apple_sub, created_at, updated_at FROM user_accounts WHERE apple_sub = $1
`

func (q *Queries) GetUserAccountByAppleSub(ctx context.Context, appleSub *string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByAppleSub, appleSub)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByEmail = `-- name: GetUserAccountByEmail :one
SELECT id, person_id, email, apple_sub, created_at, updated_at FROM user_accounts WHERE email = $1
`

func (q *Queries) GetUserAccountByEmail(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByEmail, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByID = `-- name: GetUserAccountByID :one
SELECT id, person_id, email, apple_sub, created_at, updated_at FROM user_accounts WHERE id = $1
`

func (q *Queries) GetUserAccountByID(ctx context.Context, id uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByPersonID = `-- name: GetUserAccountByPersonID :one
SELECT id, person_id, email, apple_sub, created_at, updated_at FROM user_accounts WHERE person_id = $1
`

// The account behind a Person, and so the verified address invitations are matched on.
// A Person with no account has no row here, which is the right answer rather than an
// error: an athlete with no login has nothing to sign in and accept with.
func (q *Queries) GetUserAccountByPersonID(ctx context.Context, personID uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByPersonID, personID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Email,
		&i.AppleSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isGuardianOf = `-- name: IsGuardianOf :one
SELECT EXISTS (
    SELECT 1 FROM guardianships
     WHERE guardian_person_id = $1 AND child_person_id = $2
)
`

type IsGuardianOfParams struct {
	GuardianPersonID uuid.UUID `json:"guardian_person_id"`
	ChildPersonID    uuid.UUID `json:"child_person_id"`
}

// Whether one person is a recorded guardian of another. This is what makes the parent
// role mean something narrower than "member of the org": a parent sees their own
// children and nobody else's.
func (q *Queries) IsGuardianOf(ctx context.Context, arg IsGuardianOfParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGuardianOf, arg.GuardianPersonID, arg.ChildPersonID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listChildren = `-- name: ListChildren :many
SELECT p.id, p.display_name, p.given_name, p.family_name, p.birthdate, p.email, p.phone, p.emergency_contact_name, p.emergency_contact_phone, p.medical_notes, p.created_at, p.updated_at, p.sync_account_id, p.payload, p.deleted, p.seq FROM guardianships g
JOIN persons p ON p.id = g.child_person_id
WHERE g.guardian_person_id = $1 AND p.deleted = false
ORDER BY p.display_name ASC
`

// p.deleted = false for the same reason every other person read has it: a tombstoned
// Person is gone, and since a tombstone now clears its display columns it would list as
// a blank row rather than a name. Nothing calls this yet -- guardianships are not
// exposed -- which is exactly why it is worth fixing before something does.
func (q *Queries) ListChildren(ctx context.Context, guardianPersonID uuid.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listChildren, guardianPersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GivenName,
			&i.FamilyName,
			&i.Birthdate,
			&i.Email,
			&i.Phone,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardiansForChild = `-- name: ListGuardiansForChild :many
SELECT p.id, p.display_name, p.given_name, p.family_name, p.birthdate, p.email, p.phone, p.emergency_contact_name, p.emergency_contact_phone, p.medical_notes, p.created_at, p.updated_at, p.sync_account_id, p.payload, p.deleted, p.seq FROM guardianships g
JOIN persons p ON p.id = g.guardian_person_id
WHERE g.child_person_id = $1 AND p.deleted = false
ORDER BY p.display_name ASC
`

func (q *Queries) ListGuardiansForChild(ctx context.Context, childPersonID uuid.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listGuardiansForChild, childPersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GivenName,
			&i.FamilyName,
			&i.Birthdate,
			&i.Email,
			&i.Phone,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForPerson = `-- name: ListMembershipsForPerson :many
SELECT m.id, m.role, m.organization_id, o.name AS organization_name, o.kind AS organization_kind
FROM memberships m
JOIN organizations o ON o.id = m.organization_id
WHERE m.person_id = $1
ORDER BY o.created_at ASC, o.id ASC
`

type ListMembershipsForPersonRow struct {
	ID               uuid.UUID `json:"id"`
	Role             string    `json:"role"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrganizationName string    `json:"organization_name"`
	OrganizationKind string    `json:"organization_kind"`
}

// Tie-broken on id: orgs created inside one transaction share a now() timestamp, and
// resolveOrg takes the first row as the caller's default org when no X-Organization-ID
// is sent. Without the tie-break that default is whatever Postgres happens to return.
func (q *Queries) ListMembershipsForPerson(ctx context.Context, personID uuid.UUID) ([]ListMembershipsForPersonRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForPersonRow
	for rows.Next() {
		var i ListMembershipsForPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT p.id AS person_id, p.display_name, p.email,
       array_agg(m.role ORDER BY m.role)::text[] AS roles,
       bool_or(o.owner_person_id = p.id) AS is_owner
FROM memberships m
JOIN persons p ON p.id = m.person_id
JOIN organizations o ON o.id = m.organization_id
WHERE m.organization_id = $1 AND p.deleted = false
GROUP BY p.id, p.display_name, p.email
ORDER BY p.display_name ASC, p.id ASC
`

type ListOrganizationMembersRow struct {
	PersonID    uuid.UUID `json:"person_id"`
	DisplayName string    `json:"display_name"`
	Email       *string   `json:"email"`
	Roles       []string  `json:"roles"`
	IsOwner     bool      `json:"is_owner"`
}

// Everyone in an organization, one row per person with their roles gathered into an
// array. Roles are rows -- UNIQUE (person_id, organization_id, role) -- so a person
// holding both coach and parent is two memberships, and listing them unaggregated would
// show that person twice with no way to tell it was one human.
//
// Deliberately not a person read: display_name and email are what a member list needs,
// and birthdate, phone and medical notes are not. Someone who may manage members is not
// thereby entitled to every athlete's medical history.
func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationMembersRow
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.PersonID,
			&i.DisplayName,
			&i.Email,
			&i.Roles,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedPersonalOrgIDsForPerson = `-- name: ListOwnedPersonalOrgIDsForPerson :many
SELECT o.id
FROM organizations o
WHERE o.owner_person_id = $1 AND o.kind = 'personal'
`

// The personal org(s) this person owns, selected on organizations.owner_person_id.
//
// This used to select on membership and argue that the two were the same thing —
// "a personal org is created with its owner as sole member, so member == owner". That
// held only because nothing could add a second member to an org. Once something can, a
// plain member deleting their own account deletes the org out from under its owner. The
// name said "ForPerson" and meant "belonging to"; it now means "owned by", which is why
// it is renamed rather than quietly reworded.
//
// Club orgs stay excluded even when the caller owns one: whether deleting a club
// owner's account should destroy the club is a product decision that has not been made,
// and the conservative answer — orphan it, leave the data — matches today's behaviour.
func (q *Queries) ListOwnedPersonalOrgIDsForPerson(ctx context.Context, ownerPersonID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOwnedPersonalOrgIDsForPerson, ownerPersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForEmail = `-- name: ListPendingInvitationsForEmail :many
SELECT i.id, i.organization_id, i.email, i.roles, i.invited_by_person_id, i.status, i.expires_at, i.created_at, i.responded_at, o.name AS organization_name, o.kind AS organization_kind
FROM invitations i
JOIN organizations o ON o.id = i.organization_id
WHERE i.email = $1 AND i.status = 'pending' AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type ListPendingInvitationsForEmailRow struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	Roles             []string           `json:"roles"`
	InvitedByPersonID *uuid.UUID         `json:"invited_by_person_id"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RespondedAt       pgtype.Timestamptz `json:"responded_at"`
	OrganizationName  string             `json:"organization_name"`
	OrganizationKind  string             `json:"organization_kind"`
}

// The invitee's side. Keyed on the address alone, because the caller proved they own it
// by signing in with it -- see 0011_invitations.sql for why there is no token.
func (q *Queries) ListPendingInvitationsForEmail(ctx context.Context, email string) ([]ListPendingInvitationsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitationsForEmailRow
	for rows.Next() {
		var i ListPendingInvitationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Roles,
			&i.InvitedByPersonID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.OrganizationName,
			&i.OrganizationKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForOrg = `-- name: ListPendingInvitationsForOrg :many
SELECT i.id, i.organization_id, i.email, i.roles, i.invited_by_person_id, i.status, i.expires_at, i.created_at, i.responded_at, p.display_name AS invited_by_name
FROM invitations i
LEFT JOIN persons p ON p.id = i.invited_by_person_id
WHERE i.organization_id = $1 AND i.status = 'pending' AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type ListPendingInvitationsForOrgRow struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	Roles             []string           `json:"roles"`
	InvitedByPersonID *uuid.UUID         `json:"invited_by_person_id"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RespondedAt       pgtype.Timestamptz `json:"responded_at"`
	InvitedByName     *string            `json:"invited_by_name"`
}

// What the club has outstanding. Expired rows are filtered rather than deleted: an
// invitation nobody answered is a fact about what was offered, and the partial unique
// index only guards pending ones, so a stale row never blocks a fresh send.
func (q *Queries) ListPendingInvitationsForOrg(ctx context.Context, organizationID uuid.UUID) ([]ListPendingInvitationsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsForOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitationsForOrgRow
	for rows.Next() {
		var i ListPendingInvitationsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Roles,
			&i.InvitedByPersonID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.InvitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForPersonInOrg = `-- name: ListRolesForPersonInOrg :many
SELECT role FROM memberships
WHERE person_id = $1 AND organization_id = $2
ORDER BY role
`

type ListRolesForPersonInOrgParams struct {
	PersonID       uuid.UUID `json:"person_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// One person's roles in one organization. Used before a role change, so the handler can
// say what it is replacing and refuse to strip the last admin.
func (q *Queries) ListRolesForPersonInOrg(ctx context.Context, arg ListRolesForPersonInOrgParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolesForPersonInOrg, arg.PersonID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const personHasUserAccount = `-- name: PersonHasUserAccount :one
SELECT EXISTS (
    SELECT 1 FROM user_accounts WHERE person_id = $1
)
`

// Whether this Person can sign in. PATCH /persons/{id} uses it to keep a coach's edit
// rights to the loginless athletes they manage, the same population POST /persons can
// create -- someone with an account edits their own row.
func (q *Queries) PersonHasUserAccount(ctx context.Context, personID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, personHasUserAccount, personID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const personOwnedBySyncAccount = `-- name: PersonOwnedBySyncAccount :one
SELECT EXISTS (
    SELECT 1 FROM persons p
     WHERE p.id = $1
       AND p.deleted = false
       AND p.sync_account_id = $2
)
`

type PersonOwnedBySyncAccountParams struct {
	PersonID       uuid.UUID  `json:"person_id"`
	ViewerPersonID *uuid.UUID `json:"viewer_person_id"`
}

// Whether this Person is a row the caller pushed through sync themselves.
//
// Separate from the org arms and available to every role, because it is not a claim
// about the organization: sync streams are per-account, so this matches only rows the
// caller wrote and already holds on their own device. An athlete the app creates arrives
// carrying no membership and no roster row, so without this the person endpoints answer
// 404 for the athletes a coach actually has.
func (q *Queries) PersonOwnedBySyncAccount(ctx context.Context, arg PersonOwnedBySyncAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, personOwnedBySyncAccount, arg.PersonID, arg.ViewerPersonID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const personVisibleInOrg = `-- name: PersonVisibleInOrg :one
SELECT EXISTS (
    SELECT 1 FROM persons p
     WHERE p.id = $1
       AND p.deleted = false
       AND (EXISTS (SELECT 1 FROM memberships m
                     WHERE m.person_id = p.id
                       AND m.organization_id = $2)
         OR EXISTS (SELECT 1 FROM roster_memberships rm
                      JOIN teams t ON t.id = rm.team_id
                     WHERE rm.person_id = p.id
                       AND t.organization_id = $2
                       AND t.deleted = false))
)
`

type PersonVisibleInOrgParams struct {
	PersonID       uuid.UUID `json:"person_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Whether the caller may see a Person at all: they are not tombstoned, and one of three
// things is true -- they hold a membership in the caller's org, they are rostered on one
// of its live teams, or the caller pushed them through sync themselves. The roster arm
// matters because an athlete can be added to a team without a membership row of their
// own.
//
// This is the *organization* arm only. Sync ownership used to be a third disjunct here;
// it is PersonOwnedBySyncAccount now, because the two answer different questions and the
// role rules ask them of different callers. Staff get this one -- they run the club, so
// they see everyone in it. A parent does not, and would have been handed the whole club
// by the membership arm.
func (q *Queries) PersonVisibleInOrg(ctx context.Context, arg PersonVisibleInOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, personVisibleInOrg, arg.PersonID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reapExpiredRefreshTokens = `-- name: ReapExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at < now() - $1::interval
`

// Delete refresh tokens that expired long enough ago to be of no further use.
//
// Nothing ever deleted. RevokeRefreshToken and RevokeRefreshTokensForAccount stamp
// revoked_at; logout removes its own row; everything else accumulated, one row per
// sign-in and one per refresh, forever. Since password authentication was removed a
// refresh token is the only credential this service stores, so the table is both the
// fastest-growing thing here and the most sensitive. See docs/AUDIT-2.md L4.
//
// The predicate is expires_at, not revoked_at, and that is the whole subtlety. A revoked
// row is what replay detection reads: presenting an already-rotated token is evidence
// the chain leaked, and the response is to revoke the family. Delete revoked rows
// eagerly and a replay stops looking like a replay -- it looks like an unknown token,
// answered with a plain 401, and the theft goes unremarked. Keying on expiry keeps every
// revoked row for as long as the token it describes could still be presented, plus the
// grace the caller passes.
func (q *Queries) ReapExpiredRefreshTokens(ctx context.Context, grace pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredRefreshTokens, grace)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const respondToInvitation = `-- name: RespondToInvitation :execrows
UPDATE invitations
SET status = $1, responded_at = now()
WHERE id = $2 AND status = 'pending' AND expires_at > now()
`

type RespondToInvitationParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

// Answers an invitation, and is the whole concurrency story. The status test is inside
// the UPDATE, so two accepts of the same invitation cannot both see 'pending' and both
// grant the roles -- the second matches no row and is told it was already answered.
// Expiry is checked here too, so a row that aged out between the read and the write
// cannot slip through.
func (q *Queries) RespondToInvitation(ctx context.Context, arg RespondToInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, respondToInvitation, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE invitations
SET status = 'revoked', responded_at = now()
WHERE id = $1 AND organization_id = $2 AND status = 'pending'
`

type RevokeInvitationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

// Rotation's single-use guard, not a follow-up to one. handleRefresh used to read the
// row, decide it was live, and then revoke it unconditionally — a check-then-act with
// nothing between the two statements, so concurrent presentations of one token all read
// it before any of them wrote and every one of them minted a fresh family (measured: 6
// live chains from 32 simultaneous redemptions of a single token). That is the exact
// invariant reuse detection rests on: one token, one use, and a second use is evidence.
//
// The predicate makes the write itself the arbiter. Zero rows means somebody else
// redeemed this token between our read and our write, which the caller treats the same
// way it treats a replay inside the grace window — microseconds apart is the retry case,
// not the theft case.
func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokensForAccount = `-- name: RevokeRefreshTokensForAccount :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_account_id = $1 AND revoked_at IS NULL
`

// Revoke every live token for one account. Used when a already-rotated token is
// presented again: that is a replay, and the only safe reading is that the chain has
// leaked, so the whole family goes rather than just the one token.
func (q *Queries) RevokeRefreshTokensForAccount(ctx context.Context, userAccountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensForAccount, userAccountID)
	return err
}

const selectOrphanedAthletePersonIDs = `-- name: SelectOrphanedAthletePersonIDs :many
WITH linked_in AS (
    SELECT m.person_id FROM memberships m
    WHERE m.organization_id = ANY($2::uuid[])
    UNION
    SELECT rm.person_id FROM roster_memberships rm
    JOIN teams t ON t.id = rm.team_id
    WHERE t.organization_id = ANY($2::uuid[])
),
linked_out AS (
    SELECT m.person_id FROM memberships m
    WHERE m.organization_id <> ALL($2::uuid[])
    UNION
    SELECT rm.person_id FROM roster_memberships rm
    JOIN teams t ON t.id = rm.team_id
    WHERE t.organization_id <> ALL($2::uuid[])
)
SELECT p.id
FROM persons p
WHERE p.id IN (SELECT person_id FROM linked_in)
  AND p.id NOT IN (SELECT person_id FROM linked_out)
  AND p.id <> $1
  AND (p.sync_account_id IS NULL OR p.sync_account_id = $1)
`

type SelectOrphanedAthletePersonIDsParams struct {
	CallerPersonID uuid.UUID   `json:"caller_person_id"`
	OrgIds         []uuid.UUID `json:"org_ids"`
}

// Athletes (Persons) whose ONLY organizational linkage is via the org(s) being
// deleted. Deleting those orgs strips their membership/roster rows but leaves the
// Person itself — name, birthdate, medical notes: minors' PII we are legally
// required to erase (COPPA/GDPR). ON DELETE CASCADE never reaches these, so we
// delete them explicitly. A person still linked to any org OUTSIDE the delete-set
// survives (the shared-athlete / multi-org case). Excludes the caller's own
// Person (deleted separately) and anyone synced by a different account.
func (q *Queries) SelectOrphanedAthletePersonIDs(ctx context.Context, arg SelectOrphanedAthletePersonIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, selectOrphanedAthletePersonIDs, arg.CallerPersonID, arg.OrgIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = COALESCE($1, name),
    updated_at = now()
WHERE id = $2
RETURNING id, name, kind, created_at, updated_at, owner_person_id
`

type UpdateOrganizationParams struct {
	Name *string   `json:"name"`
	ID   uuid.UUID `json:"id"`
}

// Only the name. `kind` is deliberately not editable here: handleDeleteMe deletes the
// caller's *personal* orgs and orphans their clubs, so flipping kind would quietly
// change what account deletion destroys. That is a product decision with a data-loss
// edge, not a field on a PATCH body.
func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.Name, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerPersonID,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET display_name            = COALESCE($1, display_name),
    given_name              = CASE WHEN $2::bool THEN $3 ELSE given_name END,
    family_name             = CASE WHEN $4::bool THEN $5 ELSE family_name END,
    birthdate               = CASE WHEN $6::bool THEN $7 ELSE birthdate END,
    email                   = CASE WHEN $8::bool THEN $9 ELSE email END,
    phone                   = CASE WHEN $10::bool THEN $11 ELSE phone END,
    emergency_contact_name  = CASE WHEN $12::bool THEN $13 ELSE emergency_contact_name END,
    emergency_contact_phone = CASE WHEN $14::bool THEN $15 ELSE emergency_contact_phone END,
    medical_notes           = CASE WHEN $16::bool THEN $17 ELSE medical_notes END,
    payload                 = CASE WHEN $18::bool
                                   THEN COALESCE(payload, '{}'::jsonb) || $19::jsonb
                                   ELSE payload END,
    seq                     = nextval('sync_seq'),
    updated_at              = now()
WHERE id = $20
RETURNING id, display_name, given_name, family_name, birthdate, email, phone, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type UpdatePersonParams struct {
	DisplayName   *string     `json:"display_name"`
	SetGivenName  bool        `json:"set_given_name"`
	GivenName     *string     `json:"given_name"`
	SetFamilyName bool        `json:"set_family_name"`
	FamilyName    *string     `json:"family_name"`
	SetBirthdate  bool        `json:"set_birthdate"`
	Birthdate     pgtype.Date `json:"birthdate"`
	SetEmail      bool        `json:"set_email"`
	Email         *string     `json:"email"`
	SetPhone      bool        `json:"set_phone"`
	Phone         *string     `json:"phone"`
	SetEcName     bool        `json:"set_ec_name"`
	EcName        *string     `json:"ec_name"`
	SetEcPhone    bool        `json:"set_ec_phone"`
	EcPhone       *string     `json:"ec_phone"`
	SetMedical    bool        `json:"set_medical"`
	Medical       *string     `json:"medical"`
	PatchPayload  bool        `json:"patch_payload"`
	PayloadPatch  []byte      `json:"payload_patch"`
	ID            uuid.UUID   `json:"id"`
}

// Writes the record twice, for the reason UpdateTeam spells out: a pull returns
// `payload`, so a column-only edit never reaches the phone and is overwritten by its
// next push.
//
// Only four of these columns are in the sync contract -- display_name, the two emergency
// contact fields and medical_notes are what SyncUpsertPerson projects, so they are what
// payload_patch may carry. given_name, family_name, birthdate, email and phone are REST's
// alone: no push writes them and SyncTombstonePerson deliberately spares them, so they
// need no propagation and must not be invented into a payload the app would not
// recognise.
func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.DisplayName,
		arg.SetGivenName,
		arg.GivenName,
		arg.SetFamilyName,
		arg.FamilyName,
		arg.SetBirthdate,
		arg.Birthdate,
		arg.SetEmail,
		arg.Email,
		arg.SetPhone,
		arg.Phone,
		arg.SetEcName,
		arg.EcName,
		arg.SetEcPhone,
		arg.EcPhone,
		arg.SetMedical,
		arg.Medical,
		arg.PatchPayload,
		arg.PayloadPatch,
		arg.ID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Birthdate,
		&i.Email,
		&i.Phone,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}
