// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE invitations
SET accepted_at = now(), accepted_by_person_id = $2
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

type AcceptInvitationParams struct {
	ID                 uuid.UUID  `json:"id"`
	AcceptedByPersonID *uuid.UUID `json:"accepted_by_person_id"`
}

// The write is the arbiter of whether this invitation was still redeemable.
//
// Reading the row, deciding it is live, and then updating it is a check-then-act with
// nothing between the two statements: two devices opening the same link — the ordinary
// case, not an attack, since people forward these — would both read "pending" and both
// redeem. Every condition that makes an invitation usable is therefore in the predicate,
// and zero rows affected means somebody (possibly the same person twice) got there first.
func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, arg.ID, arg.AcceptedByPersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addInvitationChild = `-- name: AddInvitationChild :exec
INSERT INTO invitation_children (invitation_id, child_person_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddInvitationChildParams struct {
	InvitationID  uuid.UUID `json:"invitation_id"`
	ChildPersonID uuid.UUID `json:"child_person_id"`
}

func (q *Queries) AddInvitationChild(ctx context.Context, arg AddInvitationChildParams) error {
	_, err := q.db.Exec(ctx, addInvitationChild, arg.InvitationID, arg.ChildPersonID)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (organization_id, token_hash, role, email, note, invited_by_person_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, token_hash, role, email, note, invited_by_person_id, expires_at, accepted_at, accepted_by_person_id, revoked_at, created_at
`

type CreateInvitationParams struct {
	OrganizationID    uuid.UUID          `json:"organization_id"`
	TokenHash         string             `json:"token_hash"`
	Role              string             `json:"role"`
	Email             *string            `json:"email"`
	Note              *string            `json:"note"`
	InvitedByPersonID *uuid.UUID         `json:"invited_by_person_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.TokenHash,
		arg.Role,
		arg.Email,
		arg.Note,
		arg.InvitedByPersonID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.Role,
		&i.Email,
		&i.Note,
		&i.InvitedByPersonID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByPersonID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, organization_id, token_hash, role, email, note, invited_by_person_id, expires_at, accepted_at, accepted_by_person_id, revoked_at, created_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.Role,
		&i.Email,
		&i.Note,
		&i.InvitedByPersonID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByPersonID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, organization_id, token_hash, role, email, note, invited_by_person_id, expires_at, accepted_at, accepted_by_person_id, revoked_at, created_at FROM invitations WHERE token_hash = $1
`

// Redemption looks an invitation up by the hash of the token presented, never by id: the
// token is the only thing that proves the caller was invited to anything.
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.Role,
		&i.Email,
		&i.Note,
		&i.InvitedByPersonID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByPersonID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitationChildRefs = `-- name: ListInvitationChildRefs :many
SELECT ic.invitation_id, p.id AS person_id, p.display_name
FROM invitation_children ic
JOIN persons p ON p.id = ic.child_person_id
WHERE ic.invitation_id = ANY($1::uuid[]) AND p.deleted = false
ORDER BY p.display_name ASC
`

type ListInvitationChildRefsRow struct {
	InvitationID uuid.UUID `json:"invitation_id"`
	PersonID     uuid.UUID `json:"person_id"`
	DisplayName  string    `json:"display_name"`
}

// The children named on one or more invitations, id and name only — enough for "join
// Riverside FC as a parent of Sam Smith", and no more of a minor's record than that
// sentence needs. Takes an array so listing a page of invitations is one query rather
// than one per row.
func (q *Queries) ListInvitationChildRefs(ctx context.Context, invitationIds []uuid.UUID) ([]ListInvitationChildRefsRow, error) {
	rows, err := q.db.Query(ctx, listInvitationChildRefs, invitationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitationChildRefsRow
	for rows.Next() {
		var i ListInvitationChildRefsRow
		if err := rows.Scan(&i.InvitationID, &i.PersonID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationsInOrg = `-- name: ListInvitationsInOrg :many
SELECT id, organization_id, token_hash, role, email, note, invited_by_person_id, expires_at, accepted_at, accepted_by_person_id, revoked_at, created_at FROM invitations
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListInvitationsInOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
}

// Newest first. Accepted and revoked rows are kept and returned: "who did we invite, and
// what came of it" is the question this list answers, and dropping the answer as soon as
// it arrives is how a club invites the same parent four times.
func (q *Queries) ListInvitationsInOrg(ctx context.Context, arg ListInvitationsInOrgParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsInOrg, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TokenHash,
			&i.Role,
			&i.Email,
			&i.Note,
			&i.InvitedByPersonID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedByPersonID,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE invitations
SET revoked_at = now()
WHERE id = $1 AND organization_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Revoking an invitation that was already accepted must not un-accept it, so the
// predicate excludes those rather than the handler reading first and hoping.
func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
