// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leagues.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addLeagueTeam = `-- name: AddLeagueTeam :exec
INSERT INTO league_teams (league_id, team_id) VALUES ($1, $2)
`

type AddLeagueTeamParams struct {
	LeagueID uuid.UUID `json:"league_id"`
	TeamID   uuid.UUID `json:"team_id"`
}

func (q *Queries) AddLeagueTeam(ctx context.Context, arg AddLeagueTeamParams) error {
	_, err := q.db.Exec(ctx, addLeagueTeam, arg.LeagueID, arg.TeamID)
	return err
}

const createFixture = `-- name: CreateFixture :one
INSERT INTO fixtures (league_id, home_team_id, away_team_id, kickoff_at)
VALUES ($1, $2, $3, $4)
RETURNING id, league_id, home_team_id, away_team_id, kickoff_at, home_score, away_score, status, created_at, updated_at
`

type CreateFixtureParams struct {
	LeagueID   uuid.UUID          `json:"league_id"`
	HomeTeamID uuid.UUID          `json:"home_team_id"`
	AwayTeamID uuid.UUID          `json:"away_team_id"`
	KickoffAt  pgtype.Timestamptz `json:"kickoff_at"`
}

func (q *Queries) CreateFixture(ctx context.Context, arg CreateFixtureParams) (Fixture, error) {
	row := q.db.QueryRow(ctx, createFixture,
		arg.LeagueID,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.KickoffAt,
	)
	var i Fixture
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.KickoffAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLeague = `-- name: CreateLeague :one
INSERT INTO leagues (name, season) VALUES ($1, $2) RETURNING id, name, season, created_at
`

type CreateLeagueParams struct {
	Name   string `json:"name"`
	Season string `json:"season"`
}

func (q *Queries) CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error) {
	row := q.db.QueryRow(ctx, createLeague, arg.Name, arg.Season)
	var i League
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Season,
		&i.CreatedAt,
	)
	return i, err
}

const getFixture = `-- name: GetFixture :one
SELECT id, league_id, home_team_id, away_team_id, kickoff_at, home_score, away_score, status, created_at, updated_at FROM fixtures WHERE id = $1
`

func (q *Queries) GetFixture(ctx context.Context, id uuid.UUID) (Fixture, error) {
	row := q.db.QueryRow(ctx, getFixture, id)
	var i Fixture
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.KickoffAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFixtureWithTeams = `-- name: GetFixtureWithTeams :one
SELECT f.id, f.league_id, f.home_team_id, f.away_team_id, f.kickoff_at, f.home_score, f.away_score, f.status, f.created_at, f.updated_at, h.name AS home_team_name, a.name AS away_team_name
FROM fixtures f
JOIN teams h ON h.id = f.home_team_id
JOIN teams a ON a.id = f.away_team_id
WHERE f.id = $1
`

type GetFixtureWithTeamsRow struct {
	ID           uuid.UUID          `json:"id"`
	LeagueID     uuid.UUID          `json:"league_id"`
	HomeTeamID   uuid.UUID          `json:"home_team_id"`
	AwayTeamID   uuid.UUID          `json:"away_team_id"`
	KickoffAt    pgtype.Timestamptz `json:"kickoff_at"`
	HomeScore    *int32             `json:"home_score"`
	AwayScore    *int32             `json:"away_score"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName string             `json:"home_team_name"`
	AwayTeamName string             `json:"away_team_name"`
}

func (q *Queries) GetFixtureWithTeams(ctx context.Context, id uuid.UUID) (GetFixtureWithTeamsRow, error) {
	row := q.db.QueryRow(ctx, getFixtureWithTeams, id)
	var i GetFixtureWithTeamsRow
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.KickoffAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeTeamName,
		&i.AwayTeamName,
	)
	return i, err
}

const getLeague = `-- name: GetLeague :one
SELECT l.id, l.name, l.season, l.created_at,
    (SELECT count(*) FROM league_teams lt WHERE lt.league_id = l.id)::bigint AS team_count
FROM leagues l WHERE l.id = $1
`

type GetLeagueRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Season    string             `json:"season"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TeamCount int64              `json:"team_count"`
}

func (q *Queries) GetLeague(ctx context.Context, id uuid.UUID) (GetLeagueRow, error) {
	row := q.db.QueryRow(ctx, getLeague, id)
	var i GetLeagueRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Season,
		&i.CreatedAt,
		&i.TeamCount,
	)
	return i, err
}

const getLeagueTeam = `-- name: GetLeagueTeam :one
SELECT id, league_id, team_id FROM league_teams WHERE league_id = $1 AND team_id = $2
`

type GetLeagueTeamParams struct {
	LeagueID uuid.UUID `json:"league_id"`
	TeamID   uuid.UUID `json:"team_id"`
}

func (q *Queries) GetLeagueTeam(ctx context.Context, arg GetLeagueTeamParams) (LeagueTeam, error) {
	row := q.db.QueryRow(ctx, getLeagueTeam, arg.LeagueID, arg.TeamID)
	var i LeagueTeam
	err := row.Scan(&i.ID, &i.LeagueID, &i.TeamID)
	return i, err
}

const listCompletedFixtures = `-- name: ListCompletedFixtures :many
SELECT id, league_id, home_team_id, away_team_id, kickoff_at, home_score, away_score, status, created_at, updated_at FROM fixtures
WHERE league_id = $1 AND status = 'COMPLETED'
  AND home_score IS NOT NULL AND away_score IS NOT NULL
`

func (q *Queries) ListCompletedFixtures(ctx context.Context, leagueID uuid.UUID) ([]Fixture, error) {
	rows, err := q.db.Query(ctx, listCompletedFixtures, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fixture
	for rows.Next() {
		var i Fixture
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.KickoffAt,
			&i.HomeScore,
			&i.AwayScore,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFixtures = `-- name: ListFixtures :many
SELECT f.id, f.league_id, f.home_team_id, f.away_team_id, f.kickoff_at, f.home_score, f.away_score, f.status, f.created_at, f.updated_at, h.name AS home_team_name, a.name AS away_team_name
FROM fixtures f
JOIN teams h ON h.id = f.home_team_id
JOIN teams a ON a.id = f.away_team_id
WHERE f.league_id = $1
ORDER BY f.kickoff_at ASC
`

type ListFixturesRow struct {
	ID           uuid.UUID          `json:"id"`
	LeagueID     uuid.UUID          `json:"league_id"`
	HomeTeamID   uuid.UUID          `json:"home_team_id"`
	AwayTeamID   uuid.UUID          `json:"away_team_id"`
	KickoffAt    pgtype.Timestamptz `json:"kickoff_at"`
	HomeScore    *int32             `json:"home_score"`
	AwayScore    *int32             `json:"away_score"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName string             `json:"home_team_name"`
	AwayTeamName string             `json:"away_team_name"`
}

func (q *Queries) ListFixtures(ctx context.Context, leagueID uuid.UUID) ([]ListFixturesRow, error) {
	rows, err := q.db.Query(ctx, listFixtures, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFixturesRow
	for rows.Next() {
		var i ListFixturesRow
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.KickoffAt,
			&i.HomeScore,
			&i.AwayScore,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamName,
			&i.AwayTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeagueTeams = `-- name: ListLeagueTeams :many
SELECT lt.team_id, t.name AS team_name
FROM league_teams lt
JOIN teams t ON t.id = lt.team_id
WHERE lt.league_id = $1
ORDER BY t.name ASC
`

type ListLeagueTeamsRow struct {
	TeamID   uuid.UUID `json:"team_id"`
	TeamName string    `json:"team_name"`
}

func (q *Queries) ListLeagueTeams(ctx context.Context, leagueID uuid.UUID) ([]ListLeagueTeamsRow, error) {
	rows, err := q.db.Query(ctx, listLeagueTeams, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeagueTeamsRow
	for rows.Next() {
		var i ListLeagueTeamsRow
		if err := rows.Scan(&i.TeamID, &i.TeamName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeagues = `-- name: ListLeagues :many
SELECT l.id, l.name, l.season, l.created_at,
    (SELECT count(*) FROM league_teams lt WHERE lt.league_id = l.id)::bigint AS team_count
FROM leagues l
ORDER BY l.created_at DESC
`

type ListLeaguesRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Season    string             `json:"season"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TeamCount int64              `json:"team_count"`
}

func (q *Queries) ListLeagues(ctx context.Context) ([]ListLeaguesRow, error) {
	rows, err := q.db.Query(ctx, listLeagues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeaguesRow
	for rows.Next() {
		var i ListLeaguesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Season,
			&i.CreatedAt,
			&i.TeamCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFixtureResult = `-- name: RecordFixtureResult :one
UPDATE fixtures
SET home_score = $2, away_score = $3, status = 'COMPLETED', updated_at = now()
WHERE id = $1
RETURNING id, league_id, home_team_id, away_team_id, kickoff_at, home_score, away_score, status, created_at, updated_at
`

type RecordFixtureResultParams struct {
	ID        uuid.UUID `json:"id"`
	HomeScore *int32    `json:"home_score"`
	AwayScore *int32    `json:"away_score"`
}

func (q *Queries) RecordFixtureResult(ctx context.Context, arg RecordFixtureResultParams) (Fixture, error) {
	row := q.db.QueryRow(ctx, recordFixtureResult, arg.ID, arg.HomeScore, arg.AwayScore)
	var i Fixture
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.KickoffAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
