// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGoingExcludingUser = `-- name: CountGoingExcludingUser :one
SELECT count(*)::bigint FROM match_rsvps
WHERE match_id = $1 AND status = 'GOING' AND user_id <> $2
`

type CountGoingExcludingUserParams struct {
	MatchID uuid.UUID `json:"match_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CountGoingExcludingUser(ctx context.Context, arg CountGoingExcludingUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGoingExcludingUser, arg.MatchID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMatchGoing = `-- name: CountMatchGoing :one
SELECT count(*)::bigint FROM match_rsvps WHERE match_id = $1 AND status = 'GOING'
`

func (q *Queries) CountMatchGoing(ctx context.Context, matchID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchGoing, matchID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (host_id, venue_id, title, description, format, max_players, kickoff_at, duration_min)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, host_id, venue_id, title, description, format, max_players, kickoff_at, duration_min, status, created_at, updated_at
`

type CreateMatchParams struct {
	HostID      uuid.UUID          `json:"host_id"`
	VenueID     *uuid.UUID         `json:"venue_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Format      string             `json:"format"`
	MaxPlayers  int32              `json:"max_players"`
	KickoffAt   pgtype.Timestamptz `json:"kickoff_at"`
	DurationMin int32              `json:"duration_min"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.HostID,
		arg.VenueID,
		arg.Title,
		arg.Description,
		arg.Format,
		arg.MaxPlayers,
		arg.KickoffAt,
		arg.DurationMin,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.VenueID,
		&i.Title,
		&i.Description,
		&i.Format,
		&i.MaxPlayers,
		&i.KickoffAt,
		&i.DurationMin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatch = `-- name: GetMatch :one
SELECT id, host_id, venue_id, title, description, format, max_players, kickoff_at, duration_min, status, created_at, updated_at FROM matches WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.VenueID,
		&i.Title,
		&i.Description,
		&i.Format,
		&i.MaxPlayers,
		&i.KickoffAt,
		&i.DurationMin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOldestWaitlisted = `-- name: GetOldestWaitlisted :one
SELECT id, match_id, user_id, status, created_at, updated_at FROM match_rsvps
WHERE match_id = $1 AND status = 'WAITLIST'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetOldestWaitlisted(ctx context.Context, matchID uuid.UUID) (MatchRsvp, error) {
	row := q.db.QueryRow(ctx, getOldestWaitlisted, matchID)
	var i MatchRsvp
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRsvp = `-- name: GetRsvp :one
SELECT id, match_id, user_id, status, created_at, updated_at FROM match_rsvps WHERE match_id = $1 AND user_id = $2
`

type GetRsvpParams struct {
	MatchID uuid.UUID `json:"match_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRsvp(ctx context.Context, arg GetRsvpParams) (MatchRsvp, error) {
	row := q.db.QueryRow(ctx, getRsvp, arg.MatchID, arg.UserID)
	var i MatchRsvp
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatchRsvps = `-- name: ListMatchRsvps :many
SELECT r.id, r.status, r.created_at,
    u.id AS user_id, u.email, u.display_name, u.position, u.skill_level, u.bio, u.avatar_url, u.created_at AS user_created_at
FROM match_rsvps r
JOIN users u ON u.id = r.user_id
WHERE r.match_id = $1 AND r.status <> 'DECLINED'
ORDER BY r.created_at ASC
`

type ListMatchRsvpsRow struct {
	ID            uuid.UUID          `json:"id"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UserID        uuid.UUID          `json:"user_id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	Position      *string            `json:"position"`
	SkillLevel    int32              `json:"skill_level"`
	Bio           *string            `json:"bio"`
	AvatarUrl     *string            `json:"avatar_url"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) ListMatchRsvps(ctx context.Context, matchID uuid.UUID) ([]ListMatchRsvpsRow, error) {
	rows, err := q.db.Query(ctx, listMatchRsvps, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchRsvpsRow
	for rows.Next() {
		var i ListMatchRsvpsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Position,
			&i.SkillLevel,
			&i.Bio,
			&i.AvatarUrl,
			&i.UserCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatches = `-- name: ListMatches :many
SELECT m.id, m.host_id, m.venue_id, m.title, m.description, m.format, m.max_players, m.kickoff_at, m.duration_min, m.status, m.created_at, m.updated_at,
    (SELECT count(*) FROM match_rsvps r WHERE r.match_id = m.id AND r.status = 'GOING')::bigint AS going_count
FROM matches m
WHERE ($1::text IS NULL OR m.status = $1)
  AND ($2::uuid IS NULL OR m.venue_id = $2)
  AND ($3::uuid IS NULL OR m.host_id = $3)
  AND (NOT $4::bool OR m.kickoff_at >= now())
ORDER BY m.kickoff_at ASC
LIMIT $6 OFFSET $5
`

type ListMatchesParams struct {
	Status       *string    `json:"status"`
	VenueID      *uuid.UUID `json:"venue_id"`
	HostID       *uuid.UUID `json:"host_id"`
	UpcomingOnly bool       `json:"upcoming_only"`
	Off          int32      `json:"off"`
	Lim          int32      `json:"lim"`
}

type ListMatchesRow struct {
	ID          uuid.UUID          `json:"id"`
	HostID      uuid.UUID          `json:"host_id"`
	VenueID     *uuid.UUID         `json:"venue_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Format      string             `json:"format"`
	MaxPlayers  int32              `json:"max_players"`
	KickoffAt   pgtype.Timestamptz `json:"kickoff_at"`
	DurationMin int32              `json:"duration_min"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	GoingCount  int64              `json:"going_count"`
}

func (q *Queries) ListMatches(ctx context.Context, arg ListMatchesParams) ([]ListMatchesRow, error) {
	rows, err := q.db.Query(ctx, listMatches,
		arg.Status,
		arg.VenueID,
		arg.HostID,
		arg.UpcomingOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesRow
	for rows.Next() {
		var i ListMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.VenueID,
			&i.Title,
			&i.Description,
			&i.Format,
			&i.MaxPlayers,
			&i.KickoffAt,
			&i.DurationMin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GoingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMatchStatus = `-- name: SetMatchStatus :exec
UPDATE matches SET status = $2, updated_at = now() WHERE id = $1
`

type SetMatchStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetMatchStatus(ctx context.Context, arg SetMatchStatusParams) error {
	_, err := q.db.Exec(ctx, setMatchStatus, arg.ID, arg.Status)
	return err
}

const setRsvpStatus = `-- name: SetRsvpStatus :exec
UPDATE match_rsvps SET status = $2, updated_at = now() WHERE id = $1
`

type SetRsvpStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetRsvpStatus(ctx context.Context, arg SetRsvpStatusParams) error {
	_, err := q.db.Exec(ctx, setRsvpStatus, arg.ID, arg.Status)
	return err
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE matches
SET title        = COALESCE($1, title),
    description  = CASE WHEN $2::bool THEN $3 ELSE description END,
    format       = COALESCE($4, format),
    max_players  = COALESCE($5, max_players),
    kickoff_at   = COALESCE($6, kickoff_at),
    duration_min = COALESCE($7, duration_min),
    venue_id     = CASE WHEN $8::bool THEN $9 ELSE venue_id END,
    status       = COALESCE($10, status),
    updated_at   = now()
WHERE id = $11
RETURNING id, host_id, venue_id, title, description, format, max_players, kickoff_at, duration_min, status, created_at, updated_at
`

type UpdateMatchParams struct {
	Title          *string            `json:"title"`
	SetDescription bool               `json:"set_description"`
	Description    *string            `json:"description"`
	Format         *string            `json:"format"`
	MaxPlayers     *int32             `json:"max_players"`
	KickoffAt      pgtype.Timestamptz `json:"kickoff_at"`
	DurationMin    *int32             `json:"duration_min"`
	SetVenueID     bool               `json:"set_venue_id"`
	VenueID        *uuid.UUID         `json:"venue_id"`
	Status         *string            `json:"status"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.Format,
		arg.MaxPlayers,
		arg.KickoffAt,
		arg.DurationMin,
		arg.SetVenueID,
		arg.VenueID,
		arg.Status,
		arg.ID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.VenueID,
		&i.Title,
		&i.Description,
		&i.Format,
		&i.MaxPlayers,
		&i.KickoffAt,
		&i.DurationMin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRsvp = `-- name: UpsertRsvp :one
INSERT INTO match_rsvps (match_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (match_id, user_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = now()
RETURNING id, match_id, user_id, status, created_at, updated_at
`

type UpsertRsvpParams struct {
	MatchID uuid.UUID `json:"match_id"`
	UserID  uuid.UUID `json:"user_id"`
	Status  string    `json:"status"`
}

func (q *Queries) UpsertRsvp(ctx context.Context, arg UpsertRsvpParams) (MatchRsvp, error) {
	row := q.db.QueryRow(ctx, upsertRsvp, arg.MatchID, arg.UserID, arg.Status)
	var i MatchRsvp
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
