// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Fixture struct {
	ID         uuid.UUID          `json:"id"`
	LeagueID   uuid.UUID          `json:"league_id"`
	HomeTeamID uuid.UUID          `json:"home_team_id"`
	AwayTeamID uuid.UUID          `json:"away_team_id"`
	KickoffAt  pgtype.Timestamptz `json:"kickoff_at"`
	HomeScore  *int32             `json:"home_score"`
	AwayScore  *int32             `json:"away_score"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type League struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Season    string             `json:"season"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LeagueTeam struct {
	ID       uuid.UUID `json:"id"`
	LeagueID uuid.UUID `json:"league_id"`
	TeamID   uuid.UUID `json:"team_id"`
}

type Match struct {
	ID          uuid.UUID          `json:"id"`
	HostID      uuid.UUID          `json:"host_id"`
	VenueID     *uuid.UUID         `json:"venue_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Format      string             `json:"format"`
	MaxPlayers  int32              `json:"max_players"`
	KickoffAt   pgtype.Timestamptz `json:"kickoff_at"`
	DurationMin int32              `json:"duration_min"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MatchRsvp struct {
	ID        uuid.UUID          `json:"id"`
	MatchID   uuid.UUID          `json:"match_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlayerMatchStat struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	MatchID       *uuid.UUID         `json:"match_id"`
	FixtureID     *uuid.UUID         `json:"fixture_id"`
	Goals         int32              `json:"goals"`
	Assists       int32              `json:"assists"`
	YellowCards   int32              `json:"yellow_cards"`
	RedCards      int32              `json:"red_cards"`
	MinutesPlayed int32              `json:"minutes_played"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	Token     string             `json:"token"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CrestUrl  *string            `json:"crest_url"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	ID           uuid.UUID          `json:"id"`
	TeamID       uuid.UUID          `json:"team_id"`
	UserID       uuid.UUID          `json:"user_id"`
	Role         string             `json:"role"`
	JerseyNumber *int32             `json:"jersey_number"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	Position     *string            `json:"position"`
	SkillLevel   int32              `json:"skill_level"`
	Bio          *string            `json:"bio"`
	AvatarUrl    *string            `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Venue struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Address   *string            `json:"address"`
	City      *string            `json:"city"`
	Latitude  *float64           `json:"latitude"`
	Longitude *float64           `json:"longitude"`
	Surface   *string            `json:"surface"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
