// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Roster (time-bounded memberships) ----------------------------------------
	AddRosterMembership(ctx context.Context, arg AddRosterMembershipParams) (RosterMembership, error)
	// The moat query: cross-instance aggregation of scored fields for one athlete,
	// optionally scoped to a context. Powers readiness means, effort trends, etc.
	AggregateScoresForPerson(ctx context.Context, arg AggregateScoresForPersonParams) ([]AggregateScoresForPersonRow, error)
	// Drills --------------------------------------------------------------------
	CreateDrill(ctx context.Context, arg CreateDrillParams) (Drill, error)
	CreateFormAnswer(ctx context.Context, arg CreateFormAnswerParams) (FormAnswer, error)
	CreateFormField(ctx context.Context, arg CreateFormFieldParams) (FormField, error)
	// Instances & answers -------------------------------------------------------
	CreateFormInstance(ctx context.Context, arg CreateFormInstanceParams) (FormInstance, error)
	// Templates ----------------------------------------------------------------
	CreateFormTemplate(ctx context.Context, arg CreateFormTemplateParams) (FormTemplate, error)
	// Games (game day) ----------------------------------------------------------
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateGuardianship(ctx context.Context, arg CreateGuardianshipParams) (Guardianship, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	// owner_person_id is not optional in practice: it is what account deletion selects on,
	// and an org created without one can never be deleted by the person who made it.
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	// Create a Person at an explicit id — the coach's deterministic account Person, so it
	// matches the id the app derives locally.
	//
	// DO NOTHING, not DO UPDATE. This used to adopt whatever row was already at that id,
	// and the id is UUIDv5(a namespace constant published in this repo, apple_sub), so it is
	// computable by anyone who knows the subject. POST /sync lets any authenticated account
	// insert a persons row at an id of its choosing — SyncUpsertPerson's ownership guard
	// governs conflicts, and there is no conflict when the row does not exist yet — so an
	// attacker could pre-create the row and have the victim's first Apple sign-in adopt it,
	// sync_account_id and all. From then on the victim's own account Person was the
	// attacker's to rewrite, tombstone and pull.
	//
	// Returning zero rows means the id is taken by a row we did not create. There is no
	// legitimate way for that to happen: authenticating as this coach requires /auth/apple,
	// so their own sync push cannot precede their own provisioning, and provisioning is one
	// transaction that commits whole or not at all. The caller treats it as a refusal.
	CreatePersonWithID(ctx context.Context, arg CreatePersonWithIDParams) (Person, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// Sessions ------------------------------------------------------------------
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionBlock(ctx context.Context, arg CreateSessionBlockParams) (SessionBlock, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error)
	DeleteOrganizationsByIDs(ctx context.Context, ids []uuid.UUID) error
	DeletePersonByID(ctx context.Context, id uuid.UUID) error
	DeletePersonsByIDs(ctx context.Context, ids []uuid.UUID) error
	// Logout removes the row outright rather than revoking it. A revoked row is the signal
	// that a token was rotated away, and presenting one again is treated as a replay; a
	// logged-out token must not look like that, or signing out on one device would cascade
	// every other device off too.
	DeleteRefreshTokenByToken(ctx context.Context, tokenHash string) error
	// Tombstoned, not dropped — see DeleteTeam.
	DeleteSession(ctx context.Context, id uuid.UUID) error
	// A REST delete tombstones rather than dropping the row, so the deletion reaches sync
	// clients. A hard DELETE produced no row for ListSyncChangesSince to return, so a device
	// holding the team was never told it was gone and re-created it on its next push.
	DeleteTeam(ctx context.Context, id uuid.UUID) error
	EndRosterMembership(ctx context.Context, arg EndRosterMembershipParams) (RosterMembership, error)
	GetActiveRosterMembership(ctx context.Context, arg GetActiveRosterMembershipParams) (RosterMembership, error)
	GetDrill(ctx context.Context, id uuid.UUID) (Drill, error)
	GetFormFieldByKey(ctx context.Context, arg GetFormFieldByKeyParams) (FormField, error)
	GetFormInstance(ctx context.Context, id uuid.UUID) (FormInstance, error)
	GetFormTemplate(ctx context.Context, id uuid.UUID) (FormTemplate, error)
	GetGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetPerson(ctx context.Context, id uuid.UUID) (Person, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRosterMembership(ctx context.Context, id uuid.UUID) (RosterMembership, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetUserAccountByAppleSub(ctx context.Context, appleSub *string) (UserAccount, error)
	GetUserAccountByEmail(ctx context.Context, email string) (UserAccount, error)
	GetUserAccountByID(ctx context.Context, id uuid.UUID) (UserAccount, error)
	// The account behind an authenticated Person. Access tokens name a Person, so this is
	// how a signed-in caller reaches their own account row — used by the Apple-link
	// endpoint, where the session is the proof of ownership that the address is not.
	GetUserAccountByPersonID(ctx context.Context, personID uuid.UUID) (UserAccount, error)
	HasMembership(ctx context.Context, arg HasMembershipParams) (bool, error)
	// Attach an Apple identity to an account that does not have one. Guarded on
	// apple_sub IS NULL rather than checked beforehand: the handler does read the row first
	// (to tell an idempotent re-link from a different Apple ID, which deserve different
	// answers), but a predicate on the write is what makes two concurrent links unable to
	// overwrite each other and silently cut one Apple ID off from the account.
	LinkAppleSub(ctx context.Context, arg LinkAppleSubParams) (int64, error)
	ListActiveRoster(ctx context.Context, teamID uuid.UUID) ([]ListActiveRosterRow, error)
	ListAnswersForInstance(ctx context.Context, instanceID uuid.UUID) ([]ListAnswersForInstanceRow, error)
	ListChildren(ctx context.Context, guardianPersonID uuid.UUID) ([]Person, error)
	ListDrillsInOrg(ctx context.Context, organizationID uuid.UUID) ([]Drill, error)
	ListFormFields(ctx context.Context, templateID uuid.UUID) ([]FormField, error)
	ListFormTemplates(ctx context.Context, arg ListFormTemplatesParams) ([]FormTemplate, error)
	ListGamesForTeam(ctx context.Context, teamID uuid.UUID) ([]Game, error)
	ListInstancesForPerson(ctx context.Context, arg ListInstancesForPersonParams) ([]ListInstancesForPersonRow, error)
	// Tie-broken on id: orgs created inside one transaction share a now() timestamp, and
	// resolveOrg takes the first row as the caller's default org when no X-Organization-ID
	// is sent. Without the tie-break that default is whatever Postgres happens to return.
	ListMembershipsForPerson(ctx context.Context, personID uuid.UUID) ([]ListMembershipsForPersonRow, error)
	// The personal org(s) this person owns, selected on organizations.owner_person_id.
	//
	// This used to select on membership and argue that the two were the same thing —
	// "a personal org is created with its owner as sole member, so member == owner". That
	// held only because nothing could add a second member to an org. Once something can, a
	// plain member deleting their own account deletes the org out from under its owner. The
	// name said "ForPerson" and meant "belonging to"; it now means "owned by", which is why
	// it is renamed rather than quietly reworded.
	//
	// Club orgs stay excluded even when the caller owns one: whether deleting a club
	// owner's account should destroy the club is a product decision that has not been made,
	// and the conservative answer — orphan it, leave the data — matches today's behaviour.
	ListOwnedPersonalOrgIDsForPerson(ctx context.Context, ownerPersonID *uuid.UUID) ([]uuid.UUID, error)
	ListRolesInOrg(ctx context.Context, arg ListRolesInOrgParams) ([]string, error)
	ListSessionBlocks(ctx context.Context, sessionID uuid.UUID) ([]ListSessionBlocksRow, error)
	ListSessionsInOrg(ctx context.Context, arg ListSessionsInOrgParams) ([]Session, error)
	// The delta an account hasn't seen: synced rows across every source, ordered by
	// the shared cursor. Projected tables contribute their type; sync_documents
	// carries its own.
	ListSyncChangesSince(ctx context.Context, arg ListSyncChangesSinceParams) ([]ListSyncChangesSinceRow, error)
	ListTeamsForPerson(ctx context.Context, personID uuid.UUID) ([]ListTeamsForPersonRow, error)
	ListTeamsInOrg(ctx context.Context, organizationID uuid.UUID) ([]ListTeamsInOrgRow, error)
	// Whether an organization may see a Person at all: they are not tombstoned, and they
	// either hold a membership in the org or are rostered on one of its live teams. The
	// roster arm matters because an athlete can be added to a team without a membership
	// row of their own.
	PersonVisibleInOrg(ctx context.Context, arg PersonVisibleInOrgParams) (bool, error)
	// Rotation's single-use guard, not a follow-up to one. handleRefresh used to read the
	// row, decide it was live, and then revoke it unconditionally — a check-then-act with
	// nothing between the two statements, so concurrent presentations of one token all read
	// it before any of them wrote and every one of them minted a fresh family (measured: 6
	// live chains from 32 simultaneous redemptions of a single token). That is the exact
	// invariant reuse detection rests on: one token, one use, and a second use is evidence.
	//
	// The predicate makes the write itself the arbiter. Zero rows means somebody else
	// redeemed this token between our read and our write, which the caller treats the same
	// way it treats a replay inside the grace window — microseconds apart is the retry case,
	// not the theft case.
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) (int64, error)
	// Revoke every live token for one account. Used when a already-rotated token is
	// presented again: that is a replay, and the only safe reading is that the chain has
	// leaked, so the whole family goes rather than just the one token.
	RevokeRefreshTokensForAccount(ctx context.Context, userAccountID uuid.UUID) error
	// Athletes (Persons) whose ONLY organizational linkage is via the org(s) being
	// deleted. Deleting those orgs strips their membership/roster rows but leaves the
	// Person itself — name, birthdate, medical notes: minors' PII we are legally
	// required to erase (COPPA/GDPR). ON DELETE CASCADE never reaches these, so we
	// delete them explicitly. A person still linked to any org OUTSIDE the delete-set
	// survives (the shared-athlete / multi-org case). Excludes the caller's own
	// Person (deleted separately) and anyone synced by a different account.
	SelectOrphanedAthletePersonIDs(ctx context.Context, arg SelectOrphanedAthletePersonIDsParams) ([]uuid.UUID, error)
	SyncTombstoneDiagram(ctx context.Context, arg SyncTombstoneDiagramParams) (int64, error)
	SyncTombstoneDocument(ctx context.Context, arg SyncTombstoneDocumentParams) (int64, error)
	SyncTombstoneDrill(ctx context.Context, arg SyncTombstoneDrillParams) (int64, error)
	SyncTombstoneEvent(ctx context.Context, arg SyncTombstoneEventParams) (int64, error)
	SyncTombstonePerson(ctx context.Context, arg SyncTombstonePersonParams) (int64, error)
	SyncTombstonePlayer(ctx context.Context, arg SyncTombstonePlayerParams) (int64, error)
	SyncTombstoneSession(ctx context.Context, arg SyncTombstoneSessionParams) (int64, error)
	// Tombstones are per-table: a delete can only affect a row this account owns,
	// so REST-created rows (sync_account_id IS NULL) are never tombstoned.
	SyncTombstoneTeam(ctx context.Context, arg SyncTombstoneTeamParams) (int64, error)
	SyncUpsertDiagram(ctx context.Context, arg SyncUpsertDiagramParams) (int64, error)
	SyncUpsertDocument(ctx context.Context, arg SyncUpsertDocumentParams) (int64, error)
	SyncUpsertDrill(ctx context.Context, arg SyncUpsertDrillParams) (int64, error)
	SyncUpsertEvent(ctx context.Context, arg SyncUpsertEventParams) (int64, error)
	// The one statement that may adopt an unowned row, and only the caller's own Person.
	// /auth/apple provisions the coach's Person through CreatePersonWithID with a NULL
	// sync_account_id, and the app then pushes that same id expecting the two to reconcile
	// into one identity (see 0003_person_sync.sql). The second disjunct permits exactly that:
	// persons.id equals the pushing account's id only for the caller's own row, so it cannot
	// be used to claim anyone else's.
	SyncUpsertPerson(ctx context.Context, arg SyncUpsertPersonParams) (int64, error)
	SyncUpsertPlayer(ctx context.Context, arg SyncUpsertPlayerParams) (int64, error)
	SyncUpsertSession(ctx context.Context, arg SyncUpsertSessionParams) (int64, error)
	// Upserts are keyed on the client-supplied primary key, so each conflict clause is
	// guarded on the row's owner: a push naming a row this account does not own affects
	// zero rows, and the handler returns it to the client as a conflict. A NULL owner
	// (a REST-created row) fails the guard too — the separation 0002_sync.sql describes.
	// Ownership never transfers on update, so the SET clauses do not reassign
	// sync_account_id; SyncUpsertPerson is the one exception, see its comment.
	SyncUpsertTeam(ctx context.Context, arg SyncUpsertTeamParams) (int64, error)
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
