// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Roster (time-bounded memberships) ----------------------------------------
	AddRosterMembership(ctx context.Context, arg AddRosterMembershipParams) (RosterMembership, error)
	// The moat query: cross-instance aggregation of scored fields for one athlete,
	// optionally scoped to a context. Powers readiness means, effort trends, etc.
	AggregateScoresForPerson(ctx context.Context, arg AggregateScoresForPersonParams) ([]AggregateScoresForPersonRow, error)
	CreateFormAnswer(ctx context.Context, arg CreateFormAnswerParams) (FormAnswer, error)
	CreateFormField(ctx context.Context, arg CreateFormFieldParams) (FormField, error)
	// Instances & answers -------------------------------------------------------
	CreateFormInstance(ctx context.Context, arg CreateFormInstanceParams) (FormInstance, error)
	// Templates ----------------------------------------------------------------
	CreateFormTemplate(ctx context.Context, arg CreateFormTemplateParams) (FormTemplate, error)
	CreateGuardianship(ctx context.Context, arg CreateGuardianshipParams) (Guardianship, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error)
	DeleteTeam(ctx context.Context, id uuid.UUID) error
	EndRosterMembership(ctx context.Context, arg EndRosterMembershipParams) (RosterMembership, error)
	GetActiveRosterMembership(ctx context.Context, arg GetActiveRosterMembershipParams) (RosterMembership, error)
	GetFormFieldByKey(ctx context.Context, arg GetFormFieldByKeyParams) (FormField, error)
	GetFormInstance(ctx context.Context, id uuid.UUID) (FormInstance, error)
	GetFormTemplate(ctx context.Context, id uuid.UUID) (FormTemplate, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetPerson(ctx context.Context, id uuid.UUID) (Person, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetRosterMembership(ctx context.Context, id uuid.UUID) (RosterMembership, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetUserAccountByEmail(ctx context.Context, email string) (UserAccount, error)
	GetUserAccountByID(ctx context.Context, id uuid.UUID) (UserAccount, error)
	HasMembership(ctx context.Context, arg HasMembershipParams) (bool, error)
	ListActiveRoster(ctx context.Context, teamID uuid.UUID) ([]ListActiveRosterRow, error)
	ListAnswersForInstance(ctx context.Context, instanceID uuid.UUID) ([]ListAnswersForInstanceRow, error)
	ListChildren(ctx context.Context, guardianPersonID uuid.UUID) ([]Person, error)
	ListFormFields(ctx context.Context, templateID uuid.UUID) ([]FormField, error)
	ListFormTemplates(ctx context.Context, arg ListFormTemplatesParams) ([]FormTemplate, error)
	ListInstancesForPerson(ctx context.Context, arg ListInstancesForPersonParams) ([]ListInstancesForPersonRow, error)
	ListMembershipsForPerson(ctx context.Context, personID uuid.UUID) ([]ListMembershipsForPersonRow, error)
	ListRolesInOrg(ctx context.Context, arg ListRolesInOrgParams) ([]string, error)
	ListTeamsForPerson(ctx context.Context, personID uuid.UUID) ([]ListTeamsForPersonRow, error)
	ListTeamsInOrg(ctx context.Context, organizationID uuid.UUID) ([]ListTeamsInOrgRow, error)
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeRefreshTokenByToken(ctx context.Context, token string) error
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
