// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Roster (time-bounded memberships) ----------------------------------------
	AddRosterMembership(ctx context.Context, arg AddRosterMembershipParams) (RosterMembership, error)
	// Idempotent: a coach already on a team stays on it, and the create path can call this
	// without first asking.
	AddTeamStaff(ctx context.Context, arg AddTeamStaffParams) error
	// The register read down the season instead of across one fixture.
	//
	// A coach's real question is not "who is coming on Saturday" but "who keeps missing
	// training", and until now the only way to ask it was to open every sheet in turn and
	// count by hand. This is that count, one line per player.
	//
	// The universe is the active squad times the team's events in the window, not the
	// attendance rows: a player who was never marked at all has to appear as somebody who
	// missed six sessions, and driving this off `attendances` would show them as having a
	// clean record because silence leaves no row. That is what `not_recorded` separates out —
	// a squad nobody registered and a squad that turned up are the same numbers otherwise.
	//
	// A cancelled game drops out. Nobody attends a match that was called off, and counting it
	// as an absence would punish a squad for a coach's decision.
	//
	// Rows with no date are in the window only when no window was asked for: `starts_at >=
	// NULL` is NULL and so fails the filter, which is the wanted answer — a fixture with no
	// time cannot be placed in March.
	AggregateAttendanceForTeam(ctx context.Context, arg AggregateAttendanceForTeamParams) ([]AggregateAttendanceForTeamRow, error)
	// The moat query: cross-instance aggregation of scored fields for one athlete,
	// optionally scoped to a context. Powers readiness means, effort trends, etc.
	//
	// The average accumulates in numeric, not double precision. avg() over float8 sums in
	// float8, so two answers near the type's ceiling overflowed the running sum and the
	// whole query failed — every key at once, not just the one with the big values, because
	// this is one GROUP BY over every answer about the athlete:
	//
	//   ERROR: value out of range: overflow (SQLSTATE 22003)
	//
	// validateAnswer now bounds what can be written (see maxAnswerMagnitude), but rows
	// already in the table are not reachable by any endpoint — nothing in this API deletes a
	// form instance or an answer — so a validation-only fix would leave existing athletes
	// with a permanently 500ing aggregate. numeric has no such ceiling, and the average of
	// values that each fit in float8 always fits in float8 on the way back out.
	AggregateScoresForPerson(ctx context.Context, arg AggregateScoresForPersonParams) ([]AggregateScoresForPersonRow, error)
	// Reminders: chasing the squad that has not replied yet -----------------------
	// Take the fixtures that are close enough to chase, and mark them chased in the same
	// statement.
	//
	// The claim is the point. A deployed service runs more than one instance and every
	// instance sweeps on the same schedule, so a select-then-update would hand the same
	// fixture to all of them and every player would get one push per replica. Here the row is
	// only returned if this statement is the one that set the column: under READ COMMITTED a
	// second instance re-evaluates `reminder_sent_at IS NULL` after the first commits, finds
	// it set, and updates nothing. No advisory lock, no leader election, no SKIP LOCKED --
	// the column that records the work is the same column that claims it.
	//
	// Only 'scheduled' games. A cancelled fixture has nothing to reply to (POST /rsvp refuses
	// it), and a completed one is in the past by definition.
	//
	// The upper bound comes in as an instant rather than an interval so the caller owns the
	// lead time, and `kickoff_at > now()` keeps a match that has already started out of it: a
	// sweep that fell behind should stay quiet rather than ask a squad whether they are
	// coming to something that kicked off an hour ago.
	ClaimGamesDueForReminder(ctx context.Context, until pgtype.Timestamptz) ([]ClaimGamesDueForReminderRow, error)
	// The training half, claimed the same way. Two conditions differ: a session has no status
	// column, and its team is optional -- a plan a coach drafted for themselves has no roster
	// to chase, so a NULL team_id drops out here rather than producing a sweep that finds
	// nobody.
	ClaimSessionsDueForReminder(ctx context.Context, until pgtype.Timestamptz) ([]ClaimSessionsDueForReminderRow, error)
	// Whether a session's register has been started, which is what decides whether it may
	// still be moved to another team.
	//
	// Counted on answers rather than rows: EnsureAttendance opens a blank line before either
	// setter runs, so a row on its own means nothing happened. A line with an RSVP or a
	// recorded status is somebody's statement about a specific squad's training, and carrying
	// it over to a different squad would attribute it to people who were never asked.
	CountAnsweredAttendanceForSession(ctx context.Context, sessionID *uuid.UUID) (int64, error)
	// How many of these ids are live drills in this organization. handleCreateSession asks
	// once for every drill its blocks reference and compares the answer with the number of
	// distinct ids it asked about; fewer means at least one block points at a drill that is
	// deleted, missing, or another org's. Counting rather than returning the rows is enough
	// because the request is rejected as a whole, and it keeps the check to one round trip
	// however many blocks the session has.
	CountDrillsInOrgByIDs(ctx context.Context, arg CountDrillsInOrgByIDsParams) (int64, error)
	// How many admins an organization would still have without this person. The guard against
	// the one mistake that cannot be undone through the API: an org whose last admin demotes
	// or removes themselves has nobody left who can manage members, and no endpoint that can
	// put one back.
	CountOtherAdminsInOrg(ctx context.Context, arg CountOtherAdminsInOrgParams) (int64, error)
	// Drills --------------------------------------------------------------------
	// A drill created here is a drill the app can see, for the reasons CreateTeam sets out:
	// sync_account_id puts the row in the caller's stream, seq gives a cursor something to
	// deliver, and payload is what a pull actually returns.
	//
	// The payload carries only id, title and fieldSetup, because that is all POST /drills
	// collects. Until now the app required a category, a duration and coaching points as
	// well, so a drill made this way could not be decoded at all and was dropped whole --
	// Codable loses the record over one missing key. Those fields are optional on the app
	// side now, so the drill arrives with blanks the coach can fill in rather than not
	// arriving. Inventing a category here was the alternative, and putting a coaching
	// decision nobody made into a coach's library is worse than leaving it empty.
	CreateDrill(ctx context.Context, arg CreateDrillParams) (Drill, error)
	CreateFormAnswer(ctx context.Context, arg CreateFormAnswerParams) (FormAnswer, error)
	CreateFormField(ctx context.Context, arg CreateFormFieldParams) (FormField, error)
	// Instances & answers -------------------------------------------------------
	CreateFormInstance(ctx context.Context, arg CreateFormInstanceParams) (FormInstance, error)
	// Templates ----------------------------------------------------------------
	CreateFormTemplate(ctx context.Context, arg CreateFormTemplateParams) (FormTemplate, error)
	// Games (game day) ----------------------------------------------------------
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateGuardianship(ctx context.Context, arg CreateGuardianshipParams) (Guardianship, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	// owner_person_id is not optional in practice: it is what account deletion selects on,
	// and an org created without one can never be deleted by the person who made it.
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	// Create a Person at an explicit id — the coach's deterministic account Person, so it
	// matches the id the app derives locally.
	//
	// DO NOTHING, not DO UPDATE. This used to adopt whatever row was already at that id,
	// and the id is UUIDv5(a namespace constant published in this repo, apple_sub), so it is
	// computable by anyone who knows the subject. POST /sync lets any authenticated account
	// insert a persons row at an id of its choosing — SyncUpsertPerson's ownership guard
	// governs conflicts, and there is no conflict when the row does not exist yet — so an
	// attacker could pre-create the row and have the victim's first Apple sign-in adopt it,
	// sync_account_id and all. From then on the victim's own account Person was the
	// attacker's to rewrite, tombstone and pull.
	//
	// Returning zero rows means the id is taken by a row we did not create. There is no
	// legitimate way for that to happen: authenticating as this coach requires /auth/apple,
	// so their own sync push cannot precede their own provisioning, and provisioning is one
	// transaction that commits whole or not at all. The caller treats it as a refusal.
	CreatePersonWithID(ctx context.Context, arg CreatePersonWithIDParams) (Person, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// Sessions ------------------------------------------------------------------
	// Same three columns as CreateDrill, and one field that needs saying out loud: the app
	// requires a date and the server always has one, so the payload carries scheduled_at
	// when it was given and the creation time when it was not. It is written as a number of
	// seconds since 2001-01-01, which is how Swift encodes a Date -- see
	// TestContractSwiftDatesSurviveAsNumbers, which pins that against this side drifting.
	//
	// teamID and each block's drillID may be absent. Both were required by the app until
	// now, and both are things this API has always let a caller leave out, so a session
	// without a team, or with a warm-up block that runs no drill, simply never arrived.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// The id is supplied rather than defaulted, because the session's payload has to carry
	// each block's id and is written in the same statement as the session itself.
	CreateSessionBlock(ctx context.Context, arg CreateSessionBlockParams) (SessionBlock, error)
	// A team created here is a team the app can see. It used to be invisible: a REST insert
	// left sync_account_id NULL, and ListSyncChangesSince scopes every branch to an account,
	// so nothing this endpoint made ever reached a phone. Editing converged before creating
	// did, which left the odd state where a web client could rename a team the app owned but
	// not create one of its own.
	//
	// Three columns make it visible, and all three are needed. sync_account_id puts the row
	// in the caller's stream; seq gives a cursor something to deliver; payload is what a pull
	// actually returns, so a row without one arrives as a null record the client cannot
	// decode.
	//
	// The payload is built here rather than defaulted, because Swift's Codable throws on a
	// missing required key and takes the whole record with it. Team's decoder requires id,
	// name, ageGroup, season and accentName -- see Models/Team.swift in the app -- so all
	// five are written. organizationID is deliberately left out: the app reads it with
	// decodeIfPresent and falls back to its own personal-org constant, which is the right
	// answer for a solo coach and better than asserting a server org id the app has never
	// seen.
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	// Sign in with Apple is the only path that creates an account, so an account is born
	// with its Apple subject and there is no credential of ours to store alongside it.
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error)
	// The highest cursor this server could have issued.
	//
	// A pull uses it to bounds-check the cursor it was handed. Every cursor the server
	// returns is the seq of a row it actually delivered, so a legitimate cursor is never
	// above this; a cursor that is can only have come from a sequence that moved backwards
	// under a client that had already passed it -- which is what a database restore does,
	// and a restore is the documented way back from 0009. Without the check, such a cursor
	// is answered with an empty page and echoed back unchanged, which is exactly the
	// client's "you are up to date" condition. See docs/AUDIT-5.md M2.
	//
	// pg_sequence_last_value reads the sequence's own page rather than consuming a value,
	// so this costs no cursor and no write.
	//
	// It is NULL when the sequence has not been called since it was created or reset, and
	// that is deliberately left as NULL rather than folded to 0. A restore taken by pg_dump
	// or PITR brings last_value back with is_called set, so the real case this guards has a
	// number. NULL means something reset the sequence without writing through it, and then
	// 0 is not the highest cursor the server could have issued -- the rows still carry
	// higher seqs, and folding to 0 would make a pull reject the cursor it had itself just
	// returned, resyncing that device from the beginning on every single pull. The caller
	// reads `known = false` as "no bound available" and lets the cursor stand.
	CurrentSyncSeq(ctx context.Context) (CurrentSyncSeqRow, error)
	// Scoped to the owner, so holding a token is not enough to unregister someone else's
	// device. Sign-out is the ordinary caller.
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) (int64, error)
	// Pruning after Apple rejects a token, which is not scoped to a person on purpose: the
	// rejection says this token is dead everywhere, and the row may well belong to whoever
	// registered it before the device changed hands.
	DeleteDeviceTokenAnyOwner(ctx context.Context, token string) error
	DeleteGuardianship(ctx context.Context, arg DeleteGuardianshipParams) error
	// Removes a person from an organization outright, every role at once. Roles are rows, so
	// "remove this member" is a delete of the set rather than of one of them.
	DeleteMembershipsForPersonInOrg(ctx context.Context, arg DeleteMembershipsForPersonInOrgParams) error
	DeleteOrganizationsByIDs(ctx context.Context, ids []uuid.UUID) error
	DeletePersonByID(ctx context.Context, id uuid.UUID) error
	DeletePersonsByIDs(ctx context.Context, ids []uuid.UUID) error
	// Logout removes the row outright rather than revoking it. A revoked row is the signal
	// that a token was rotated away, and presenting one again is treated as a replay; a
	// logged-out token must not look like that, or signing out on one device would cascade
	// every other device off too.
	DeleteRefreshTokenByToken(ctx context.Context, tokenHash string) error
	// Tombstoned, not dropped — see DeleteTeam.
	DeleteSession(ctx context.Context, id uuid.UUID) error
	// A REST delete tombstones rather than dropping the row, so the deletion reaches sync
	// clients. A hard DELETE produced no row for ListSyncChangesSince to return, so a device
	// holding the team was never told it was gone and re-created it on its next push.
	// Clears the row's content for the same reason SyncTombstoneTeam does: a tombstone
	// needs the id, the flag and a seq, and nothing else. See docs/AUDIT-5.md L1.
	DeleteTeam(ctx context.Context, id uuid.UUID) error
	EndRosterMembership(ctx context.Context, arg EndRosterMembershipParams) (RosterMembership, error)
	// Attendance (RSVP + who actually came) ------------------------------------
	// Open the row for (event, person) if it is not already open.
	//
	// Paired with one of the two setters below rather than folded into them as an upsert:
	// the uniqueness that matters lives in two partial indexes (one per event kind, see
	// 0014_attendance.sql), and ON CONFLICT can only infer one target, so an upsert would
	// have to be written twice and each copy would silently cover only half the table. A
	// bare DO NOTHING covers whichever index the row actually hits, and makes this safe to
	// call on every write without asking first.
	//
	// The two statements do not need a transaction between them. An insert whose setter
	// never ran leaves a row with no answer and no status, which is exactly the row that
	// would have been read as "has not replied" had the insert not happened at all.
	EnsureAttendance(ctx context.Context, arg EnsureAttendanceParams) error
	GetActiveRosterMembership(ctx context.Context, arg GetActiveRosterMembershipParams) (RosterMembership, error)
	GetDrill(ctx context.Context, id uuid.UUID) (Drill, error)
	GetFormInstance(ctx context.Context, id uuid.UUID) (FormInstance, error)
	GetFormTemplate(ctx context.Context, id uuid.UUID) (FormTemplate, error)
	GetGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetPerson(ctx context.Context, id uuid.UUID) (Person, error)
	// Resolves the address a member is invited by to the Person it belongs to.
	//
	// Addressing by email rather than by person id is the authorization: a person id is an
	// opaque handle that says nothing about whether the caller has any business adding its
	// owner, whereas knowing someone's sign-in address is the ordinary evidence that you
	// know them. It also keeps this endpoint from becoming a way to sweep person ids and
	// pull each one into an org to read it.
	//
	// user_accounts.email, not persons.email: the former is the verified Apple claim and is
	// UNIQUE, the latter is editable contact information and neither.
	GetPersonIDByAccountEmail(ctx context.Context, email string) (uuid.UUID, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetUserAccountByAppleSub(ctx context.Context, appleSub *string) (UserAccount, error)
	GetUserAccountByEmail(ctx context.Context, email string) (UserAccount, error)
	GetUserAccountByID(ctx context.Context, id uuid.UUID) (UserAccount, error)
	// The account behind a Person, and so the verified address invitations are matched on.
	// A Person with no account has no row here, which is the right answer rather than an
	// error: an athlete with no login has nothing to sign in and accept with.
	GetUserAccountByPersonID(ctx context.Context, personID uuid.UUID) (UserAccount, error)
	// Whether one person is a recorded guardian of another. This is what makes the parent
	// role mean something narrower than "member of the org": a parent sees their own
	// children and nobody else's.
	IsGuardianOf(ctx context.Context, arg IsGuardianOfParams) (bool, error)
	ListActiveRoster(ctx context.Context, teamID uuid.UUID) ([]ListActiveRosterRow, error)
	ListAnswersForInstance(ctx context.Context, instanceID uuid.UUID) ([]ListAnswersForInstanceRow, error)
	// The sheet: one line per person, whether or not they have answered.
	//
	// The people are the union of two sets, not just the current roster. A player who left
	// the club in March was still at February's match, and driving this off
	// roster_memberships alone would erase them from that game's record -- the attendance
	// row would still exist, unreachable, and the coach's own count would disagree with it.
	// `on_roster` is what tells the two apart on the far side.
	//
	// The union is a CTE over two indexed lookups rather than a scan of persons filtered by
	// "on this team or at this event", which is the same set and reads every person in the
	// database to find it.
	//
	// `all_people` narrows the result to named people without a second query: the RSVP and
	// attendance writes each return the one line they changed, and re-reading a squad of
	// twenty to answer with one of them is a query nobody asked for. Role scoping is
	// deliberately NOT done here -- see handleGetAttendance, which needs the whole sheet to
	// count it before narrowing what it shows.
	ListAttendanceForEvent(ctx context.Context, arg ListAttendanceForEventParams) ([]ListAttendanceForEventRow, error)
	// p.deleted = false for the same reason every other person read has it: a tombstoned
	// Person is gone, and since a tombstone now clears its display columns it would list as
	// a blank row rather than a name. Nothing calls this yet -- guardianships are not
	// exposed -- which is exactly why it is worth fixing before something does.
	ListChildren(ctx context.Context, guardianPersonID uuid.UUID) ([]Person, error)
	ListDeviceTokensForPerson(ctx context.Context, personID uuid.UUID) ([]string, error)
	ListDrillsInOrg(ctx context.Context, organizationID uuid.UUID) ([]Drill, error)
	ListFormFields(ctx context.Context, templateID uuid.UUID) ([]FormField, error)
	ListFormTemplates(ctx context.Context, arg ListFormTemplatesParams) ([]FormTemplate, error)
	ListGamesForTeam(ctx context.Context, teamID uuid.UUID) ([]Game, error)
	ListGuardiansForChild(ctx context.Context, childPersonID uuid.UUID) ([]Person, error)
	ListInstancesForPerson(ctx context.Context, arg ListInstancesForPersonParams) ([]ListInstancesForPersonRow, error)
	// Tie-broken on id: orgs created inside one transaction share a now() timestamp, and
	// resolveOrg takes the first row as the caller's default org when no X-Organization-ID
	// is sent. Without the tie-break that default is whatever Postgres happens to return.
	ListMembershipsForPerson(ctx context.Context, personID uuid.UUID) ([]ListMembershipsForPersonRow, error)
	// Everyone in an organization, one row per person with their roles gathered into an
	// array. Roles are rows -- UNIQUE (person_id, organization_id, role) -- so a person
	// holding both coach and parent is two memberships, and listing them unaggregated would
	// show that person twice with no way to tell it was one human.
	//
	// Deliberately not a person read: display_name and email are what a member list needs,
	// and birthdate, phone and medical notes are not. Someone who may manage members is not
	// thereby entitled to every athlete's medical history.
	ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error)
	// The personal org(s) this person owns, selected on organizations.owner_person_id.
	//
	// This used to select on membership and argue that the two were the same thing —
	// "a personal org is created with its owner as sole member, so member == owner". That
	// held only because nothing could add a second member to an org. Once something can, a
	// plain member deleting their own account deletes the org out from under its owner. The
	// name said "ForPerson" and meant "belonging to"; it now means "owned by", which is why
	// it is renamed rather than quietly reworded.
	//
	// Club orgs stay excluded even when the caller owns one: whether deleting a club
	// owner's account should destroy the club is a product decision that has not been made,
	// and the conservative answer — orphan it, leave the data — matches today's behaviour.
	ListOwnedPersonalOrgIDsForPerson(ctx context.Context, ownerPersonID *uuid.UUID) ([]uuid.UUID, error)
	// The invitee's side. Keyed on the address alone, because the caller proved they own it
	// by signing in with it -- see 0011_invitations.sql for why there is no token.
	ListPendingInvitationsForEmail(ctx context.Context, email string) ([]ListPendingInvitationsForEmailRow, error)
	// What the club has outstanding. Expired rows are filtered rather than deleted: an
	// invitation nobody answered is a fact about what was offered, and the partial unique
	// index only guards pending ones, so a stale row never blocks a fresh send.
	ListPendingInvitationsForOrg(ctx context.Context, organizationID uuid.UUID) ([]ListPendingInvitationsForOrgRow, error)
	// Who to tell when a team's fixture is scheduled, moved or called off: the squad, and the
	// parents of the squad. It is the RSVP's audience -- the people the register is asking --
	// so it is the roster and its guardians rather than everyone who can see the team.
	//
	// Filtered to people who have a device registered, which is a departure from how an
	// invitation notifies: that one tells a single named person and asks nothing about their
	// phone. A fixture fans out to a whole squad plus their families, and the delivery queue
	// is bounded and drained by one worker (see internal/push), so a coach entering a
	// season's fixtures in one sitting would otherwise push hundreds of deliveries for people
	// with nowhere to deliver to, and the drops would land on whoever was behind them.
	//
	// The actor is excluded. A coach who just moved a kickoff does not need their own phone
	// to tell them they moved it.
	ListReachablePeopleForTeam(ctx context.Context, arg ListReachablePeopleForTeamParams) ([]uuid.UUID, error)
	// One person's roles in one organization. Used before a role change, so the handler can
	// say what it is replacing and refuse to strip the last admin.
	ListRolesForPersonInOrg(ctx context.Context, arg ListRolesForPersonInOrgParams) ([]string, error)
	ListSessionBlocks(ctx context.Context, sessionID uuid.UUID) ([]ListSessionBlocksRow, error)
	ListSessionsInOrg(ctx context.Context, arg ListSessionsInOrgParams) ([]Session, error)
	// The delta an account hasn't seen: synced rows across every source, ordered by
	// the shared cursor. Projected tables contribute their type; sync_documents
	// carries its own.
	//
	// One page of it, not all of it. This had no LIMIT, and a pull accumulated whatever it
	// returned into a single response: pushes are capped at maxSyncBatch records but nothing
	// caps how many pushes an account makes, so an account grows its own delta without bound
	// and then every full pull -- since=0, which is what a reinstall sends -- is an unbounded
	// allocation on the server.
	//
	// seq comes from a single sequence and is unique across every source, so ordering by it
	// is total and a page boundary cannot fall inside a group of equal keys. That is what
	// makes "resume from the last seq I returned" safe: no row is skipped and none is sent
	// twice. The client drains by asking again until the cursor stops moving; nothing about
	// the wire format changes.
	//
	// A page is bounded twice, by rows and by bytes, and both bounds are applied here.
	//
	// The byte bound used to be applied in Go, after every row in the window had been read
	// off the wire and materialized. That bounded the response but not the read, and the two
	// bounds only balance at max_bytes/lim -- ~4.2 KiB per record at 2 MiB and 500. Above
	// that the byte bound binds first and the window is mostly waste: measured at 1 MiB
	// payloads, a pull allocated 513 MiB to return a single record. Cutting here means the
	// discarded rows never cross the wire. See docs/AUDIT-5.md M1.
	//
	// rn = 1 keeps the rule that made the Go loop correct: the first row goes in whatever it
	// weighs. A payload above the whole budget would otherwise be skipped by every pull
	// forever, and because the cursor only advances over rows actually delivered the client
	// would ask for it again and again and never get past it. Running weights are
	// non-decreasing, so "the prefix that fits" is exactly what this filter selects.
	//
	// Every branch has an index on (sync_account_id, seq), and the planner index-scans each
	// one and then top-N heapsorts into the window.
	//
	// The ::bigint on max_bytes is load-bearing and not cosmetic. sqlc infers a parameter's
	// type from the column it is compared against, and it cannot resolve one that comes out
	// of a derived table carrying window functions -- without the cast, generation fails with
	// `table alias "budgeted" does not exist`. The cast tells it the type outright.
	//
	// What this still does not buy, and it is the open half of M1: it does not stop early.
	// There is no merge-append plan available for this shape (checked with enable_sort off;
	// it sorts anyway), so each page reads the account's remaining delta to find the next
	// `lim` rows, and draining k pages costs k scans of a shrinking tail. When the byte bound
	// binds, k is much larger than rows/lim -- 500 pages for 500 one-MiB records -- and the
	// drain is quadratic in the row count. Bounding that needs a cap on a single record's
	// payload at push time, which is a wire change and is written up as M1 (3).
	ListSyncChangesSince(ctx context.Context, arg ListSyncChangesSinceParams) ([]ListSyncChangesSinceRow, error)
	ListTeamStaff(ctx context.Context, teamID uuid.UUID) ([]Person, error)
	ListTeamsForPerson(ctx context.Context, personID uuid.UUID) ([]ListTeamsForPersonRow, error)
	// The teams a caller may see, which is a different set per role.
	//
	// One statement rather than one per role, because every non-admin arm asks the same
	// question in the end: is this team connected to me? A coach is connected by staffing
	// it, a player by being rostered on it, a parent through a child. Someone who is two of
	// those -- a parent who also coaches, which the role model explicitly allows -- gets the
	// union without any branch having to remember they exist.
	//
	// `see_all` is the whole of the role logic: admins and directors see the organization,
	// per the permission matrix. Everyone else gets the connected set, and a coach who
	// staffs nothing sees nothing, which is the correct answer to "your teams" rather than
	// an error.
	ListTeamsVisibleInOrg(ctx context.Context, arg ListTeamsVisibleInOrgParams) ([]ListTeamsVisibleInOrgRow, error)
	// Who still owes an answer, and can be reached to be asked for it.
	//
	// Narrower than ListReachablePeopleForTeam in the way that matters: someone who already
	// said they are coming has done what was asked, and chasing them is how a reminder
	// becomes noise people turn off. A line with a recorded attendance but no RSVP still
	// counts as unanswered -- the coach marking someone present is not that person replying.
	//
	// Guardians come along for the child's silence, not their own. A nine-year-old has no
	// device and no login; the reply is going to come from a parent or not at all, so the
	// parents of every unanswered player are in the set even though the players themselves
	// may not be.
	ListUnansweredReachablePeopleForEvent(ctx context.Context, arg ListUnansweredReachablePeopleForEventParams) ([]uuid.UUID, error)
	// Whether this Person can sign in. PATCH /persons/{id} uses it to keep a coach's edit
	// rights to the loginless athletes they manage, the same population POST /persons can
	// create -- someone with an account edits their own row.
	PersonHasUserAccount(ctx context.Context, personID uuid.UUID) (bool, error)
	// Whether this Person is a row the caller pushed through sync themselves.
	//
	// Separate from the org arms and available to every role, because it is not a claim
	// about the organization: sync streams are per-account, so this matches only rows the
	// caller wrote and already holds on their own device. An athlete the app creates arrives
	// carrying no membership and no roster row, so without this the person endpoints answer
	// 404 for the athletes a coach actually has.
	PersonOwnedBySyncAccount(ctx context.Context, arg PersonOwnedBySyncAccountParams) (bool, error)
	// Whether the caller may see a Person at all: they are not tombstoned, and one of three
	// things is true -- they hold a membership in the caller's org, they are rostered on one
	// of its live teams, or the caller pushed them through sync themselves. The roster arm
	// matters because an athlete can be added to a team without a membership row of their
	// own.
	//
	// This is the *organization* arm only. Sync ownership used to be a third disjunct here;
	// it is PersonOwnedBySyncAccount now, because the two answer different questions and the
	// role rules ask them of different callers. Staff get this one -- they run the club, so
	// they see everyone in it. A parent does not, and would have been handed the whole club
	// by the membership arm.
	PersonVisibleInOrg(ctx context.Context, arg PersonVisibleInOrgParams) (bool, error)
	// Delete refresh tokens that expired long enough ago to be of no further use.
	//
	// Nothing ever deleted. RevokeRefreshToken and RevokeRefreshTokensForAccount stamp
	// revoked_at; logout removes its own row; everything else accumulated, one row per
	// sign-in and one per refresh, forever. Since password authentication was removed a
	// refresh token is the only credential this service stores, so the table is both the
	// fastest-growing thing here and the most sensitive. See docs/AUDIT-2.md L4.
	//
	// The predicate is expires_at, not revoked_at, and that is the whole subtlety. A revoked
	// row is what replay detection reads: presenting an already-rotated token is evidence
	// the chain leaked, and the response is to revoke the family. Delete revoked rows
	// eagerly and a replay stops looking like a replay -- it looks like an unknown token,
	// answered with a plain 401, and the theft goes unremarked. Keying on expiry keeps every
	// revoked row for as long as the token it describes could still be presented, plus the
	// grace the caller passes.
	ReapExpiredRefreshTokens(ctx context.Context, grace pgtype.Interval) (int64, error)
	RemoveTeamStaff(ctx context.Context, arg RemoveTeamStaffParams) (int64, error)
	// Answers an invitation, and is the whole concurrency story. The status test is inside
	// the UPDATE, so two accepts of the same invitation cannot both see 'pending' and both
	// grant the roles -- the second matches no row and is told it was already answered.
	// Expiry is checked here too, so a row that aged out between the read and the write
	// cannot slip through.
	RespondToInvitation(ctx context.Context, arg RespondToInvitationParams) (int64, error)
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error)
	// Rotation's single-use guard, not a follow-up to one. handleRefresh used to read the
	// row, decide it was live, and then revoke it unconditionally — a check-then-act with
	// nothing between the two statements, so concurrent presentations of one token all read
	// it before any of them wrote and every one of them minted a fresh family (measured: 6
	// live chains from 32 simultaneous redemptions of a single token). That is the exact
	// invariant reuse detection rests on: one token, one use, and a second use is evidence.
	//
	// The predicate makes the write itself the arbiter. Zero rows means somebody else
	// redeemed this token between our read and our write, which the caller treats the same
	// way it treats a replay inside the grace window — microseconds apart is the retry case,
	// not the theft case.
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) (int64, error)
	// Revoke every live token for one account. Used when a already-rotated token is
	// presented again: that is a replay, and the only safe reading is that the chain has
	// leaked, so the whole family goes rather than just the one token.
	RevokeRefreshTokensForAccount(ctx context.Context, userAccountID uuid.UUID) error
	// Athletes (Persons) whose ONLY organizational linkage is via the org(s) being
	// deleted. Deleting those orgs strips their membership/roster rows but leaves the
	// Person itself — name, birthdate, medical notes: minors' PII we are legally
	// required to erase (COPPA/GDPR). ON DELETE CASCADE never reaches these, so we
	// delete them explicitly. A person still linked to any org OUTSIDE the delete-set
	// survives (the shared-athlete / multi-org case). Excludes the caller's own
	// Person (deleted separately) and anyone synced by a different account.
	SelectOrphanedAthletePersonIDs(ctx context.Context, arg SelectOrphanedAthletePersonIDsParams) ([]uuid.UUID, error)
	// Record what a player said, and who said it. rsvp_by_person_id is the caller, which is
	// not always the subject: a parent answers for a child, and a coach answers for a player
	// with no login.
	//
	// The event is matched with an OR over the two nullable keys rather than a branch per
	// kind. Exactly one of the arguments is ever non-NULL, and `column = NULL` is NULL and so
	// never matches, which makes the unused half of the condition inert instead of wrong.
	//
	// Every field is written, with no set-flags: the endpoint is a PUT of one whole answer,
	// so a reply sent without a note is a reply that has no note. That is the difference from
	// SetAttendanceStatus below, which is a PATCH and has to tell absent from null.
	SetAttendanceRSVP(ctx context.Context, arg SetAttendanceRSVPParams) (Attendance, error)
	// Record what happened, which is staff's to write.
	//
	// Clearing the status is a real operation, unlike clearing an RSVP: a coach who ticked
	// the wrong player needs the row to go back to "not recorded", and there is no value in
	// the vocabulary that means that. When the status goes the provenance goes with it --
	// keeping a recorded_at for a status nobody holds would be a timestamp on nothing.
	//
	// Which makes each field a set-flag plus a nullable value, the shape UpdateGame settles
	// on and for the same reason: this is a PATCH, so absent and null are different requests,
	// and a single COALESCE has no way to say "clear it". Without the flags, a coach adding a
	// note to a line would silently erase the status they had just recorded.
	SetAttendanceStatus(ctx context.Context, arg SetAttendanceStatusParams) (Attendance, error)
	SyncTombstoneDiagram(ctx context.Context, arg SyncTombstoneDiagramParams) (int64, error)
	SyncTombstoneDocument(ctx context.Context, arg SyncTombstoneDocumentParams) (int64, error)
	SyncTombstoneDrill(ctx context.Context, arg SyncTombstoneDrillParams) (int64, error)
	SyncTombstoneEvent(ctx context.Context, arg SyncTombstoneEventParams) (int64, error)
	// The one that motivated the rule. medical_notes and the emergency contact of a deleted
	// athlete are the most sensitive fields this service stores, and they were kept forever.
	// email, phone, birthdate and the given/family names are deliberately not touched:
	// SyncUpsertPerson does not write them, REST does, and clearing what cannot be restored
	// would turn a sync delete into permanent loss of data it does not own.
	SyncTombstonePerson(ctx context.Context, arg SyncTombstonePersonParams) (int64, error)
	SyncTombstonePlayer(ctx context.Context, arg SyncTombstonePlayerParams) (int64, error)
	SyncTombstoneSession(ctx context.Context, arg SyncTombstoneSessionParams) (int64, error)
	// Tombstones are per-table: a delete can only affect a row this account owns,
	// so REST-created rows (sync_account_id IS NULL) are never tombstoned.
	//
	// A tombstone clears exactly what its upsert sets, and keeps only what a tombstone needs
	// to do its job: the id, the deleted flag and a fresh seq. It went on holding everything
	// -- names, medical notes, emergency contacts, the whole payload -- for as long as the
	// row existed, and nothing ever revisited them. A coach who deleted an athlete had not
	// deleted that athlete's medical notes. sync_documents already cleared its payload on
	// write; these seven did not (see docs/AUDIT-5.md L1).
	//
	// Clearing precisely the upsert's own columns is what keeps this reversible: pushing the
	// record again restores every field that was cleared, because they are the same fields.
	// Columns the sync upsert never writes are left alone for the same reason -- REST owns
	// them, a sync delete has no business dropping them, and nothing would put them back.
	// The NOT NULL display columns take '' rather than NULL; no read reaches a tombstoned
	// row, so the value is unobservable either way, and '' keeps the constraint honest.
	//
	// The trade, stated once: the server can no longer reconstruct a record from a delete it
	// has applied. There is no undelete endpoint and no read path that returns a tombstoned
	// row, so nothing loses a capability it had -- but a mistaken delete is now the client's
	// to recover from, not ours.
	SyncTombstoneTeam(ctx context.Context, arg SyncTombstoneTeamParams) (int64, error)
	SyncUpsertDiagram(ctx context.Context, arg SyncUpsertDiagramParams) (int64, error)
	SyncUpsertDocument(ctx context.Context, arg SyncUpsertDocumentParams) (int64, error)
	SyncUpsertDrill(ctx context.Context, arg SyncUpsertDrillParams) (int64, error)
	SyncUpsertEvent(ctx context.Context, arg SyncUpsertEventParams) (int64, error)
	// The one statement that may adopt an unowned row, and only the caller's own Person.
	// /auth/apple provisions the coach's Person through CreatePersonWithID with a NULL
	// sync_account_id, and the app then pushes that same id expecting the two to reconcile
	// into one identity (see 0003_person_sync.sql). The second disjunct permits exactly that:
	// persons.id equals the pushing account's id only for the caller's own row, so it cannot
	// be used to claim anyone else's.
	SyncUpsertPerson(ctx context.Context, arg SyncUpsertPersonParams) (int64, error)
	SyncUpsertPlayer(ctx context.Context, arg SyncUpsertPlayerParams) (int64, error)
	SyncUpsertSession(ctx context.Context, arg SyncUpsertSessionParams) (int64, error)
	// Upserts are keyed on the client-supplied primary key, so each conflict clause is
	// guarded on the row's owner: a push naming a row this account does not own affects
	// zero rows, and the handler returns it to the client as a conflict. A NULL owner
	// (a REST-created row) fails the guard too — the separation 0002_sync.sql describes.
	// Ownership never transfers on update, so the SET clauses do not reassign
	// sync_account_id; SyncUpsertPerson is the one exception, see its comment.
	SyncUpsertTeam(ctx context.Context, arg SyncUpsertTeamParams) (int64, error)
	// Every clearable field is a set-flag plus a nullable value, kickoff_at included. It
	// used to be COALESCE(narg, kickoff_at), which reads NULL as "leave this alone" and so
	// leaves no value that means "clear it": a cancelled fixture's kickoff time could not be
	// unset. See docs/AUDIT-2.md L3.
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
	// Only the name. `kind` is deliberately not editable here: handleDeleteMe deletes the
	// caller's *personal* orgs and orphans their clubs, so flipping kind would quietly
	// change what account deletion destroys. That is a product decision with a data-loss
	// edge, not a field on a PATCH body.
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	// Writes the record twice, for the reason UpdateTeam spells out: a pull returns
	// `payload`, so a column-only edit never reaches the phone and is overwritten by its
	// next push.
	//
	// Only four of these columns are in the sync contract -- display_name, the two emergency
	// contact fields and medical_notes are what SyncUpsertPerson projects, so they are what
	// payload_patch may carry. given_name, family_name, birthdate, email and phone are REST's
	// alone: no push writes them and SyncTombstonePerson deliberately spares them, so they
	// need no propagation and must not be invented into a payload the app would not
	// recognise.
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
	// Sessions could be created and deleted over REST but never edited, so a coach who moved
	// Tuesday training to Thursday had to delete the session and build it again -- taking its
	// register with it, now that a session has one. It is the same gap UpdateTeam closed for
	// teams, arriving late because nothing scheduled by a session used to be attended.
	//
	// Written twice, into the columns this API reads and into the payload a pull returns, for
	// the reason UpdateTeam sets out at length: a pull returns `payload`, so a column-only
	// edit is invisible on the phone and the app's next push writes the old values straight
	// back over it, with nothing logged and nobody told.
	//
	// Blocks are deliberately untouched. They are an ordered collection whose ids the payload
	// carries, so replacing them is a different operation from editing the session's own
	// fields -- folding the two together would mean every rename rewrote the plan, and a
	// caller who sent no blocks would erase one.
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	// A REST edit has to reach the app, which is why this writes the record twice.
	//
	// A sync pull returns `payload`, not these columns, so updating the columns alone would
	// leave the edit invisible on the phone -- and the app's next push, built from its own
	// unchanged copy, would write the old values straight back over it. The change would
	// disappear with nothing logged and nobody told.
	//
	// So the caller passes `payload_patch`: the same fields, keyed the way the app's own
	// record keys them, merged over whatever payload is already there. `||` merges only the
	// keys present, so an untouched field keeps its value and a field the server does not
	// project is preserved rather than dropped -- which is what keeps a newer app's extra
	// fields alive across an edit made by an older server.
	//
	// seq is bumped unconditionally. A row with a NULL sync_account_id is invisible to sync
	// and the new seq is simply unread; for a synced row, an edit that did not move the
	// cursor is an edit no device would ever ask for.
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	// Registering is idempotent and re-points the token at whoever is signed in now. See
	// 0012_device_tokens.sql for why the token owns the row rather than the person.
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error)
}

var _ Querier = (*Queries)(nil)
