// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimGamesDueForReminder = `-- name: ClaimGamesDueForReminder :many

UPDATE games SET reminder_sent_at = now()
WHERE reminder_sent_at IS NULL
  AND id IN (
    SELECT g.id FROM games g
    JOIN teams t ON t.id = g.team_id AND t.deleted = false
    WHERE g.reminder_sent_at IS NULL
      AND g.status = 'scheduled'
      AND g.kickoff_at IS NOT NULL
      AND g.kickoff_at > now()
      AND g.kickoff_at <= $1
  )
RETURNING id, team_id, opponent, kickoff_at
`

type ClaimGamesDueForReminderRow struct {
	ID        uuid.UUID          `json:"id"`
	TeamID    uuid.UUID          `json:"team_id"`
	Opponent  *string            `json:"opponent"`
	KickoffAt pgtype.Timestamptz `json:"kickoff_at"`
}

// Reminders: chasing the squad that has not replied yet -----------------------
// Take the fixtures that are close enough to chase, and mark them chased in the same
// statement.
//
// The claim is the point. A deployed service runs more than one instance and every
// instance sweeps on the same schedule, so a select-then-update would hand the same
// fixture to all of them and every player would get one push per replica. Here the row is
// only returned if this statement is the one that set the column: under READ COMMITTED a
// second instance re-evaluates `reminder_sent_at IS NULL` after the first commits, finds
// it set, and updates nothing. No advisory lock, no leader election, no SKIP LOCKED --
// the column that records the work is the same column that claims it.
//
// Only 'scheduled' games. A cancelled fixture has nothing to reply to (POST /rsvp refuses
// it), and a completed one is in the past by definition.
//
// The upper bound comes in as an instant rather than an interval so the caller owns the
// lead time, and `kickoff_at > now()` keeps a match that has already started out of it: a
// sweep that fell behind should stay quiet rather than ask a squad whether they are
// coming to something that kicked off an hour ago.
func (q *Queries) ClaimGamesDueForReminder(ctx context.Context, until pgtype.Timestamptz) ([]ClaimGamesDueForReminderRow, error) {
	rows, err := q.db.Query(ctx, claimGamesDueForReminder, until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimGamesDueForReminderRow
	for rows.Next() {
		var i ClaimGamesDueForReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Opponent,
			&i.KickoffAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimSessionsDueForReminder = `-- name: ClaimSessionsDueForReminder :many
UPDATE sessions SET reminder_sent_at = now()
WHERE reminder_sent_at IS NULL
  AND id IN (
    SELECT s.id FROM sessions s
    JOIN teams t ON t.id = s.team_id AND t.deleted = false
    WHERE s.reminder_sent_at IS NULL
      AND s.deleted = false
      AND s.team_id IS NOT NULL
      AND s.scheduled_at IS NOT NULL
      AND s.scheduled_at > now()
      AND s.scheduled_at <= $1
  )
RETURNING id, team_id, title, scheduled_at
`

type ClaimSessionsDueForReminderRow struct {
	ID          uuid.UUID          `json:"id"`
	TeamID      *uuid.UUID         `json:"team_id"`
	Title       string             `json:"title"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

// The training half, claimed the same way. Two conditions differ: a session has no status
// column, and its team is optional -- a plan a coach drafted for themselves has no roster
// to chase, so a NULL team_id drops out here rather than producing a sweep that finds
// nobody.
func (q *Queries) ClaimSessionsDueForReminder(ctx context.Context, until pgtype.Timestamptz) ([]ClaimSessionsDueForReminderRow, error) {
	rows, err := q.db.Query(ctx, claimSessionsDueForReminder, until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimSessionsDueForReminderRow
	for rows.Next() {
		var i ClaimSessionsDueForReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.ScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnansweredReachablePeopleForEvent = `-- name: ListUnansweredReachablePeopleForEvent :many
WITH unanswered AS (
    SELECT r.person_id FROM roster_memberships r
    WHERE r.team_id = $1 AND r.left_on IS NULL
      AND NOT EXISTS (
        SELECT 1 FROM attendances a
        WHERE a.person_id = r.person_id
          AND (a.game_id = $2 OR a.session_id = $3)
          AND a.rsvp IS NOT NULL
      )
), people AS (
    SELECT person_id FROM unanswered
    UNION
    SELECT g.guardian_person_id AS person_id FROM guardianships g
    WHERE g.child_person_id IN (SELECT person_id FROM unanswered)
)
SELECT p.id FROM people pe
JOIN persons p ON p.id = pe.person_id AND p.deleted = false
WHERE EXISTS (SELECT 1 FROM device_tokens d WHERE d.person_id = p.id)
`

type ListUnansweredReachablePeopleForEventParams struct {
	TeamID    uuid.UUID  `json:"team_id"`
	GameID    *uuid.UUID `json:"game_id"`
	SessionID *uuid.UUID `json:"session_id"`
}

// Who still owes an answer, and can be reached to be asked for it.
//
// Narrower than ListReachablePeopleForTeam in the way that matters: someone who already
// said they are coming has done what was asked, and chasing them is how a reminder
// becomes noise people turn off. A line with a recorded attendance but no RSVP still
// counts as unanswered -- the coach marking someone present is not that person replying.
//
// Guardians come along for the child's silence, not their own. A nine-year-old has no
// device and no login; the reply is going to come from a parent or not at all, so the
// parents of every unanswered player are in the set even though the players themselves
// may not be.
func (q *Queries) ListUnansweredReachablePeopleForEvent(ctx context.Context, arg ListUnansweredReachablePeopleForEventParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnansweredReachablePeopleForEvent, arg.TeamID, arg.GameID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
