// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listFixtureStats = `-- name: ListFixtureStats :many
SELECT s.id, s.user_id, s.match_id, s.fixture_id, s.goals, s.assists, s.yellow_cards, s.red_cards, s.minutes_played, s.created_at, s.updated_at,
    u.email, u.display_name, u.position, u.skill_level, u.bio, u.avatar_url, u.created_at AS user_created_at
FROM player_match_stats s
JOIN users u ON u.id = s.user_id
WHERE s.fixture_id = $1
ORDER BY s.goals DESC, s.assists DESC
`

type ListFixtureStatsRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	MatchID       *uuid.UUID         `json:"match_id"`
	FixtureID     *uuid.UUID         `json:"fixture_id"`
	Goals         int32              `json:"goals"`
	Assists       int32              `json:"assists"`
	YellowCards   int32              `json:"yellow_cards"`
	RedCards      int32              `json:"red_cards"`
	MinutesPlayed int32              `json:"minutes_played"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	Position      *string            `json:"position"`
	SkillLevel    int32              `json:"skill_level"`
	Bio           *string            `json:"bio"`
	AvatarUrl     *string            `json:"avatar_url"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) ListFixtureStats(ctx context.Context, fixtureID *uuid.UUID) ([]ListFixtureStatsRow, error) {
	rows, err := q.db.Query(ctx, listFixtureStats, fixtureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFixtureStatsRow
	for rows.Next() {
		var i ListFixtureStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MatchID,
			&i.FixtureID,
			&i.Goals,
			&i.Assists,
			&i.YellowCards,
			&i.RedCards,
			&i.MinutesPlayed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
			&i.Position,
			&i.SkillLevel,
			&i.Bio,
			&i.AvatarUrl,
			&i.UserCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchStats = `-- name: ListMatchStats :many
SELECT s.id, s.user_id, s.match_id, s.fixture_id, s.goals, s.assists, s.yellow_cards, s.red_cards, s.minutes_played, s.created_at, s.updated_at,
    u.email, u.display_name, u.position, u.skill_level, u.bio, u.avatar_url, u.created_at AS user_created_at
FROM player_match_stats s
JOIN users u ON u.id = s.user_id
WHERE s.match_id = $1
ORDER BY s.goals DESC, s.assists DESC
`

type ListMatchStatsRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	MatchID       *uuid.UUID         `json:"match_id"`
	FixtureID     *uuid.UUID         `json:"fixture_id"`
	Goals         int32              `json:"goals"`
	Assists       int32              `json:"assists"`
	YellowCards   int32              `json:"yellow_cards"`
	RedCards      int32              `json:"red_cards"`
	MinutesPlayed int32              `json:"minutes_played"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	Position      *string            `json:"position"`
	SkillLevel    int32              `json:"skill_level"`
	Bio           *string            `json:"bio"`
	AvatarUrl     *string            `json:"avatar_url"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) ListMatchStats(ctx context.Context, matchID *uuid.UUID) ([]ListMatchStatsRow, error) {
	rows, err := q.db.Query(ctx, listMatchStats, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchStatsRow
	for rows.Next() {
		var i ListMatchStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MatchID,
			&i.FixtureID,
			&i.Goals,
			&i.Assists,
			&i.YellowCards,
			&i.RedCards,
			&i.MinutesPlayed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
			&i.Position,
			&i.SkillLevel,
			&i.Bio,
			&i.AvatarUrl,
			&i.UserCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFixtureStat = `-- name: UpsertFixtureStat :one
INSERT INTO player_match_stats (user_id, fixture_id, goals, assists, yellow_cards, red_cards, minutes_played)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, fixture_id)
DO UPDATE SET goals = EXCLUDED.goals, assists = EXCLUDED.assists,
    yellow_cards = EXCLUDED.yellow_cards, red_cards = EXCLUDED.red_cards,
    minutes_played = EXCLUDED.minutes_played, updated_at = now()
RETURNING id, user_id, match_id, fixture_id, goals, assists, yellow_cards, red_cards, minutes_played, created_at, updated_at
`

type UpsertFixtureStatParams struct {
	UserID        uuid.UUID  `json:"user_id"`
	FixtureID     *uuid.UUID `json:"fixture_id"`
	Goals         int32      `json:"goals"`
	Assists       int32      `json:"assists"`
	YellowCards   int32      `json:"yellow_cards"`
	RedCards      int32      `json:"red_cards"`
	MinutesPlayed int32      `json:"minutes_played"`
}

func (q *Queries) UpsertFixtureStat(ctx context.Context, arg UpsertFixtureStatParams) (PlayerMatchStat, error) {
	row := q.db.QueryRow(ctx, upsertFixtureStat,
		arg.UserID,
		arg.FixtureID,
		arg.Goals,
		arg.Assists,
		arg.YellowCards,
		arg.RedCards,
		arg.MinutesPlayed,
	)
	var i PlayerMatchStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatchID,
		&i.FixtureID,
		&i.Goals,
		&i.Assists,
		&i.YellowCards,
		&i.RedCards,
		&i.MinutesPlayed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMatchStat = `-- name: UpsertMatchStat :one
INSERT INTO player_match_stats (user_id, match_id, goals, assists, yellow_cards, red_cards, minutes_played)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, match_id)
DO UPDATE SET goals = EXCLUDED.goals, assists = EXCLUDED.assists,
    yellow_cards = EXCLUDED.yellow_cards, red_cards = EXCLUDED.red_cards,
    minutes_played = EXCLUDED.minutes_played, updated_at = now()
RETURNING id, user_id, match_id, fixture_id, goals, assists, yellow_cards, red_cards, minutes_played, created_at, updated_at
`

type UpsertMatchStatParams struct {
	UserID        uuid.UUID  `json:"user_id"`
	MatchID       *uuid.UUID `json:"match_id"`
	Goals         int32      `json:"goals"`
	Assists       int32      `json:"assists"`
	YellowCards   int32      `json:"yellow_cards"`
	RedCards      int32      `json:"red_cards"`
	MinutesPlayed int32      `json:"minutes_played"`
}

func (q *Queries) UpsertMatchStat(ctx context.Context, arg UpsertMatchStatParams) (PlayerMatchStat, error) {
	row := q.db.QueryRow(ctx, upsertMatchStat,
		arg.UserID,
		arg.MatchID,
		arg.Goals,
		arg.Assists,
		arg.YellowCards,
		arg.RedCards,
		arg.MinutesPlayed,
	)
	var i PlayerMatchStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatchID,
		&i.FixtureID,
		&i.Goals,
		&i.Assists,
		&i.YellowCards,
		&i.RedCards,
		&i.MinutesPlayed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
