// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const listSyncChangesSince = `-- name: ListSyncChangesSince :many
SELECT delta.type, delta.id, delta.payload, delta.deleted, delta.seq FROM (
    SELECT 'Team'::text    AS type, t.id::text AS id, t.payload AS payload, t.deleted AS deleted, t.seq AS seq
        FROM teams    t WHERE t.sync_account_id = $1 AND t.seq > $2
    UNION ALL
    SELECT 'Drill'::text,   d.id::text, d.payload, d.deleted, d.seq
        FROM drills   d WHERE d.sync_account_id = $1 AND d.seq > $2
    UNION ALL
    SELECT 'Session'::text, s.id::text, s.payload, s.deleted, s.seq
        FROM sessions s WHERE s.sync_account_id = $1 AND s.seq > $2
    UNION ALL
    SELECT 'Person'::text, pe.id::text, pe.payload, pe.deleted, pe.seq
        FROM persons pe WHERE pe.sync_account_id = $1 AND pe.seq > $2
    UNION ALL
    SELECT sd.type, sd.id, sd.payload, sd.deleted, sd.seq
        FROM sync_documents sd WHERE sd.sync_account_id = $1 AND sd.seq > $2
) delta
ORDER BY delta.seq ASC
`

type ListSyncChangesSinceParams struct {
	SyncAccountID *uuid.UUID `json:"sync_account_id"`
	Seq           *int64     `json:"seq"`
}

type ListSyncChangesSinceRow struct {
	Type    string `json:"type"`
	ID      string `json:"id"`
	Payload []byte `json:"payload"`
	Deleted bool   `json:"deleted"`
	Seq     *int64 `json:"seq"`
}

// The delta an account hasn't seen: synced rows across every source, ordered by
// the shared cursor. Projected tables contribute their type; sync_documents
// carries its own.
func (q *Queries) ListSyncChangesSince(ctx context.Context, arg ListSyncChangesSinceParams) ([]ListSyncChangesSinceRow, error) {
	rows, err := q.db.Query(ctx, listSyncChangesSince, arg.SyncAccountID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncChangesSinceRow
	for rows.Next() {
		var i ListSyncChangesSinceRow
		if err := rows.Scan(
			&i.Type,
			&i.ID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncTombstoneDocument = `-- name: SyncTombstoneDocument :exec
INSERT INTO sync_documents (sync_account_id, type, id, payload, deleted, seq)
VALUES ($1, $2, $3, NULL, true, nextval('sync_seq'))
ON CONFLICT (sync_account_id, type, id) DO UPDATE
SET payload = NULL, deleted = true, seq = nextval('sync_seq'), updated_at = now()
`

type SyncTombstoneDocumentParams struct {
	SyncAccountID uuid.UUID `json:"sync_account_id"`
	Type          string    `json:"type"`
	ID            string    `json:"id"`
}

func (q *Queries) SyncTombstoneDocument(ctx context.Context, arg SyncTombstoneDocumentParams) error {
	_, err := q.db.Exec(ctx, syncTombstoneDocument, arg.SyncAccountID, arg.Type, arg.ID)
	return err
}

const syncTombstoneDrill = `-- name: SyncTombstoneDrill :exec
UPDATE drills SET deleted = true, seq = nextval('sync_seq'), updated_at = now()
WHERE id = $1 AND sync_account_id = $2
`

type SyncTombstoneDrillParams struct {
	ID            uuid.UUID  `json:"id"`
	SyncAccountID *uuid.UUID `json:"sync_account_id"`
}

func (q *Queries) SyncTombstoneDrill(ctx context.Context, arg SyncTombstoneDrillParams) error {
	_, err := q.db.Exec(ctx, syncTombstoneDrill, arg.ID, arg.SyncAccountID)
	return err
}

const syncTombstonePerson = `-- name: SyncTombstonePerson :exec
UPDATE persons SET deleted = true, seq = nextval('sync_seq'), updated_at = now()
WHERE id = $1 AND sync_account_id = $2
`

type SyncTombstonePersonParams struct {
	ID            uuid.UUID  `json:"id"`
	SyncAccountID *uuid.UUID `json:"sync_account_id"`
}

func (q *Queries) SyncTombstonePerson(ctx context.Context, arg SyncTombstonePersonParams) error {
	_, err := q.db.Exec(ctx, syncTombstonePerson, arg.ID, arg.SyncAccountID)
	return err
}

const syncTombstoneSession = `-- name: SyncTombstoneSession :exec
UPDATE sessions SET deleted = true, seq = nextval('sync_seq'), updated_at = now()
WHERE id = $1 AND sync_account_id = $2
`

type SyncTombstoneSessionParams struct {
	ID            uuid.UUID  `json:"id"`
	SyncAccountID *uuid.UUID `json:"sync_account_id"`
}

func (q *Queries) SyncTombstoneSession(ctx context.Context, arg SyncTombstoneSessionParams) error {
	_, err := q.db.Exec(ctx, syncTombstoneSession, arg.ID, arg.SyncAccountID)
	return err
}

const syncTombstoneTeam = `-- name: SyncTombstoneTeam :exec

UPDATE teams SET deleted = true, seq = nextval('sync_seq'), updated_at = now()
WHERE id = $1 AND sync_account_id = $2
`

type SyncTombstoneTeamParams struct {
	ID            uuid.UUID  `json:"id"`
	SyncAccountID *uuid.UUID `json:"sync_account_id"`
}

// Tombstones are per-table: a delete can only affect a row this account owns,
// so REST-created rows (sync_account_id IS NULL) are never tombstoned.
func (q *Queries) SyncTombstoneTeam(ctx context.Context, arg SyncTombstoneTeamParams) error {
	_, err := q.db.Exec(ctx, syncTombstoneTeam, arg.ID, arg.SyncAccountID)
	return err
}

const syncUpsertDocument = `-- name: SyncUpsertDocument :exec
INSERT INTO sync_documents (sync_account_id, type, id, payload, deleted, seq)
VALUES ($1, $2, $3, $4, false, nextval('sync_seq'))
ON CONFLICT (sync_account_id, type, id) DO UPDATE
SET payload = EXCLUDED.payload, deleted = false, seq = nextval('sync_seq'), updated_at = now()
`

type SyncUpsertDocumentParams struct {
	SyncAccountID uuid.UUID `json:"sync_account_id"`
	Type          string    `json:"type"`
	ID            string    `json:"id"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) SyncUpsertDocument(ctx context.Context, arg SyncUpsertDocumentParams) error {
	_, err := q.db.Exec(ctx, syncUpsertDocument,
		arg.SyncAccountID,
		arg.Type,
		arg.ID,
		arg.Payload,
	)
	return err
}

const syncUpsertDrill = `-- name: SyncUpsertDrill :exec
INSERT INTO drills (id, organization_id, author_person_id, sync_account_id, name, description, payload, deleted, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, false, nextval('sync_seq'))
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, description = EXCLUDED.description,
    sync_account_id = EXCLUDED.sync_account_id, payload = EXCLUDED.payload,
    deleted = false, seq = nextval('sync_seq'), updated_at = now()
`

type SyncUpsertDrillParams struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	AuthorPersonID *uuid.UUID `json:"author_person_id"`
	SyncAccountID  *uuid.UUID `json:"sync_account_id"`
	Name           string     `json:"name"`
	Description    *string    `json:"description"`
	Payload        []byte     `json:"payload"`
}

func (q *Queries) SyncUpsertDrill(ctx context.Context, arg SyncUpsertDrillParams) error {
	_, err := q.db.Exec(ctx, syncUpsertDrill,
		arg.ID,
		arg.OrganizationID,
		arg.AuthorPersonID,
		arg.SyncAccountID,
		arg.Name,
		arg.Description,
		arg.Payload,
	)
	return err
}

const syncUpsertPerson = `-- name: SyncUpsertPerson :exec
INSERT INTO persons (id, sync_account_id, display_name, emergency_contact_name, emergency_contact_phone, medical_notes, payload, deleted, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, false, nextval('sync_seq'))
ON CONFLICT (id) DO UPDATE
SET display_name = EXCLUDED.display_name,
    emergency_contact_name = EXCLUDED.emergency_contact_name,
    emergency_contact_phone = EXCLUDED.emergency_contact_phone,
    medical_notes = EXCLUDED.medical_notes,
    sync_account_id = EXCLUDED.sync_account_id, payload = EXCLUDED.payload,
    deleted = false, seq = nextval('sync_seq'), updated_at = now()
`

type SyncUpsertPersonParams struct {
	ID                    uuid.UUID  `json:"id"`
	SyncAccountID         *uuid.UUID `json:"sync_account_id"`
	DisplayName           string     `json:"display_name"`
	EmergencyContactName  *string    `json:"emergency_contact_name"`
	EmergencyContactPhone *string    `json:"emergency_contact_phone"`
	MedicalNotes          *string    `json:"medical_notes"`
	Payload               []byte     `json:"payload"`
}

func (q *Queries) SyncUpsertPerson(ctx context.Context, arg SyncUpsertPersonParams) error {
	_, err := q.db.Exec(ctx, syncUpsertPerson,
		arg.ID,
		arg.SyncAccountID,
		arg.DisplayName,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalNotes,
		arg.Payload,
	)
	return err
}

const syncUpsertSession = `-- name: SyncUpsertSession :exec
INSERT INTO sessions (id, organization_id, author_person_id, sync_account_id, title, notes, payload, deleted, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, false, nextval('sync_seq'))
ON CONFLICT (id) DO UPDATE
SET title = EXCLUDED.title, notes = EXCLUDED.notes,
    sync_account_id = EXCLUDED.sync_account_id, payload = EXCLUDED.payload,
    deleted = false, seq = nextval('sync_seq'), updated_at = now()
`

type SyncUpsertSessionParams struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	AuthorPersonID *uuid.UUID `json:"author_person_id"`
	SyncAccountID  *uuid.UUID `json:"sync_account_id"`
	Title          string     `json:"title"`
	Notes          *string    `json:"notes"`
	Payload        []byte     `json:"payload"`
}

func (q *Queries) SyncUpsertSession(ctx context.Context, arg SyncUpsertSessionParams) error {
	_, err := q.db.Exec(ctx, syncUpsertSession,
		arg.ID,
		arg.OrganizationID,
		arg.AuthorPersonID,
		arg.SyncAccountID,
		arg.Title,
		arg.Notes,
		arg.Payload,
	)
	return err
}

const syncUpsertTeam = `-- name: SyncUpsertTeam :exec
INSERT INTO teams (id, organization_id, sync_account_id, name, age_group, season, payload, deleted, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, false, nextval('sync_seq'))
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, age_group = EXCLUDED.age_group, season = EXCLUDED.season,
    sync_account_id = EXCLUDED.sync_account_id, payload = EXCLUDED.payload,
    deleted = false, seq = nextval('sync_seq'), updated_at = now()
`

type SyncUpsertTeamParams struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	SyncAccountID  *uuid.UUID `json:"sync_account_id"`
	Name           string     `json:"name"`
	AgeGroup       *string    `json:"age_group"`
	Season         *string    `json:"season"`
	Payload        []byte     `json:"payload"`
}

func (q *Queries) SyncUpsertTeam(ctx context.Context, arg SyncUpsertTeamParams) error {
	_, err := q.db.Exec(ctx, syncUpsertTeam,
		arg.ID,
		arg.OrganizationID,
		arg.SyncAccountID,
		arg.Name,
		arg.AgeGroup,
		arg.Season,
		arg.Payload,
	)
	return err
}
