// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRosterMembership = `-- name: AddRosterMembership :one

INSERT INTO roster_memberships (person_id, team_id, jersey_number, position, joined_on)
VALUES ($1, $2, $3, $4, COALESCE($5, CURRENT_DATE))
RETURNING id, person_id, team_id, jersey_number, position, joined_on, left_on, status, created_at, updated_at
`

type AddRosterMembershipParams struct {
	PersonID     uuid.UUID   `json:"person_id"`
	TeamID       uuid.UUID   `json:"team_id"`
	JerseyNumber *int32      `json:"jersey_number"`
	Position     *string     `json:"position"`
	JoinedOn     interface{} `json:"joined_on"`
}

// Roster (time-bounded memberships) ----------------------------------------
func (q *Queries) AddRosterMembership(ctx context.Context, arg AddRosterMembershipParams) (RosterMembership, error) {
	row := q.db.QueryRow(ctx, addRosterMembership,
		arg.PersonID,
		arg.TeamID,
		arg.JerseyNumber,
		arg.Position,
		arg.JoinedOn,
	)
	var i RosterMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.Position,
		&i.JoinedOn,
		&i.LeftOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (organization_id, name, age_group, season)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, age_group, season, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreateTeamParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	AgeGroup       *string   `json:"age_group"`
	Season         *string   `json:"season"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.OrganizationID,
		arg.Name,
		arg.AgeGroup,
		arg.Season,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AgeGroup,
		&i.Season,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const endRosterMembership = `-- name: EndRosterMembership :one
UPDATE roster_memberships
SET left_on = COALESCE($1, CURRENT_DATE), status = 'inactive', updated_at = now()
WHERE id = $2
RETURNING id, person_id, team_id, jersey_number, position, joined_on, left_on, status, created_at, updated_at
`

type EndRosterMembershipParams struct {
	LeftOn pgtype.Date `json:"left_on"`
	ID     uuid.UUID   `json:"id"`
}

func (q *Queries) EndRosterMembership(ctx context.Context, arg EndRosterMembershipParams) (RosterMembership, error) {
	row := q.db.QueryRow(ctx, endRosterMembership, arg.LeftOn, arg.ID)
	var i RosterMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.Position,
		&i.JoinedOn,
		&i.LeftOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRosterMembership = `-- name: GetActiveRosterMembership :one
SELECT id, person_id, team_id, jersey_number, position, joined_on, left_on, status, created_at, updated_at FROM roster_memberships
WHERE person_id = $1 AND team_id = $2 AND left_on IS NULL
`

type GetActiveRosterMembershipParams struct {
	PersonID uuid.UUID `json:"person_id"`
	TeamID   uuid.UUID `json:"team_id"`
}

func (q *Queries) GetActiveRosterMembership(ctx context.Context, arg GetActiveRosterMembershipParams) (RosterMembership, error) {
	row := q.db.QueryRow(ctx, getActiveRosterMembership, arg.PersonID, arg.TeamID)
	var i RosterMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.Position,
		&i.JoinedOn,
		&i.LeftOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRosterMembership = `-- name: GetRosterMembership :one
SELECT id, person_id, team_id, jersey_number, position, joined_on, left_on, status, created_at, updated_at FROM roster_memberships WHERE id = $1
`

func (q *Queries) GetRosterMembership(ctx context.Context, id uuid.UUID) (RosterMembership, error) {
	row := q.db.QueryRow(ctx, getRosterMembership, id)
	var i RosterMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.Position,
		&i.JoinedOn,
		&i.LeftOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, organization_id, name, age_group, season, created_at, updated_at, sync_account_id, payload, deleted, seq FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AgeGroup,
		&i.Season,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const listActiveRoster = `-- name: ListActiveRoster :many
SELECT r.id, r.jersey_number, r.position, r.joined_on, r.status,
    p.id AS person_id, p.display_name, p.email, p.birthdate
FROM roster_memberships r
JOIN persons p ON p.id = r.person_id
WHERE r.team_id = $1 AND r.left_on IS NULL
ORDER BY r.jersey_number NULLS LAST, p.display_name ASC
`

type ListActiveRosterRow struct {
	ID           uuid.UUID   `json:"id"`
	JerseyNumber *int32      `json:"jersey_number"`
	Position     *string     `json:"position"`
	JoinedOn     pgtype.Date `json:"joined_on"`
	Status       string      `json:"status"`
	PersonID     uuid.UUID   `json:"person_id"`
	DisplayName  string      `json:"display_name"`
	Email        *string     `json:"email"`
	Birthdate    pgtype.Date `json:"birthdate"`
}

func (q *Queries) ListActiveRoster(ctx context.Context, teamID uuid.UUID) ([]ListActiveRosterRow, error) {
	rows, err := q.db.Query(ctx, listActiveRoster, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRosterRow
	for rows.Next() {
		var i ListActiveRosterRow
		if err := rows.Scan(
			&i.ID,
			&i.JerseyNumber,
			&i.Position,
			&i.JoinedOn,
			&i.Status,
			&i.PersonID,
			&i.DisplayName,
			&i.Email,
			&i.Birthdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForPerson = `-- name: ListTeamsForPerson :many
SELECT t.id AS team_id, t.name AS team_name, r.jersey_number, r.position, r.joined_on, r.left_on
FROM roster_memberships r
JOIN teams t ON t.id = r.team_id
WHERE r.person_id = $1
ORDER BY r.joined_on DESC
`

type ListTeamsForPersonRow struct {
	TeamID       uuid.UUID   `json:"team_id"`
	TeamName     string      `json:"team_name"`
	JerseyNumber *int32      `json:"jersey_number"`
	Position     *string     `json:"position"`
	JoinedOn     pgtype.Date `json:"joined_on"`
	LeftOn       pgtype.Date `json:"left_on"`
}

func (q *Queries) ListTeamsForPerson(ctx context.Context, personID uuid.UUID) ([]ListTeamsForPersonRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsForPersonRow
	for rows.Next() {
		var i ListTeamsForPersonRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TeamName,
			&i.JerseyNumber,
			&i.Position,
			&i.JoinedOn,
			&i.LeftOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsInOrg = `-- name: ListTeamsInOrg :many
SELECT t.id, t.organization_id, t.name, t.age_group, t.season, t.created_at, t.updated_at, t.sync_account_id, t.payload, t.deleted, t.seq,
    (SELECT count(*) FROM roster_memberships r WHERE r.team_id = t.id AND r.left_on IS NULL)::bigint AS active_roster_count
FROM teams t
WHERE t.organization_id = $1
ORDER BY t.name ASC
`

type ListTeamsInOrgRow struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Name              string             `json:"name"`
	AgeGroup          *string            `json:"age_group"`
	Season            *string            `json:"season"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SyncAccountID     *uuid.UUID         `json:"sync_account_id"`
	Payload           []byte             `json:"payload"`
	Deleted           bool               `json:"deleted"`
	Seq               *int64             `json:"seq"`
	ActiveRosterCount int64              `json:"active_roster_count"`
}

func (q *Queries) ListTeamsInOrg(ctx context.Context, organizationID uuid.UUID) ([]ListTeamsInOrgRow, error) {
	rows, err := q.db.Query(ctx, listTeamsInOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsInOrgRow
	for rows.Next() {
		var i ListTeamsInOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.AgeGroup,
			&i.Season,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
			&i.ActiveRosterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name       = COALESCE($1, name),
    age_group  = CASE WHEN $2::bool THEN $3 ELSE age_group END,
    season     = CASE WHEN $4::bool THEN $5 ELSE season END,
    updated_at = now()
WHERE id = $6
RETURNING id, organization_id, name, age_group, season, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type UpdateTeamParams struct {
	Name        *string   `json:"name"`
	SetAgeGroup bool      `json:"set_age_group"`
	AgeGroup    *string   `json:"age_group"`
	SetSeason   bool      `json:"set_season"`
	Season      *string   `json:"season"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.SetAgeGroup,
		arg.AgeGroup,
		arg.SetSeason,
		arg.Season,
		arg.ID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AgeGroup,
		&i.Season,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}
