// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRosterMembership = `-- name: AddRosterMembership :one

INSERT INTO roster_memberships (person_id, team_id, jersey_number, position, joined_on)
VALUES ($1, $2, $3, $4, COALESCE($5, CURRENT_DATE))
RETURNING id, person_id, team_id, jersey_number, position, joined_on, left_on, status, created_at, updated_at
`

type AddRosterMembershipParams struct {
	PersonID     uuid.UUID   `json:"person_id"`
	TeamID       uuid.UUID   `json:"team_id"`
	JerseyNumber *int32      `json:"jersey_number"`
	Position     *string     `json:"position"`
	JoinedOn     interface{} `json:"joined_on"`
}

// Roster (time-bounded memberships) ----------------------------------------
func (q *Queries) AddRosterMembership(ctx context.Context, arg AddRosterMembershipParams) (RosterMembership, error) {
	row := q.db.QueryRow(ctx, addRosterMembership,
		arg.PersonID,
		arg.TeamID,
		arg.JerseyNumber,
		arg.Position,
		arg.JoinedOn,
	)
	var i RosterMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.Position,
		&i.JoinedOn,
		&i.LeftOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addTeamStaff = `-- name: AddTeamStaff :exec
INSERT INTO team_staff (team_id, person_id)
VALUES ($1, $2)
ON CONFLICT (team_id, person_id) DO NOTHING
`

type AddTeamStaffParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	PersonID uuid.UUID `json:"person_id"`
}

// Idempotent: a coach already on a team stays on it, and the create path can call this
// without first asking.
func (q *Queries) AddTeamStaff(ctx context.Context, arg AddTeamStaffParams) error {
	_, err := q.db.Exec(ctx, addTeamStaff, arg.TeamID, arg.PersonID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, organization_id, sync_account_id, name, age_group, season, payload, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, nextval('sync_seq'))
RETURNING id, organization_id, name, age_group, season, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type CreateTeamParams struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	SyncAccountID  *uuid.UUID `json:"sync_account_id"`
	Name           string     `json:"name"`
	AgeGroup       *string    `json:"age_group"`
	Season         *string    `json:"season"`
	Payload        []byte     `json:"payload"`
}

// A team created here is a team the app can see. It used to be invisible: a REST insert
// left sync_account_id NULL, and ListSyncChangesSince scopes every branch to an account,
// so nothing this endpoint made ever reached a phone. Editing converged before creating
// did, which left the odd state where a web client could rename a team the app owned but
// not create one of its own.
//
// Three columns make it visible, and all three are needed. sync_account_id puts the row
// in the caller's stream; seq gives a cursor something to deliver; payload is what a pull
// actually returns, so a row without one arrives as a null record the client cannot
// decode.
//
// The payload is built here rather than defaulted, because Swift's Codable throws on a
// missing required key and takes the whole record with it. Team's decoder requires id,
// name, ageGroup, season and accentName -- see Models/Team.swift in the app -- so all
// five are written. organizationID is deliberately left out: the app reads it with
// decodeIfPresent and falls back to its own personal-org constant, which is the right
// answer for a solo coach and better than asserting a server org id the app has never
// seen.
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ID,
		arg.OrganizationID,
		arg.SyncAccountID,
		arg.Name,
		arg.AgeGroup,
		arg.Season,
		arg.Payload,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AgeGroup,
		&i.Season,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
UPDATE teams SET deleted = true, seq = nextval('sync_seq'), updated_at = now(),
    name = '', age_group = NULL, season = NULL, payload = NULL
WHERE id = $1
`

// A REST delete tombstones rather than dropping the row, so the deletion reaches sync
// clients. A hard DELETE produced no row for ListSyncChangesSince to return, so a device
// holding the team was never told it was gone and re-created it on its next push.
// Clears the row's content for the same reason SyncTombstoneTeam does: a tombstone
// needs the id, the flag and a seq, and nothing else. See docs/AUDIT-5.md L1.
func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const endRosterMembership = `-- name: EndRosterMembership :one
UPDATE roster_memberships
SET left_on = COALESCE($1, CURRENT_DATE), status = 'inactive', updated_at = now()
WHERE id = $2
RETURNING id, person_id, team_id, jersey_number, position, joined_on, left_on, status, created_at, updated_at
`

type EndRosterMembershipParams struct {
	LeftOn pgtype.Date `json:"left_on"`
	ID     uuid.UUID   `json:"id"`
}

func (q *Queries) EndRosterMembership(ctx context.Context, arg EndRosterMembershipParams) (RosterMembership, error) {
	row := q.db.QueryRow(ctx, endRosterMembership, arg.LeftOn, arg.ID)
	var i RosterMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.Position,
		&i.JoinedOn,
		&i.LeftOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRosterMembership = `-- name: GetActiveRosterMembership :one
SELECT id, person_id, team_id, jersey_number, position, joined_on, left_on, status, created_at, updated_at FROM roster_memberships
WHERE person_id = $1 AND team_id = $2 AND left_on IS NULL
`

type GetActiveRosterMembershipParams struct {
	PersonID uuid.UUID `json:"person_id"`
	TeamID   uuid.UUID `json:"team_id"`
}

func (q *Queries) GetActiveRosterMembership(ctx context.Context, arg GetActiveRosterMembershipParams) (RosterMembership, error) {
	row := q.db.QueryRow(ctx, getActiveRosterMembership, arg.PersonID, arg.TeamID)
	var i RosterMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TeamID,
		&i.JerseyNumber,
		&i.Position,
		&i.JoinedOn,
		&i.LeftOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, organization_id, name, age_group, season, created_at, updated_at, sync_account_id, payload, deleted, seq FROM teams WHERE id = $1 AND deleted = false
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AgeGroup,
		&i.Season,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}

const listActiveRoster = `-- name: ListActiveRoster :many
SELECT r.id, r.jersey_number, r.position, r.joined_on, r.status,
    p.id AS person_id, p.display_name, p.email, p.birthdate
FROM roster_memberships r
JOIN persons p ON p.id = r.person_id
WHERE r.team_id = $1 AND r.left_on IS NULL AND p.deleted = false
ORDER BY r.jersey_number NULLS LAST, p.display_name ASC
`

type ListActiveRosterRow struct {
	ID           uuid.UUID   `json:"id"`
	JerseyNumber *int32      `json:"jersey_number"`
	Position     *string     `json:"position"`
	JoinedOn     pgtype.Date `json:"joined_on"`
	Status       string      `json:"status"`
	PersonID     uuid.UUID   `json:"person_id"`
	DisplayName  string      `json:"display_name"`
	Email        *string     `json:"email"`
	Birthdate    pgtype.Date `json:"birthdate"`
}

func (q *Queries) ListActiveRoster(ctx context.Context, teamID uuid.UUID) ([]ListActiveRosterRow, error) {
	rows, err := q.db.Query(ctx, listActiveRoster, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRosterRow
	for rows.Next() {
		var i ListActiveRosterRow
		if err := rows.Scan(
			&i.ID,
			&i.JerseyNumber,
			&i.Position,
			&i.JoinedOn,
			&i.Status,
			&i.PersonID,
			&i.DisplayName,
			&i.Email,
			&i.Birthdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamStaff = `-- name: ListTeamStaff :many
SELECT p.id, p.display_name, p.given_name, p.family_name, p.birthdate, p.email, p.phone, p.emergency_contact_name, p.emergency_contact_phone, p.medical_notes, p.created_at, p.updated_at, p.sync_account_id, p.payload, p.deleted, p.seq FROM team_staff ts
JOIN persons p ON p.id = ts.person_id
WHERE ts.team_id = $1 AND p.deleted = false
ORDER BY p.display_name ASC
`

func (q *Queries) ListTeamStaff(ctx context.Context, teamID uuid.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listTeamStaff, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GivenName,
			&i.FamilyName,
			&i.Birthdate,
			&i.Email,
			&i.Phone,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForPerson = `-- name: ListTeamsForPerson :many
SELECT t.id AS team_id, t.name AS team_name, r.jersey_number, r.position, r.joined_on, r.left_on
FROM roster_memberships r
JOIN teams t ON t.id = r.team_id
WHERE r.person_id = $1
ORDER BY r.joined_on DESC
`

type ListTeamsForPersonRow struct {
	TeamID       uuid.UUID   `json:"team_id"`
	TeamName     string      `json:"team_name"`
	JerseyNumber *int32      `json:"jersey_number"`
	Position     *string     `json:"position"`
	JoinedOn     pgtype.Date `json:"joined_on"`
	LeftOn       pgtype.Date `json:"left_on"`
}

func (q *Queries) ListTeamsForPerson(ctx context.Context, personID uuid.UUID) ([]ListTeamsForPersonRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsForPersonRow
	for rows.Next() {
		var i ListTeamsForPersonRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TeamName,
			&i.JerseyNumber,
			&i.Position,
			&i.JoinedOn,
			&i.LeftOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsVisibleInOrg = `-- name: ListTeamsVisibleInOrg :many
SELECT t.id, t.organization_id, t.name, t.age_group, t.season, t.created_at, t.updated_at, t.sync_account_id, t.payload, t.deleted, t.seq, (
    SELECT count(*) FROM roster_memberships r
    WHERE r.team_id = t.id AND r.left_on IS NULL
) AS active_roster_count
FROM teams t
WHERE t.organization_id = $1
  AND t.deleted = false
  AND (
    $2::bool
    OR EXISTS (SELECT 1 FROM team_staff ts
                WHERE ts.team_id = t.id AND ts.person_id = $3)
    OR EXISTS (SELECT 1 FROM roster_memberships r
                WHERE r.team_id = t.id AND r.left_on IS NULL
                  AND (r.person_id = $3
                    OR r.person_id IN (SELECT child_person_id FROM guardianships
                                        WHERE guardian_person_id = $3)))
  )
ORDER BY t.name ASC
`

type ListTeamsVisibleInOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SeeAll         bool      `json:"see_all"`
	PersonID       uuid.UUID `json:"person_id"`
}

type ListTeamsVisibleInOrgRow struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Name              string             `json:"name"`
	AgeGroup          *string            `json:"age_group"`
	Season            *string            `json:"season"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SyncAccountID     *uuid.UUID         `json:"sync_account_id"`
	Payload           []byte             `json:"payload"`
	Deleted           bool               `json:"deleted"`
	Seq               *int64             `json:"seq"`
	ActiveRosterCount int64              `json:"active_roster_count"`
}

// The teams a caller may see, which is a different set per role.
//
// One statement rather than one per role, because every non-admin arm asks the same
// question in the end: is this team connected to me? A coach is connected by staffing
// it, a player by being rostered on it, a parent through a child. Someone who is two of
// those -- a parent who also coaches, which the role model explicitly allows -- gets the
// union without any branch having to remember they exist.
//
// `see_all` is the whole of the role logic: admins and directors see the organization,
// per the permission matrix. Everyone else gets the connected set, and a coach who
// staffs nothing sees nothing, which is the correct answer to "your teams" rather than
// an error.
func (q *Queries) ListTeamsVisibleInOrg(ctx context.Context, arg ListTeamsVisibleInOrgParams) ([]ListTeamsVisibleInOrgRow, error) {
	rows, err := q.db.Query(ctx, listTeamsVisibleInOrg, arg.OrganizationID, arg.SeeAll, arg.PersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsVisibleInOrgRow
	for rows.Next() {
		var i ListTeamsVisibleInOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.AgeGroup,
			&i.Season,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncAccountID,
			&i.Payload,
			&i.Deleted,
			&i.Seq,
			&i.ActiveRosterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamStaff = `-- name: RemoveTeamStaff :execrows
DELETE FROM team_staff WHERE team_id = $1 AND person_id = $2
`

type RemoveTeamStaffParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	PersonID uuid.UUID `json:"person_id"`
}

func (q *Queries) RemoveTeamStaff(ctx context.Context, arg RemoveTeamStaffParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamStaff, arg.TeamID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name       = COALESCE($1, name),
    age_group  = CASE WHEN $2::bool THEN $3 ELSE age_group END,
    season     = CASE WHEN $4::bool THEN $5 ELSE season END,
    payload    = CASE WHEN $6::bool
                      THEN COALESCE(payload, '{}'::jsonb) || $7::jsonb
                      ELSE payload END,
    seq        = nextval('sync_seq'),
    updated_at = now()
WHERE id = $8
RETURNING id, organization_id, name, age_group, season, created_at, updated_at, sync_account_id, payload, deleted, seq
`

type UpdateTeamParams struct {
	Name         *string   `json:"name"`
	SetAgeGroup  bool      `json:"set_age_group"`
	AgeGroup     *string   `json:"age_group"`
	SetSeason    bool      `json:"set_season"`
	Season       *string   `json:"season"`
	PatchPayload bool      `json:"patch_payload"`
	PayloadPatch []byte    `json:"payload_patch"`
	ID           uuid.UUID `json:"id"`
}

// A REST edit has to reach the app, which is why this writes the record twice.
//
// A sync pull returns `payload`, not these columns, so updating the columns alone would
// leave the edit invisible on the phone -- and the app's next push, built from its own
// unchanged copy, would write the old values straight back over it. The change would
// disappear with nothing logged and nobody told.
//
// So the caller passes `payload_patch`: the same fields, keyed the way the app's own
// record keys them, merged over whatever payload is already there. `||` merges only the
// keys present, so an untouched field keeps its value and a field the server does not
// project is preserved rather than dropped -- which is what keeps a newer app's extra
// fields alive across an edit made by an older server.
//
// seq is bumped unconditionally. A row with a NULL sync_account_id is invisible to sync
// and the new seq is simply unread; for a synced row, an edit that did not move the
// cursor is an edit no device would ever ask for.
func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.SetAgeGroup,
		arg.AgeGroup,
		arg.SetSeason,
		arg.Season,
		arg.PatchPayload,
		arg.PayloadPatch,
		arg.ID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AgeGroup,
		&i.Season,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncAccountID,
		&i.Payload,
		&i.Deleted,
		&i.Seq,
	)
	return i, err
}
