// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role, jersey_number)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, user_id, role, jersey_number, joined_at
`

type AddTeamMemberParams struct {
	TeamID       uuid.UUID `json:"team_id"`
	UserID       uuid.UUID `json:"user_id"`
	Role         string    `json:"role"`
	JerseyNumber *int32    `json:"jersey_number"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.JerseyNumber,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JerseyNumber,
		&i.JoinedAt,
	)
	return i, err
}

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT count(*)::bigint FROM team_members WHERE team_id = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMembers, teamID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, crest_url, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, crest_url, owner_id, created_at, updated_at
`

type CreateTeamParams struct {
	Name     string    `json:"name"`
	CrestUrl *string   `json:"crest_url"`
	OwnerID  uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.CrestUrl, arg.OwnerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CrestUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteTeamMember = `-- name: DeleteTeamMember :execrows
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type DeleteTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeamMember, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, crest_url, owner_id, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CrestUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT id, team_id, user_id, role, jersey_number, joined_at FROM team_members WHERE team_id = $1 AND user_id = $2
`

type GetTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JerseyNumber,
		&i.JoinedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT m.id, m.role, m.jersey_number, m.joined_at,
    u.id AS user_id, u.email, u.display_name, u.position, u.skill_level, u.bio, u.avatar_url, u.created_at AS user_created_at
FROM team_members m
JOIN users u ON u.id = m.user_id
WHERE m.team_id = $1
ORDER BY m.joined_at ASC
`

type ListTeamMembersRow struct {
	ID            uuid.UUID          `json:"id"`
	Role          string             `json:"role"`
	JerseyNumber  *int32             `json:"jersey_number"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
	UserID        uuid.UUID          `json:"user_id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	Position      *string            `json:"position"`
	SkillLevel    int32              `json:"skill_level"`
	Bio           *string            `json:"bio"`
	AvatarUrl     *string            `json:"avatar_url"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.JerseyNumber,
			&i.JoinedAt,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Position,
			&i.SkillLevel,
			&i.Bio,
			&i.AvatarUrl,
			&i.UserCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.name, t.crest_url, t.owner_id, t.created_at, t.updated_at,
    (SELECT count(*) FROM team_members m WHERE m.team_id = t.id)::bigint AS member_count
FROM teams t
WHERE ($1::text IS NULL OR t.name ILIKE '%' || $1 || '%')
ORDER BY t.name ASC
LIMIT $3 OFFSET $2
`

type ListTeamsParams struct {
	Q   *string `json:"q"`
	Off int32   `json:"off"`
	Lim int32   `json:"lim"`
}

type ListTeamsRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	CrestUrl    *string            `json:"crest_url"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MemberCount int64              `json:"member_count"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, arg.Q, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsRow
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CrestUrl,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name       = COALESCE($1, name),
    crest_url  = CASE WHEN $2::bool THEN $3 ELSE crest_url END,
    updated_at = now()
WHERE id = $4
RETURNING id, name, crest_url, owner_id, created_at, updated_at
`

type UpdateTeamParams struct {
	Name        *string   `json:"name"`
	SetCrestUrl bool      `json:"set_crest_url"`
	CrestUrl    *string   `json:"crest_url"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.SetCrestUrl,
		arg.CrestUrl,
		arg.ID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CrestUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
