// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const careerStats = `-- name: CareerStats :one
SELECT
    count(*)                              AS appearances,
    COALESCE(sum(goals), 0)::bigint       AS goals,
    COALESCE(sum(assists), 0)::bigint     AS assists,
    COALESCE(sum(yellow_cards), 0)::bigint AS yellow_cards,
    COALESCE(sum(red_cards), 0)::bigint   AS red_cards,
    COALESCE(sum(minutes_played), 0)::bigint AS minutes_played
FROM player_match_stats
WHERE user_id = $1
`

type CareerStatsRow struct {
	Appearances   int64 `json:"appearances"`
	Goals         int64 `json:"goals"`
	Assists       int64 `json:"assists"`
	YellowCards   int64 `json:"yellow_cards"`
	RedCards      int64 `json:"red_cards"`
	MinutesPlayed int64 `json:"minutes_played"`
}

func (q *Queries) CareerStats(ctx context.Context, userID uuid.UUID) (CareerStatsRow, error) {
	row := q.db.QueryRow(ctx, careerStats, userID)
	var i CareerStatsRow
	err := row.Scan(
		&i.Appearances,
		&i.Goals,
		&i.Assists,
		&i.YellowCards,
		&i.RedCards,
		&i.MinutesPlayed,
	)
	return i, err
}

const countPlayers = `-- name: CountPlayers :one
SELECT count(*) FROM users
WHERE ($1::text IS NULL OR display_name ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR position = $2)
  AND ($3::int IS NULL OR skill_level >= $3)
`

type CountPlayersParams struct {
	Q        *string `json:"q"`
	Position *string `json:"position"`
	MinSkill *int32  `json:"min_skill"`
}

func (q *Queries) CountPlayers(ctx context.Context, arg CountPlayersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayers, arg.Q, arg.Position, arg.MinSkill)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, position, skill_level)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, display_name, position, skill_level, bio, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	DisplayName  string  `json:"display_name"`
	Position     *string `json:"position"`
	SkillLevel   int32   `json:"skill_level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Position,
		arg.SkillLevel,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Position,
		&i.SkillLevel,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, position, skill_level, bio, avatar_url, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Position,
		&i.SkillLevel,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, position, skill_level, bio, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Position,
		&i.SkillLevel,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, email, password_hash, display_name, position, skill_level, bio, avatar_url, created_at, updated_at FROM users
WHERE ($1::text IS NULL OR display_name ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR position = $2)
  AND ($3::int IS NULL OR skill_level >= $3)
ORDER BY display_name ASC
LIMIT $5 OFFSET $4
`

type ListPlayersParams struct {
	Q        *string `json:"q"`
	Position *string `json:"position"`
	MinSkill *int32  `json:"min_skill"`
	Off      int32   `json:"off"`
	Lim      int32   `json:"lim"`
}

func (q *Queries) ListPlayers(ctx context.Context, arg ListPlayersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listPlayers,
		arg.Q,
		arg.Position,
		arg.MinSkill,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Position,
			&i.SkillLevel,
			&i.Bio,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = COALESCE($1, display_name),
    position     = CASE WHEN $2::bool THEN $3 ELSE position END,
    skill_level  = COALESCE($4, skill_level),
    bio          = CASE WHEN $5::bool THEN $6 ELSE bio END,
    avatar_url   = CASE WHEN $7::bool THEN $8 ELSE avatar_url END,
    updated_at   = now()
WHERE id = $9
RETURNING id, email, password_hash, display_name, position, skill_level, bio, avatar_url, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName  *string   `json:"display_name"`
	SetPosition  bool      `json:"set_position"`
	Position     *string   `json:"position"`
	SkillLevel   *int32    `json:"skill_level"`
	SetBio       bool      `json:"set_bio"`
	Bio          *string   `json:"bio"`
	SetAvatarUrl bool      `json:"set_avatar_url"`
	AvatarUrl    *string   `json:"avatar_url"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.SetPosition,
		arg.Position,
		arg.SkillLevel,
		arg.SetBio,
		arg.Bio,
		arg.SetAvatarUrl,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Position,
		&i.SkillLevel,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
