// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, address, city, latitude, longitude, surface)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, address, city, latitude, longitude, surface, created_at
`

type CreateVenueParams struct {
	Name      string   `json:"name"`
	Address   *string  `json:"address"`
	City      *string  `json:"city"`
	Latitude  *float64 `json:"latitude"`
	Longitude *float64 `json:"longitude"`
	Surface   *string  `json:"surface"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Latitude,
		arg.Longitude,
		arg.Surface,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.Surface,
		&i.CreatedAt,
	)
	return i, err
}

const getVenue = `-- name: GetVenue :one
SELECT id, name, address, city, latitude, longitude, surface, created_at FROM venues WHERE id = $1
`

func (q *Queries) GetVenue(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.Surface,
		&i.CreatedAt,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, address, city, latitude, longitude, surface, created_at FROM venues
WHERE ($1::text IS NULL OR city ILIKE '%' || $1 || '%')
ORDER BY name ASC
LIMIT $3 OFFSET $2
`

type ListVenuesParams struct {
	City *string `json:"city"`
	Off  int32   `json:"off"`
	Lim  int32   `json:"lim"`
}

func (q *Queries) ListVenues(ctx context.Context, arg ListVenuesParams) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues, arg.City, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Latitude,
			&i.Longitude,
			&i.Surface,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
